import React,{useState}from'react';

export function BalanceGame({lesson,onSolved}){const[x,setX]=useState(0),[msg,setMsg]=useState('Add mystery blocks until both sides balance.');const total=x+lesson.fixed;const check=()=>total===lesson.target?(setMsg(lesson.explanation),onSolved()):setMsg(total<lesson.target?`Your side weighs ${total}. Add more mystery weight.`:`Your side weighs ${total}. Take some mystery weight away.`);return <><div className="balanceGame"><div className={`balanceBeam ${total===lesson.target?'balanced':total<lesson.target?'tiltLeft':'tiltRight'}`}><div className="balancePan"><span>❓ × {x}</span><small>+ {lesson.fixed}</small></div><div className="balancePivot">▲</div><div className="balancePan"><span>{lesson.target}</span><small>target</small></div></div><div className="stepper"><button onClick={()=>setX(v=>Math.max(0,v-1))}>−</button><b>{x} mystery blocks</b><button onClick={()=>setX(v=>Math.min(12,v+1))}>+</button></div></div><button className="primary" onClick={check}>Test the balance</button><p className="feedback">{msg}</p></>}

export function RatioGame({lesson,onSolved}){const[a,setA]=useState(0),[b,setB]=useState(0),[msg,setMsg]=useState('Build the recipe using the relationship, not a total.');const ok=a>0&&b>0&&a*lesson.ratioB===b*lesson.ratioA;const check=()=>ok?(setMsg(lesson.explanation),onSolved()):setMsg(`Not quite. For every ${lesson.ratioA} ${lesson.aLabel}, you need ${lesson.ratioB} ${lesson.bLabel}.`);return <><div className="ratioWorkbench"><div><span className="ratioObjects">{lesson.aEmoji.repeat(a)||'—'}</span><b>{a} {lesson.aLabel}</b><div className="stepper"><button onClick={()=>setA(v=>Math.max(0,v-1))}>−</button><button onClick={()=>setA(v=>Math.min(8,v+1))}>+</button></div></div><strong>:</strong><div><span className="ratioObjects">{lesson.bEmoji.repeat(b)||'—'}</span><b>{b} {lesson.bLabel}</b><div className="stepper"><button onClick={()=>setB(v=>Math.max(0,v-1))}>−</button><button onClick={()=>setB(v=>Math.min(8,v+1))}>+</button></div></div></div><button className="primary" onClick={check}>Test my ratio</button><p className="feedback">{msg}</p></>}

export function CoordinateGame({lesson,onSolved}){const[x,setX]=useState(0),[y,setY]=useState(0),[msg,setMsg]=useState('Move the rover to the target coordinate.');const check=()=>x===lesson.targetX&&y===lesson.targetY?(setMsg(lesson.explanation),onSolved()):setMsg(`You are at (${x}, ${y}). Keep navigating.`);return <><div className="coordinateGame"><div className="coordinateGrid">{Array.from({length:25},(_,i)=>{const gx=i%5,gy=4-Math.floor(i/5);return <div key={i} className={`${gx===x&&gy===y?'roverCell ':''}${gx===lesson.targetX&&gy===lesson.targetY?'goalCell':''}`}>{gx===x&&gy===y?'🚀':gx===lesson.targetX&&gy===lesson.targetY?'⭐':''}</div>})}</div><div className="coordinateReadout">Position: <b>({x}, {y})</b></div><div className="dpad"><span/><button onClick={()=>setY(v=>Math.min(4,v+1))}>↑</button><span/><button onClick={()=>setX(v=>Math.max(0,v-1))}>←</button><button onClick={()=>setY(v=>Math.max(0,v-1))}>↓</button><button onClick={()=>setX(v=>Math.min(4,v+1))}>→</button></div></div><button className="primary" onClick={check}>Check coordinates</button><p className="feedback">{msg}</p></>}

export function SortGame({lesson,onSolved}){const[left,setLeft]=useState([]),[right,setRight]=useState([]),[msg,setMsg]=useState('Sort each object by its hidden rule.');const placed=new Set([...left,...right]);const add=(i,side)=>{setLeft(v=>v.filter(x=>x!==i));setRight(v=>v.filter(x=>x!==i));side==='left'?setLeft(v=>[...v,i]):setRight(v=>[...v,i])};const check=()=>{if(placed.size<lesson.items.length){setMsg('Place every object first.');return}const ok=lesson.items.every((item,i)=>item.group==='left'?left.includes(i):right.includes(i));ok?(setMsg(lesson.explanation),onSolved()):setMsg('Some objects crossed the rule. Look for what the members of each group share.')};return <><div className="sortSource">{lesson.items.map((item,i)=>!placed.has(i)&&<span key={i}>{item.label}<button onClick={()=>add(i,'left')}>←</button><button onClick={()=>add(i,'right')}>→</button></span>)}</div><div className="sortBins"><div><b>{lesson.leftLabel}</b>{left.map(i=><span key={i}>{lesson.items[i].label}</span>)}</div><div><b>{lesson.rightLabel}</b>{right.map(i=><span key={i}>{lesson.items[i].label}</span>)}</div></div><button className="primary" onClick={check}>Check my groups</button><p className="feedback">{msg}</p></>}
