import React,{useState}from'react';
const stretch=(supportLevel,normal,hard)=>supportLevel==='expert'?hard:normal;
export function ScaleGame({lesson,onSolved,supportLevel='guided'}){const target=stretch(supportLevel,lesson.target,Math.min(3,lesson.target<1?1.5:lesson.target+.5)),[v,setV]=useState(lesson.start??1),[m,setM]=useState(supportLevel==='expert'?`Stretch challenge: resize to ${target}×.`:'Slide to resize every part together.');const check=()=>Math.abs(v-target)<.01?(setM(supportLevel==='expert'?`You preserved proportional scaling at a new factor: ${target}×.`:lesson.explanation),onSolved()):setM(`You are at ${v}×. Aim for ${target}×.`);return <><div className="scaleStage">{supportLevel==='expert'&&<div className="adaptiveHint"><b>🔥 New scale:</b> {target}×</div>}<div className="scaleRobot" style={{transform:`scale(${Math.max(.5,Math.min(1.5,v/1.5))})`}}>🤖</div><b>{v}× size</b><input type="range" min="0.5" max="3" step="0.5" value={v} onChange={e=>setV(+e.target.value)}/></div><button className="primary" onClick={check}>Check the scale</button><p className="feedback">{m}</p></>}
export function EquivalenceGame({lesson,onSolved,supportLevel='guided'}){const[s,setS]=useState([]),[m,setM]=useState(supportLevel==='expert'?'Stretch challenge: connect the amount with no extra hints.':'Select every card that means the target amount.');const check=()=>{const ok=s.length===lesson.correct.length&&lesson.correct.every(x=>s.includes(x));ok?(setM(lesson.explanation),onSolved()):setM('Some representations do not describe the same amount yet.')};return <><div className="equivTarget">Target <b>{lesson.target}</b></div><div className="matchBoard">{lesson.choices.map(x=><button key={x} className={s.includes(x)?'matchTile selected':'matchTile'} onClick={()=>setS(v=>v.includes(x)?v.filter(y=>y!==x):[...v,x])}>{x}</button>)}</div><button className="primary" onClick={check}>Connect the representations</button><p className="feedback">{m}</p></>}
export function ScaleMapGame({lesson,onSolved,supportLevel='guided'}){const expert=supportLevel==='expert',mapUnits=expert?lesson.mapUnits+2:lesson.mapUnits,target=mapUnits*lesson.factor,[v,setV]=useState(0),[m,setM]=useState(expert?`Stretch challenge: ${mapUnits} map blocks now use the same scale.`:'Slide until the map and real distance agree.');const check=()=>v===target?(setM(expert?`Exactly. ${mapUnits} × ${lesson.factor} = ${target}.`:lesson.explanation),onSolved()):setM(`${mapUnits} map blocks at ${lesson.factor} each needs a different real distance.`);return <><div className="mapScaleStage"><div>🗺️ <b>{mapUnits} blocks</b></div><div className="scaleArrow">→</div><div>🛣️ <b>{v} miles</b></div></div><input className="aimSlider" type="range" min="0" max="20" value={v} onChange={e=>setV(+e.target.value)}/><button className="primary" onClick={check}>Check distance</button><p className="feedback">{m}</p></>}
export function RaceGame({lesson,onSolved,supportLevel='guided'}){const expert=supportLevel==='expert',distance=expert?lesson.distance*2:lesson.distance,timeTarget=expert?lesson.timeTarget*2:lesson.timeTarget,[t,setT]=useState(1),[m,setM]=useState(expert?'Stretch challenge: keep the same rate over twice the distance.':'Change the time and watch the pace change.');const rate=(distance/t).toFixed(1);const check=()=>t===timeTarget?(setM(expert?'You preserved the rate while both distance and time scaled up.':lesson.explanation),onSolved()):setM(`That is ${rate} spaces each second. Keep tuning.`);return <><div className="raceTrack"><span style={{left:`${Math.min(90,10+Number(rate)*18)}%`}}>🏎️</span><i/></div><div className="raceControls"><b>{distance} spaces</b><input type="range" min="1" max="16" value={t} onChange={e=>setT(+e.target.value)}/><b>{t} sec → {rate}/sec</b></div><button className="primary" onClick={check}>Run the race</button><p className="feedback">{m}</p></>}
export function MachineGame({lesson,onSolved,supportLevel='guided'}){const expert=supportLevel==='expert',baseInput=lesson.input??4,input=expert&&!lesson.reverse?baseInput+2:baseInput,[v,setV]=useState(0),[m,setM]=useState(expert?'Stretch challenge: use the rule on a fresh input.':'Each card uses one secret rule. Compare what changed from IN to OUT.'),[tested,setTested]=useState(false);const p=lesson.pairs||[],a=p.length>1?(p[1][1]-p[0][1])/(p[1][0]-p[0][0]):1,b=p.length?p[0][1]-a*p[0][0]:0,target=expert&&!lesson.reverse?a*input+b:lesson.target;const check=()=>{setTested(true);v===target?(setM(expert?'You inferred the rule and applied it to a number you had not seen before.':lesson.explanation),onSolved()):setM('The same machine rule must work for every example. Try applying it to the new input.')};return <><div className="machineLesson"><div className="machineCoach"><span>🤖</span><div><small>{expert?'STRETCH MACHINE':'MYSTERY MACHINE'}</small><b>What does my machine do every time?</b></div></div><div className="machineExamples">{p.map(([x,y],i)=><div className="machineExample" key={i}><span className="exampleTag">Example {i+1}</span><div className="machineNumber"><small>IN</small><b>{x}</b></div><span className="flowArrow">→</span><div className="machineBox"><span>⚙️</span></div><span className="flowArrow">→</span><div className="machineNumber output"><small>OUT</small><b>{y}</b></div></div>)}</div><div className="machineQuestion"><h3>{lesson.reverse?'What must go in?':'What comes out?'}</h3><div className="machineExample activeMachine"><div className="machineNumber"><small>{lesson.reverse?'OUT':'IN'}</small><b>{lesson.reverse?'11':input}</b></div><span className="flowArrow">→</span><div className="machineBox mysteryGear"><span>⚙️</span></div><span className="flowArrow">→</span><div className="machineNumber answerNumber"><small>ANSWER</small><b>{v}</b></div></div><div className="machineStepper"><button onClick={()=>setV(x=>Math.max(0,x-1))}>−</button><b>{v}</b><button onClick={()=>setV(x=>Math.min(30,x+1))}>+</button></div></div></div><button className="primary" onClick={check}>Run my answer</button><p className={`feedback ${tested?'':'machinePrompt'}`}>{m}</p></>}
const apply=(v,op)=>op==='mul2'?v*2:op==='add2'?v+2:op==='add1'?v+1:op==='sub1'?v-1:op==='sub2'?v-2:v;
export function RuleBlocksGame({lesson,onSolved,supportLevel='guided'}){const[seq,setSeq]=useState([]),[m,setM]=useState(supportLevel==='expert'?'Stretch challenge: rebuild the rule with no worked example.':'Tap operation blocks in the order you want the machine to use them.');const result=seq.reduce((v,op)=>apply(v,op),lesson.start);const check=()=>result===lesson.target&&seq.join(',')===lesson.solution.join(',')?(setM(lesson.explanation),onSolved()):setM(`Your rule turns ${lesson.start} into ${result}. Try rearranging it.`);return <><div className="ruleFlow"><span>{lesson.start}</span>{seq.map((op,i)=><span key={i}>{lesson.blocks.find(b=>b.op===op)?.label}</span>)}<span>= {result}</span></div><div className="hubTiles">{lesson.blocks.map(b=><button key={b.op} onClick={()=>setSeq(v=>[...v,b.op])}>{b.label}</button>)}<button onClick={()=>setSeq([])}>Reset</button></div><button className="primary" onClick={check}>Run my rule</button><p className="feedback">{m}</p></>}
export function SlopeGame({lesson,onSolved,supportLevel='guided'}){const expert=supportLevel==='expert',riseTarget=expert?lesson.riseTarget*2:lesson.riseTarget,runTarget=expert?lesson.runTarget*2:lesson.runTarget,[rise,setRise]=useState(1),[run,setRun]=useState(1),[m,setM]=useState(expert?'Stretch challenge: build an equivalent slope at a larger scale.':'Build the path by changing how far it rises and runs.');const angle=Math.atan(rise/run)*180/Math.PI;const check=()=>rise===riseTarget&&run===runTarget?(setM(expert?'Same steepness, larger triangle — you preserved the ratio.':lesson.explanation),onSolved()):setM(`Right now your path rises ${rise} for every ${run} across.`);return <><div className="slopeBuilder"><div className="adaptiveHint">{expert&&<><b>🔥 Equivalent slope:</b> rise {riseTarget}, run {runTarget}</>}</div><div className="slopeVisual"><div className="slopeGround"/><div className="slopePath" style={{width:`${Math.min(82,28+run*7)}%`,transform:`rotate(${-angle}deg)`}}><span className="slopeHiker">🥾</span></div></div><div className="slopeControls"><label><span><b>Rise</b><strong>{rise}</strong></span><input type="range" min="1" max="12" value={rise} onChange={e=>setRise(+e.target.value)}/></label><label><span><b>Run</b><strong>{run}</strong></span><input type="range" min="1" max="16" value={run} onChange={e=>setRun(+e.target.value)}/></label></div></div><button className="primary" onClick={check}>Check my path</button><p className="feedback">{m}</p></>}
export function DealGame({lesson,onSolved,supportLevel='guided'}){const expert=supportLevel==='expert',[m,setM]=useState(expert?'Stretch challenge: compare the packages without seeing the unit-price hint.':'Compare what one item costs, not just the package price.');return <><div className="dealCards">{lesson.deals.map((d,i)=><button key={i} onClick={()=>i===lesson.correctIndex?(setM(lesson.explanation),onSolved()):setM(expert?'Recalculate what one item costs in each package.':`${d.label} costs ${d.unit} coins per item.`)}><span>🛒</span><b>{d.label}</b>{!expert&&<small>{d.unit} coins each</small>}</button>)}</div><p className="feedback">{m}</p></>}
export function MissionGame({lesson,onSolved,supportLevel='guided'}){
  const stages=useMemo(()=>{
    if(Array.isArray(lesson.stagePool)&&lesson.stagePool.length){
      const count=Math.min(lesson.stageCount||3,lesson.stagePool.length);
      const shuffled=[...lesson.stagePool].sort(()=>Math.random()-.5).slice(0,count);
      return shuffled.map(group=>{
        const variants=group.variants||[];
        const picked=variants.length?variants[Math.floor(Math.random()*variants.length)]:group;
        return {...group,...picked,variants:undefined};
      });
    }
    return lesson.stages||[];
  },[lesson]);
  const[stage,setStage]=useState(0),[v,setV]=useState(0),[done,setDone]=useState([]),[m,setM]=useState(supportLevel==='expert'?'Stretch mission: combine the ideas again with minimal clues.':'Bring all three systems online to launch the mission.');
  const s=stages[stage]||{label:'Control',question:'Set the control to 0.',target:0};
  const icons=['🗺️','🏎️','⚙️','🧩','🎯'];
  const step=s.step??(s.suffix==='%'?5:(s.target>=20?5:1));
  const max=s.max??(s.suffix==='%'?100:Math.max(30,s.target*2));
  const suffix=s.suffix||'';
  const check=()=>{
    if(v!==s.target){setM(v<s.target?'That setting is too low. Increase it and compare again.':'That setting is too high. Reduce it and compare again.');return}
    setDone(d=>[...d,stage]);
    if(stage===stages.length-1){setM('All systems online — mission launched!');onSolved()}
    else{setStage(x=>x+1);setV(0);setM('System online. New challenge loaded.')}
  };
  return <><div className="missionChecklist">{stages.map((x,i)=><div key={i+'-'+x.label} className={`${i===stage?'activeMissionStep ':''}${done.includes(i)?'doneMissionStep':''}`}><span>{done.includes(i)?'✅':icons[i]||'🔧'}</span><div><small>CONTROL {i+1}</small><b>{x.label}</b></div></div>)}</div><div className="missionConsole"><div className="missionProblem"><p>{s.question}</p><div className="missionAnswerControl"><button type="button" onClick={()=>setV(x=>Math.max(0,x-step))}>−</button><div><small>YOUR SETTING</small><b>{v}{suffix}</b><em>0–{max}{suffix} · step {step}</em></div><button type="button" onClick={()=>setV(x=>Math.min(max,x+step))}>+</button></div></div></div><button type="button" className="primary" onClick={check}>{stage===stages.length-1?'Launch mission':'Bring system online'}</button><p className="feedback">{m}</p></>
}
