import React,{useMemo,useState}from'react';
import'./conceptConnections.css';
import{MiniSudoku}from'./miniSudoku';

const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const gcd=(a,b)=>{a=Math.abs(Math.round(a));b=Math.abs(Math.round(b));while(b){const t=b;b=a%b;a=t}return a||1};
const amountToNumber=(raw,fallback=.5)=>{if(typeof raw==='number'&&Number.isFinite(raw))return clamp(raw,0,1);if(typeof raw==='string'){const s=raw.trim();if(s.endsWith('%')){const n=parseFloat(s);if(Number.isFinite(n))return clamp(n/100,0,1)}if(s.includes('/')){const[a,b]=s.split('/').map(Number);if(Number.isFinite(a)&&Number.isFinite(b)&&b!==0)return clamp(a/b,0,1)}const n=Number(s);if(Number.isFinite(n))return clamp(n,0,1)}return fallback};
const applyOp=(v,op)=>op==='mul2'?v*2:op==='add2'?v+2:op==='add1'?v+1:op==='sub1'?v-1:op==='sub2'?v-2:v;
const opLabel=op=>op==='mul2'?'×2':op==='add2'?'+2':op==='add1'?'+1':op==='sub1'?'−1':op==='sub2'?'−2':op;

function LabControl({label,title,onReset,children}){
  return <div className="liveLabControl"><div><small>{label}</small><b>{title}</b></div><div className="liveLabInputs">{children}</div>{onReset&&<button className="labReset" onClick={onReset}>↻ Reset</button>}</div>
}
function LabInsight({same=true,changed,constant}){
  return <div className="labInsight"><span className={same?'stable':'changed'}>{same?'✓ relationship preserved':'! relationship changed'}</span><p><b>Changed:</b> {changed}</p><p><b>Stayed the same:</b> {constant}</p></div>
}

function FractionLab({lesson}){
  const fallback=(lesson.targetSelected??2)/(lesson.totalParts||4),initial=amountToNumber(lesson.numericTarget??lesson.target,fallback),[num,setNum]=useState(Math.round(initial*8)),den=8,value=num/den,percent=Math.round(value*100),decimal=Number(value.toFixed(3));
  return <><LabControl label="MOVE ONE IDEA" title="Slide the amount and watch every representation move together." onReset={()=>setNum(Math.round(initial*8))}><input type="range" min="0" max="8" value={num} onChange={e=>setNum(+e.target.value)}/><strong>{num}/{den}</strong></LabControl><div className="connectionModules"><article><small>FRACTION</small><strong>{num}/{den}</strong><div className="miniBar">{Array.from({length:den},(_,i)=><i key={i} className={i<num?'on':''}/>)}</div><p>{num} of {den} equal parts</p></article><article><small>DECIMAL</small><strong>{decimal}</strong><div className="decimalMeter"><i style={{width:`${percent}%`}}/></div><p>The same amount on a 0–1 scale.</p></article><article><small>PICTURE</small><div className="pieVisual" style={{background:`conic-gradient(#6d5dfc 0 ${percent}%,#eef0f5 ${percent}% 100%)`}}><span/></div><p>The filled region changes with the number.</p></article><article><small>PERCENT</small><strong>{percent}%</strong><div className="hundredDots">{Array.from({length:20},(_,i)=><i key={i} className={i<Math.round(percent/5)?'on':''}/>)}</div><p>{percent} out of every 100.</p></article><article className="numberLineCard"><small>NUMBER LINE</small><div className="connectionNumberLine"><span>0</span><i style={{left:`${percent}%`}}/><span>1</span></div><p>All four representations land at the same location.</p></article></div><LabInsight changed="fraction, decimal, percent, picture and number-line position" constant="they all describe one identical amount"/></>
}

function PatternLab({lesson}){
  if(lesson?.id==='number-train'||lesson?.concept?.toLowerCase().includes('series'))return <GrowingPatternLab/>;
  const[repeats,setRepeats]=useState(3),[swap,setSwap]=useState(false),a=swap?'■':'●',b=swap?'●':'■',seq=Array.from({length:repeats*2},(_,i)=>i%2?a:b);
  return <><LabControl label="CHANGE THE PATTERN" title="Change the length or swap the symbols. Does the rule survive?" onReset={()=>{setRepeats(3);setSwap(false)}}><label>Repeats <input type="range" min="1" max="6" value={repeats} onChange={e=>setRepeats(+e.target.value)}/><strong>{repeats}</strong></label><button className="labPreset" onClick={()=>setSwap(v=>!v)}>⇄ Swap A / B</button></LabControl><div className="connectionModules patternLiveModules"><article className="wideConnectionCard"><small>VISUAL PATTERN</small><div className="patternStrip livePattern">{seq.map((x,i)=>i%2?<em key={i}>{x}</em>:<b key={i}>{x}</b>)}</div><p>{repeats} complete A-B repeats</p></article><article><small>POSITIONS</small><strong>odd → A<br/>even → B</strong><p>Position still predicts the symbol.</p></article><article><small>RULE</small><strong>A B</strong><p>The smallest repeat unit stays two parts long.</p></article><article><small>TOTAL ITEMS</small><strong>{seq.length}</strong><p>2 items × {repeats} repeats</p></article></div><LabInsight changed="how many repeats are visible and which symbol plays A or B" constant="the structure remains A-B-A-B"/></>
}

function CoordinateLab({lesson}){
  const initialX=lesson.targetX??3,initialY=lesson.targetY??2,[x,setX]=useState(initialX),[y,setY]=useState(initialY);
  return <><LabControl label="MOVE THE POINT" title="Change x and y. Watch the address and movement update." onReset={()=>{setX(initialX);setY(initialY)}}><label>x <input type="range" min="0" max="5" value={x} onChange={e=>setX(+e.target.value)}/><strong>{x}</strong></label><label>y <input type="range" min="0" max="5" value={y} onChange={e=>setY(+e.target.value)}/><strong>{y}</strong></label></LabControl><div className="connectionModules"><article><small>ADDRESS</small><strong>({x}, {y})</strong><p>x first, then y</p></article><article><small>GRID</small><div className="miniGrid liveCoordinateGrid"><i style={{left:`${x*20}%`,bottom:`${y*20}%`}}/></div><p>The point moves with the ordered pair.</p></article><article><small>MOVEMENT</small><strong>→ {x}<br/>↑ {y}</strong><p>Move across before moving up.</p></article><article><small>DISTANCE FROM ORIGIN</small><strong>{x+y} grid steps</strong><p>{x} horizontal + {y} vertical</p></article></div><LabInsight changed="the ordered pair, point location and movement counts" constant="x always means horizontal; y always means vertical"/></>
}

function BalanceLab({lesson}){
  const fixed=lesson.fixed??2,target=lesson.target??6,answer=target-fixed,[x,setX]=useState(answer),total=x+fixed,delta=total-target;
  return <><LabControl label="TEST THE UNKNOWN" title="Move the mystery amount and watch both sides of the equation." onReset={()=>setX(answer)}><button className="labStepper" onClick={()=>setX(v=>Math.max(0,v-1))}>−</button><strong>? = {x}</strong><button className="labStepper" onClick={()=>setX(v=>v+1)}>+</button></LabControl><div className="connectionModules"><article className={delta===0?'connectionCorrect':''}><small>SETUP</small><strong>{x} + {fixed} = {target}</strong><p>{delta===0?'Balanced!':'Left side = '+total}</p></article><article><small>UNDO</small><strong>{target} − {fixed} = {answer}</strong><p>Subtract the known amount from both sides.</p></article><article><small>CHECK</small><strong>{answer} + {fixed} = {target}</strong><p>Put the solution back into the original relationship.</p></article><article><small>BALANCE</small><div className="miniBalance"><span>{total}</span><i style={{transform:`rotate(${clamp(delta*4,-18,18)}deg)`}}/><span>{target}</span></div><p>{delta===0?'Both sides match.':delta<0?'Left side needs more.':'Left side has too much.'}</p></article></div><LabInsight same={delta===0} changed="the mystery amount and total on the left side" constant={`the right side stays ${target}; equality only holds when both totals match`}/></>
}

function RatioLab({lesson}){
  const a=lesson.ratioA||2,b=lesson.ratioB||1,[scale,setScale]=useState(1),[broken,setBroken]=useState(false),A=a*scale,B=b*scale+(broken?1:0),same=A*b===B*a;
  return <><LabControl label="SCALE THE RELATIONSHIP" title="Change the batch size. Then deliberately break one side." onReset={()=>{setScale(1);setBroken(false)}}><label>Batch size <input type="range" min="1" max="4" value={scale} onChange={e=>setScale(+e.target.value)}/><strong>{scale}×</strong></label><button className={broken?'labPreset danger':'labPreset'} onClick={()=>setBroken(v=>!v)}>{broken?'Repair ratio':'Break one side +1'}</button></LabControl><div className="connectionModules ratioLiveModules"><article className={same?'connectionCorrect':'connectionBroken'}><small>RATIO</small><strong>{A}:{B}</strong><p>{same?`Equivalent to ${a}:${b}`:'This no longer scales both parts equally.'}</p></article><article><small>PICTURE</small><div className="ratioDots ratioLiveDots">{Array.from({length:A},(_,i)=><b key={'a'+i}>●</b>)}{Array.from({length:B},(_,i)=><em key={'b'+i}>●</em>)}</div><p>{A} {lesson.aLabel||'A'} and {B} {lesson.bLabel||'B'}</p></article><article><small>TABLE</small><div className="ratioTable"><span>1×</span><b>{a}</b><b>{b}</b><span>{scale}×</span><b>{A}</b><b>{B}</b></div><p>Equivalent rows multiply both columns by the same factor.</p></article><article><small>BAR MODEL</small><div className="ratioBars"><i style={{width:`${Math.min(100,A/Math.max(A,B)*100)}%`}}/><em style={{width:`${Math.min(100,B/Math.max(A,B)*100)}%`}}/></div><p>The relative lengths reveal the relationship.</p></article></div><LabInsight same={same} changed="the size of the batch and total number of objects" constant={same?`the ${a}:${b} relationship`:'nothing proportional—the relationship was intentionally broken'}/></>
}

function FunctionLab({lesson}){
  const pairs=lesson.pairs||[],fromPairs=pairs.length>1;
  let mult=1,add=0,ops=[];
  if(fromPairs){mult=(pairs[1][1]-pairs[0][1])/(pairs[1][0]-pairs[0][0]);add=pairs[0][1]-mult*pairs[0][0]}
  else{ops=lesson.solution||[]}
  const initial=lesson.input??lesson.start??3,[input,setInput]=useState(initial);
  const output=fromPairs?mult*input+add:ops.reduce((v,op)=>applyOp(v,op),input);
  const rule=fromPairs?`${mult===1?'':mult+'×'}input ${add>0?'+ '+add:add<0?'− '+Math.abs(add):''}`.trim():(ops.map(opLabel).join(' → ')||'same value');
  const rows=Array.from({length:4},(_,i)=>{const x=i+1,y=fromPairs?mult*x+add:ops.reduce((v,op)=>applyOp(v,op),x);return[x,y]});
  return <><LabControl label="CHANGE THE INPUT" title="Move one input. The same rule must transform every value." onReset={()=>setInput(initial)}><button className="labStepper" onClick={()=>setInput(v=>Math.max(0,v-1))}>−</button><strong>input {input}</strong><button className="labStepper" onClick={()=>setInput(v=>Math.min(15,v+1))}>+</button></LabControl><div className="connectionModules functionLiveModules"><article><small>MACHINE</small><div className="functionPipe liveFunctionPipe"><b>{input}</b><span>{rule}</span><b>{output}</b></div><p>Only the input changed.</p></article><article><small>EQUATION / RULE</small><strong>{rule}</strong><p>The operation stays fixed.</p></article><article><small>TABLE</small><div className="functionTable">{rows.map(([x,y])=><span key={x}><b>{x}</b><i>→</i><b>{y}</b></span>)}</div><p>One rule generates every row.</p></article><article><small>CURRENT OUTPUT</small><strong>{output}</strong><p>Apply the rule to {input}.</p></article></div><LabInsight changed="the input, output, current table position" constant="the function rule"/></>
}

function ScaleLab({lesson}){
  const initial=lesson.target??2,[factor,setFactor]=useState(initial),baseW=2,baseH=3,w=Number((baseW*factor).toFixed(1)),h=Number((baseH*factor).toFixed(1)),area=Number((baseW*baseH*factor*factor).toFixed(2));
  return <><LabControl label="RESIZE EVERYTHING TOGETHER" title="Change the scale factor and watch lengths and area respond." onReset={()=>setFactor(initial)}><input type="range" min=".5" max="3" step=".5" value={factor} onChange={e=>setFactor(+e.target.value)}/><strong>{factor}× scale</strong></LabControl><div className="connectionModules scaleLiveModules"><article><small>MODEL</small><div className="scaleCompare"><i/><span>→</span><b style={{transform:`scale(${.55+.18*factor})`}}/></div><p>Same shape, new size.</p></article><article><small>LENGTHS</small><strong>{baseW} × {baseH}<br/>↓<br/>{w} × {h}</strong><p>Every length is multiplied by {factor}.</p></article><article><small>AREA</small><strong>6 → {area}</strong><p>Area changes by {Number((factor*factor).toFixed(2))}× because two dimensions scale.</p></article><article><small>RELATIONSHIP</small><strong>{factor}× length<br/>{Number((factor*factor).toFixed(2))}× area</strong><p>Scaling length and area are related, but not identical.</p></article></div><LabInsight changed="every dimension and the total area" constant="shape and proportions"/></>
}

function MapScaleLab({lesson}){
  const factor=lesson.factor??2,initial=lesson.mapUnits??4,[blocks,setBlocks]=useState(initial),distance=blocks*factor;
  return <><LabControl label="MOVE ACROSS THE MAP" title={`The key stays 1 block = ${factor} miles. Change the number of blocks.`} onReset={()=>setBlocks(initial)}><input type="range" min="1" max="8" value={blocks} onChange={e=>setBlocks(+e.target.value)}/><strong>{blocks} blocks</strong></LabControl><div className="connectionModules"><article><small>MAP</small><strong>{blocks} blocks</strong><div className="mapBlocks">{Array.from({length:blocks},(_,i)=><i key={i}/>)}</div><p>Count the model units.</p></article><article><small>SCALE KEY</small><strong>1 → {factor}</strong><p>Each map block always represents {factor} miles.</p></article><article><small>REAL DISTANCE</small><strong>{distance} miles</strong><p>{blocks} × {factor} = {distance}</p></article><article><small>TABLE</small><div className="mapScaleTable">{[1,2,blocks].map((n,i)=><span key={i}><b>{n}</b><i>→</i><b>{n*factor}</b></span>)}</div><p>The same multiplier works every time.</p></article></div><LabInsight changed="map blocks and total real distance" constant={`the ×${factor} scale factor`}/></>
}

function RateLab({lesson}){
  const baseRate=lesson.distance&&lesson.timeTarget?lesson.distance/lesson.timeTarget:2,initial=lesson.timeTarget??3,[time,setTime]=useState(initial),distance=Number((baseRate*time).toFixed(1));
  return <><LabControl label="KEEP THE PACE" title="Change the time. Distance changes so the rate stays constant." onReset={()=>setTime(initial)}><input type="range" min="1" max="8" value={time} onChange={e=>setTime(+e.target.value)}/><strong>{time} sec</strong></LabControl><div className="connectionModules"><article><small>TIME</small><strong>{time} sec</strong><p>The independent quantity you changed.</p></article><article><small>DISTANCE</small><strong>{distance} spaces</strong><div className="rateTrack"><span style={{left:`${Math.min(92,8+distance*5)}%`}}>🏎️</span></div><p>Distance grows with time.</p></article><article className="connectionCorrect"><small>RATE</small><strong>{baseRate} / sec</strong><p>{distance} ÷ {time} = {baseRate}</p></article><article><small>TABLE</small><div className="rateTable">{[1,2,time].map((t,i)=><span key={i}><b>{t}s</b><i>→</i><b>{Number((t*baseRate).toFixed(1))}</b></span>)}</div><p>Each second adds the same distance.</p></article></div><LabInsight changed="time and total distance" constant={`the rate of ${baseRate} spaces per second`}/></>
}

function UnitRateLab({lesson}){
  const deals=lesson.deals||[{label:'4 for 8',unit:2},{label:'3 for 9',unit:3}],[qty,setQty]=useState(1),a=deals[0],b=deals[1],costA=Number((a.unit*qty).toFixed(2)),costB=Number((b.unit*qty).toFixed(2));
  return <><LabControl label="COMPARE THE SAME QUANTITY" title="Change how many items you buy. Unit price predicts every total." onReset={()=>setQty(1)}><input type="range" min="1" max="10" value={qty} onChange={e=>setQty(+e.target.value)}/><strong>{qty} items</strong></LabControl><div className="connectionModules dealLiveModules"><article className={a.unit<b.unit?'connectionCorrect':''}><small>DEAL A</small><strong>{costA} coins</strong><p>{qty} × {a.unit} each</p></article><article className={b.unit<a.unit?'connectionCorrect':''}><small>DEAL B</small><strong>{costB} coins</strong><p>{qty} × {b.unit} each</p></article><article><small>PER ONE</small><strong>{a.unit} vs {b.unit}</strong><p>Compare one item before comparing totals.</p></article><article><small>SAVINGS</small><strong>{Math.abs(costA-costB).toFixed(2)}</strong><p>Difference for {qty} items.</p></article></div><LabInsight changed="package total and total savings" constant="each deal's cost per one item"/></>
}

function SlopeLab({lesson}){
  const baseRise=lesson.riseTarget??2,baseRun=lesson.runTarget??4,[rise,setRise]=useState(baseRise),[run,setRun]=useState(baseRun),g=gcd(rise,run),simpleRise=rise/g,simpleRun=run/g,baseRatio=baseRise/baseRun,currentRatio=rise/run,sameSlope=Math.abs(baseRatio-currentRatio)<.0001,y=Math.min(92,Math.max(12,currentRatio*82)),endY=112-y;
  return <><LabControl label="CHANGE THE TRIANGLE" title="Move rise and run. Watch steepness change." onReset={()=>{setRise(baseRise);setRun(baseRun)}}><label>Rise <input type="range" min="1" max="8" value={rise} onChange={e=>setRise(+e.target.value)}/><strong>{rise}</strong></label><label>Run <input type="range" min="1" max="8" value={run} onChange={e=>setRun(+e.target.value)}/><strong>{run}</strong></label></LabControl><div className="connectionModules slopeConnectionModules"><article><small>RISE / RUN</small><strong>{rise} / {run}</strong><p>Go up {rise}, then across {run}.</p></article><article className={sameSlope?'connectionCorrect':''}><small>{sameSlope?'SAME STEEPNESS':'SIMPLIFIED SLOPE'}</small><strong>{simpleRise} / {simpleRun}</strong><p>{sameSlope?`${rise}/${run} matches the original steepness.`:'Reduce the ratio to compare steepness.'}</p></article><article className="slopeVisualCard"><small>WATCH THE SLOPE</small><svg className="slopeInteractiveSvg" viewBox="0 0 220 140" role="img" aria-label={`Slope with rise ${rise} and run ${run}`}><line x1="28" y1="116" x2="198" y2="116" className="slopeAxis"/><line x1="28" y1="116" x2="28" y2="14" className="slopeAxis"/><line x1="42" y1="112" x2="188" y2={endY} className="slopeMainLine"/><line x1="42" y1="112" x2="188" y2="112" className="slopeRunGuide"/><line x1="188" y1="112" x2="188" y2={endY} className="slopeRiseGuide"/><text x="105" y="132">run {run}</text><text x="192" y={(112+endY)/2}>rise {rise}</text></svg><p>More rise = steeper. More run = flatter.</p></article></div><LabInsight same={sameSlope} changed="rise, run and the line's steepness" constant={sameSlope?'the original rise/run relationship':'only equivalent rise/run pairs preserve the same steepness'}/></>
}


function ProbabilityLab({lesson,mechanic}){
  const initialA=lesson.targetRed??lesson.targetA??Math.round((lesson.target??.5)*(lesson.segments||10));
  const initialB=lesson.targetBlue??((lesson.segments||10)-initialA);
  const totalBase=lesson.segments||initialA+initialB||10;
  const[a,setA]=useState(initialA),[trials,setTrials]=useState(10);
  const total=mechanic==='trials'?trials:totalBase,prob=mechanic==='trials'?50:Math.round(a/Math.max(1,total)*100);
  const observed=lesson.observed??prob,expected=mechanic==='trials'?50:prob;
  return <><LabControl label="CHANGE THE CHANCE" title={mechanic==='trials'?'Change sample size and compare observed vs expected.':'Change favorable outcomes and watch probability move.'} onReset={()=>{setA(initialA);setTrials(10)}}>
    {mechanic==='trials'?<label>Trials <input type="range" min="2" max="40" step="2" value={trials} onChange={e=>setTrials(+e.target.value)}/><strong>{trials}</strong></label>:<label>Favorable <input type="range" min="0" max={totalBase} value={a} onChange={e=>setA(+e.target.value)}/><strong>{a}/{totalBase}</strong></label>}
  </LabControl><div className="connectionModules"><article><small>FAVORABLE / TOTAL</small><strong>{mechanic==='trials'?Math.round(trials*.5):a} / {total}</strong><p>Probability compares favorable outcomes with all equally likely outcomes.</p></article><article><small>PERCENT</small><strong>{expected}%</strong><div className="decimalMeter"><i style={{width:expected+'%'}}/></div><p>{expected} out of every 100 in the long run.</p></article><article><small>VISUAL</small><div className="chanceDots">{Array.from({length:Math.min(20,total)},(_,i)=><i key={i} className={i<Math.round(expected/5)?'on':''}/>)}</div><p>More favorable space means greater chance.</p></article><article><small>{mechanic==='trials'?'OBSERVED RUN':'COMPLEMENT'}</small><strong>{mechanic==='trials'?observed+'%':100-prob+'%'}</strong><p>{mechanic==='trials'?'A short run can differ from expectation.':'Everything not favorable belongs to the complement.'}</p></article></div><LabInsight changed="the favorable outcomes or sample size" constant={mechanic==='trials'?'the fair long-run expectation':'probability is favorable ÷ total'}/></>
}

function GrowingPatternLab(){
  const[step,setStep]=useState(4),[add,setAdd]=useState(3),value=2+(step-1)*add;
  return <><LabControl label="GROW THE PATTERN" title="Change the step number and growth amount. Watch one rule generate the sequence." onReset={()=>{setStep(4);setAdd(3)}}><label>Step <input type="range" min="1" max="8" value={step} onChange={e=>setStep(+e.target.value)}/><strong>{step}</strong></label><label>Grow by <input type="range" min="1" max="5" value={add} onChange={e=>setAdd(+e.target.value)}/><strong>+{add}</strong></label></LabControl><div className="connectionModules"><article><small>SEQUENCE</small><strong>{Array.from({length:step},(_,i)=>2+i*add).join(', ')}</strong><p>Each term adds the same amount.</p></article><article><small>VISUAL GROWTH</small><div className="growthBars">{Array.from({length:step},(_,i)=><i key={i} style={{height:(18+(i+1)*add*7)+'px'}}/>)}</div><p>Later steps grow predictably.</p></article><article><small>RULE</small><strong>2 + (step − 1) × {add}</strong><p>The step number tells how many growth moves occurred.</p></article><article><small>CURRENT</small><strong>{value}</strong><p>Step {step} has value {value}.</p></article></div><LabInsight changed="step number, visible size, and current value" constant={'the repeated +'+add+' growth rule'}/></>
}

function LogicLab({lesson,mechanic}){
  const[a,setA]=useState(true),[b,setB]=useState(true),[rule,setRule]=useState(lesson.rule||'AND');
  const[color,setColor]=useState('blue'),[shape,setShape]=useState('corners'),[size,setSize]=useState('large');
  const target=lesson.target||{color:'blue',shape:'corners',size:'large'},constraintOk=color===target.color&&shape===target.shape&&size===target.size;
  if(mechanic==='constraint')return <><LabControl label="SATISFY ALL RULES" title="Change one property at a time; all constraints must be true together." onReset={()=>{setColor('blue');setShape('corners');setSize('large')}}><button className="labPreset" onClick={()=>setColor(color==='blue'?'red':'blue')}>Color: {color}</button><button className="labPreset" onClick={()=>setShape(shape==='corners'?'round':'corners')}>Shape: {shape}</button><button className="labPreset" onClick={()=>setSize(size==='large'?'small':'large')}>Size: {size}</button></LabControl><div className="connectionModules"><article className={constraintOk?'connectionCorrect':'connectionBroken'}><small>OBJECT</small><div className={'constraintObject '+color+' '+shape+' '+size}/><p>{color} · {shape} · {size}</p></article><article><small>RULE 1</small><strong>{target.color}</strong><p>{color===target.color?'✓':'✗'} color</p></article><article><small>RULE 2</small><strong>{target.shape}</strong><p>{shape===target.shape?'✓':'✗'} shape</p></article><article><small>RULE 3</small><strong>{target.size}</strong><p>{size===target.size?'✓':'✗'} size</p></article></div><LabInsight same={constraintOk} changed="object properties" constant="all three rules must be satisfied together"/></>;
  const output=rule==='AND'?a&&b:a||b;
  return <><LabControl label="FLIP THE SWITCHES" title="Predict the output before testing the circuit." onReset={()=>{setA(true);setB(true);setRule(lesson.rule||'AND')}}><button className={a?'labPreset active':'labPreset'} onClick={()=>setA(v=>!v)}>A {a?'ON':'OFF'}</button><button className={b?'labPreset active':'labPreset'} onClick={()=>setB(v=>!v)}>B {b?'ON':'OFF'}</button><button className="labPreset" onClick={()=>setRule(r=>r==='AND'?'OR':'AND')}>{rule}</button></LabControl><div className="connectionModules"><article><small>INPUTS</small><strong>{a?'1':'0'} {rule} {b?'1':'0'}</strong><p>Each switch is a true/false condition.</p></article><article className={output?'connectionCorrect':''}><small>LIGHT</small><div className={'logicLamp '+(output?'on':'')}>💡</div><p>{output?'ON':'OFF'}</p></article><article><small>AND</small><strong>both true</strong><p>AND needs A and B.</p></article><article><small>OR</small><strong>at least one</strong><p>OR needs A or B or both.</p></article></div><LabInsight changed="switch states and output" constant={'the '+rule+' rule'}/></>
}

function VectorLab({lesson}){
  const initialX=lesson.targetX??4,initialY=lesson.targetY??3,[x,setX]=useState(initialX),[y,setY]=useState(initialY);
  const mag=Math.sqrt(x*x+y*y).toFixed(1);
  return <><LabControl label="COMBINE TWO PUSHES" title="Change horizontal and vertical components. The diagonal updates immediately." onReset={()=>{setX(initialX);setY(initialY)}}><label>Across <input type="range" min="-5" max="6" value={x} onChange={e=>setX(+e.target.value)}/><strong>{x}</strong></label><label>Up <input type="range" min="-5" max="6" value={y} onChange={e=>setY(+e.target.value)}/><strong>{y}</strong></label></LabControl><div className="connectionModules"><article><small>COMPONENTS</small><strong>({x}, {y})</strong><p>Horizontal and vertical stay independent.</p></article><article className="vectorCard"><small>RESULTANT</small><svg viewBox="0 0 160 130"><line x1="30" y1="100" x2={30+x*15} y2="100"/><line x1={30+x*15} y1="100" x2={30+x*15} y2={100-y*15}/><line className="resultant" x1="30" y1="100" x2={30+x*15} y2={100-y*15}/></svg><p>One diagonal motion combines both pushes.</p></article><article><small>MAGNITUDE</small><strong>{mag}</strong><p>Total displacement length.</p></article><article><small>ADDRESS</small><strong>({x}, {y})</strong><p>From the origin, the vector lands here.</p></article></div><LabInsight changed="horizontal push, vertical push, endpoint, magnitude" constant="components combine into one resultant"/></>
}

function MotionLab({lesson,mechanic}){
  if(mechanic==='momentum'){
    const[mass,setMass]=useState(3),[speed,setSpeed]=useState(4),p=mass*speed;
    return <><LabControl label="MASS × SPEED" title="Find different pairs that create the same motion score." onReset={()=>{setMass(3);setSpeed(4)}}><label>Mass <input type="range" min="1" max={lesson.maxMass||8} value={mass} onChange={e=>setMass(+e.target.value)}/><strong>{mass}</strong></label><label>Speed <input type="range" min="1" max={lesson.maxSpeed||8} value={speed} onChange={e=>setSpeed(+e.target.value)}/><strong>{speed}</strong></label></LabControl><div className="connectionModules"><article><small>MOMENTUM MODEL</small><strong>{mass} × {speed} = {p}</strong><p>Both quantities matter.</p></article><article><small>VISUAL</small><div className="momentumLane"><span style={{width:(40+mass*10)+'px',left:(8+speed*7)+'%'}}>🛒</span></div><p>Heavier or faster means more motion.</p></article><article className={p===lesson.target?'connectionCorrect':''}><small>TARGET</small><strong>{lesson.target}</strong><p>{p===lesson.target?'Matched!':'Current: '+p}</p></article><article><small>RULE</small><strong>mass × speed</strong><p>Different pairs can make the same product.</p></article></div><LabInsight same={p===lesson.target} changed="mass, speed, and product" constant="momentum depends on mass × speed"/></>
  }
  if(mechanic==='torque'){
    const[w,setW]=useState(3),[d,setD]=useState(4),right=(lesson.rightWeight||3)*(lesson.rightDistance||4),left=w*d,delta=left-right;
    return <><LabControl label="BALANCE THE LEVER" title="Change weight and distance. Equal turning effect balances the bridge." onReset={()=>{setW(3);setD(4)}}><label>Weight <input type="range" min="1" max={lesson.maxWeight||10} value={w} onChange={e=>setW(+e.target.value)}/><strong>{w}</strong></label><label>Distance <input type="range" min="1" max={lesson.maxDistance||10} value={d} onChange={e=>setD(+e.target.value)}/><strong>{d}</strong></label></LabControl><div className="connectionModules"><article><small>LEFT TORQUE</small><strong>{w} × {d} = {left}</strong></article><article><small>RIGHT TORQUE</small><strong>{right}</strong><p>{lesson.rightWeight||3} × {lesson.rightDistance||4}</p></article><article className={delta===0?'connectionCorrect':''}><small>BRIDGE</small><div className="torqueBeam" style={{transform:'rotate('+clamp(delta*1.5,-16,16)+'deg)'}}><i/></div><p>{delta===0?'Balanced':'Unequal torque tilts the beam'}</p></article><article><small>RULE</small><strong>weight × distance</strong><p>Small force farther away can match a larger close force.</p></article></div><LabInsight same={delta===0} changed="weight, distance and turning effect" constant="balance requires equal torque"/></>
  }
  if(mechanic==='energy'){
    const[h,setH]=useState(lesson.targetSpeed??8),speed=Math.round(h*.9+1);
    return <><LabControl label="RAISE THE HILL" title="Starting height changes stored energy and bottom speed." onReset={()=>setH(lesson.targetSpeed??8)}><input type="range" min="1" max={lesson.maxHeight||10} value={h} onChange={e=>setH(+e.target.value)}/><strong>height {h}</strong></LabControl><div className="connectionModules"><article><small>HEIGHT</small><strong>{h}</strong><div className="energyHill" style={{height:(35+h*9)+'px'}}>🎢</div></article><article><small>STORED ENERGY</small><strong>{h*10}</strong><p>Higher position stores more gravitational potential.</p></article><article><small>BOTTOM SPEED</small><strong>{speed}</strong><p>Stored energy converts into motion.</p></article><article><small>CONVERSION</small><strong>height → speed</strong><p>Energy changes form.</p></article></div><LabInsight changed="height, stored energy and bottom speed" constant="more starting height provides more energy for motion"/></>
  }
  if(mechanic==='gravity'){
    const[g,setG]=useState(6),power=lesson.power||10,distance=Number((power*5/(g+2)).toFixed(1));
    return <><LabControl label="CHANGE GRAVITY" title="Keep launch power fixed. Change only gravity." onReset={()=>setG(6)}><input type="range" min="1" max="10" value={g} onChange={e=>setG(+e.target.value)}/><strong>gravity {g}</strong></LabControl><div className="connectionModules"><article><small>POWER</small><strong>{power}</strong><p>Held constant.</p></article><article><small>GRAVITY</small><strong>{g}</strong><p>You changed the downward pull.</p></article><article><small>DISTANCE</small><strong>{distance}</strong><div className="gravityArc"><i style={{width:Math.min(100,distance*8)+'%'}}/></div></article><article><small>RELATIONSHIP</small><strong>more gravity → shorter flight</strong><p>Less gravity keeps the launch aloft longer.</p></article></div><LabInsight changed="gravity and flight distance" constant={'launch power stays '+power}/></>
  }
  if(mechanic==='orbit'){
    const target=lesson.targetSpeed??5,[s,setS]=useState(target),state=s<target?'falls inward':s>target?'escapes outward':'stable orbit';
    return <><LabControl label="TUNE SIDEWAYS SPEED" title="Too slow falls inward; too fast escapes; the middle zone orbits." onReset={()=>setS(target)}><input type="range" min={lesson.min||1} max={lesson.max||9} value={s} onChange={e=>setS(+e.target.value)}/><strong>speed {s}</strong></LabControl><div className="connectionModules"><article className={s===target?'connectionCorrect':''}><small>ORBIT STATE</small><strong>{state}</strong><div className={'orbitViz '+(s===target?'stable':s<target?'inward':'outward')}><span>🪐</span><i>🛰️</i></div></article><article><small>TOO SLOW</small><strong>gravity wins</strong><p>The path bends inward.</p></article><article><small>TOO FAST</small><strong>speed wins</strong><p>The path opens outward.</p></article><article><small>STABLE</small><strong>{target}</strong><p>Sideways motion and gravity balance.</p></article></div><LabInsight same={s===target} changed="sideways speed and path shape" constant="gravity keeps pulling toward the planet"/></>
  }
  return null;
}

function GraphChangeLab({lesson}){
  const initial=lesson.targetRate??3,[rate,setRate]=useState(initial),steps=lesson.steps||4,end=rate*steps;
  return <><LabControl label="CHANGE THE RATE" title="Adjust the constant change. Watch the line and table update together." onReset={()=>setRate(initial)}><input type="range" min="0" max="6" value={rate} onChange={e=>setRate(+e.target.value)}/><strong>+{rate} / step</strong></LabControl><div className="connectionModules"><article><small>RULE</small><strong>y = {rate} × step</strong><p>Add {rate} each step.</p></article><article><small>END VALUE</small><strong>{end}</strong><p>{steps} steps × {rate}</p></article><article className="graphLiveCard"><small>GRAPH</small><svg viewBox="0 0 180 120"><line x1="24" y1="98" x2="165" y2="98"/><line x1="24" y1="98" x2="24" y2="15"/><line className="graphRateLine" x1="24" y1="98" x2="160" y2={98-clamp(end*4,0,78)}/></svg><p>Higher rate = steeper line.</p></article><article><small>TABLE</small><strong>{Array.from({length:steps+1},(_,i)=>i+':'+i*rate).join(' · ')}</strong><p>Every row follows the same rate.</p></article></div><LabInsight changed="rate, end value, table and graph steepness" constant="constant-rate relationships form straight lines"/></>
}

function AreaSlicesLab({lesson}){
  const initial=lesson.targetSlices??12,[slices,setSlices]=useState(initial),error=(18/slices).toFixed(2);
  return <><LabControl label="REFINE THE SLICES" title="Add thinner slices. Watch the approximation hug the curve more closely." onReset={()=>setSlices(initial)}><input type="range" min="2" max={lesson.maxSlices||18} value={slices} onChange={e=>setSlices(+e.target.value)}/><strong>{slices} slices</strong></LabControl><div className="connectionModules"><article className="areaCurveCard"><small>CURVED REGION</small><div className="sliceCurve">{Array.from({length:slices},(_,i)=><i key={i} style={{height:(20+Math.sin((i+1)/(slices+1)*Math.PI)*70)+'px',width:(100/slices)+'%'}}/>)}</div><p>Thin rectangles accumulate under the curve.</p></article><article><small>SLICE WIDTH</small><strong>{(1/slices).toFixed(3)}</strong><p>More slices means thinner pieces.</p></article><article><small>ROUGH ERROR</small><strong>{error}</strong><p>The visual gap shrinks as slices increase.</p></article><article><small>CORE IDEA</small><strong>sum many small areas</strong><p>This is the intuition behind integration.</p></article></div><LabInsight changed="slice count, slice width and approximation error" constant="the curved region being approximated"/></>
}

function GenericLab({lesson}){return <div className="connectionModules"><article><small>CONCEPT</small><strong>{lesson.concept}</strong><p>{lesson.intro}</p></article><article><small>STRUCTURE</small><strong>What changes?</strong><p>Try the discovery challenge, then compare another example.</p></article><article><small>TRANSFER</small><strong>What stays the same?</strong><p>Look for the relationship underneath the surface objects.</p></article></div>}

const sportTransferByMechanic={
  slope:{icon:'⚾🏀',title:'Angles in Athletics Park',text:'Baseball launch angle and basketball release angle use the same idea: a direction measured from a reference line changes the path.'},
  race:{icon:'🏃⚾',title:'Rates in Athletics Park',text:'Track pace and baseball base running use distance = rate × time. Change speed and both the animation and time respond.'},
  ratio:{icon:'⚾',title:'Ratios in the dugout',text:'Hits ÷ at-bats can be represented as a fraction, decimal, or percent—just like equivalent ratio representations here.'},
  deal:{icon:'🏃',title:'Per-one thinking in Track',text:'Pace is another “per one” relationship: seconds per lap or distance per second.'},
  coordinate:{icon:'⚽🏈',title:'Targets on a field',text:'Soccer and football use location plus direction to predict where a ball should go.'},
  scale:{icon:'⚾',title:'Scale on the baseball diamond',text:'The diamond keeps the same shape while dimensions change, just like any scaled model.'},
  'scale-map':{icon:'🏟️',title:'Field maps use scale',text:'A sports field diagram is a scaled representation of real distances.'},
  balance:{icon:'⛳',title:'Balancing effects',text:'Golf combines angle, force, and wind. One change can be balanced by another to reach the same target.'}
};
function SportsTransfer({mechanic}){
  const item=sportTransferByMechanic[mechanic];
  if(!item)return null;
  return <div className="sportsTransferCard"><span>{item.icon}</span><div><small>SAME IDEA · NEW SURFACE</small><b>{item.title}</b><p>{item.text}</p><em>Try it in My World → Athletics Park.</em></div></div>;
}

export function ConceptConnections({lesson}){
  const mechanic=lesson.expandedMechanic||lesson.mechanic;
  let content;
  if(['select-parts','match-set','pour','equivalence-wheel'].includes(mechanic))content=<FractionLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='pattern-choice')content=<PatternLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='coordinate')content=<CoordinateLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='balance')content=<BalanceLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='ratio')content=<RatioLab key={lesson.id} lesson={lesson}/>;
  else if(['machine','rule-blocks'].includes(mechanic))content=<FunctionLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='scale')content=<ScaleLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='scale-map')content=<MapScaleLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='race')content=<RateLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='deal')content=<UnitRateLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='slope')content=<SlopeLab key={lesson.id} lesson={lesson}/>;
  else if(['probability-bag','fair-spinner','trials'].includes(mechanic))content=<ProbabilityLab key={lesson.id} lesson={lesson} mechanic={mechanic}/>;
  else if(['logic-switch','constraint'].includes(mechanic))content=<LogicLab key={lesson.id} lesson={lesson} mechanic={mechanic}/>;
  else if(mechanic==='vector')content=<VectorLab key={lesson.id} lesson={lesson}/>;
  else if(['momentum','torque','energy','gravity','orbit'].includes(mechanic))content=<MotionLab key={lesson.id} lesson={lesson} mechanic={mechanic}/>;
  else if(mechanic==='graph-change')content=<GraphChangeLab key={lesson.id} lesson={lesson}/>;
  else if(mechanic==='area-slices')content=<AreaSlicesLab key={lesson.id} lesson={lesson}/>;
  else content=<GenericLab lesson={lesson}/>;
  return <><section className="panel connectionsLab"><div className="connectionsHeading"><div><small>TOUCH IT · CHANGE IT · CONNECT IT</small><h2>Connections Lab</h2><p>Change one thing and watch the picture, number, rule, and real situation respond together.</p></div><span>🧠</span></div>{content}<SportsTransfer mechanic={mechanic}/></section><MiniSudoku/></>
}
