import React,{useEffect,useMemo,useState}from'react';
import'./conceptArcade.css';

const clamp=(n,min,max)=>Math.max(min,Math.min(max,n));
const parseFraction=raw=>{if(typeof raw==='number'&&Number.isFinite(raw))return{value:raw,num:null,den:null};if(typeof raw==='string'&&raw.includes('/')){const[a,b]=raw.split('/').map(Number);if(Number.isFinite(a)&&Number.isFinite(b)&&b)return{value:a/b,num:a,den:b}}const n=Number(raw);return{value:Number.isFinite(n)?n:.5,num:null,den:null}};
function Frame({title,instruction,children,won,onReset}){return <section className="panel conceptArcade"><div className="arcadeHead"><div><small>CONCEPT ARCADE · PLAY THE IDEA</small><h2>{title}</h2><p>{instruction}</p></div><div className="arcadeStars">{won?'⭐':'🎮'}</div></div>{children}{won&&<div className="arcadeWin"><b>Level cleared! You made the concept work.</b><button onClick={onReset}>Play again</button></div>}</section>}

function FractionArcade({lesson}){const parsed=parseFraction(lesson.target??lesson.numericTarget),den=clamp(parsed.den||lesson.totalParts||8,2,10),target=clamp(parsed.num??Math.round((lesson.numericTarget??parsed.value??.5)*den),1,den-1),[filled,setFilled]=useState(0),[won,setWon]=useState(false),[message,setMessage]=useState('Pump fuel into the rocket.');useEffect(()=>{if(filled===target){setWon(true);setMessage('Perfect fuel level — liftoff!')}else if(filled<target)setMessage(`${target-filled} more fuel cell${target-filled===1?'':'s'} to go.`);else setMessage('Too much fuel. Drain a cell.')},[filled,target]);const reset=()=>{setFilled(0);setWon(false);setMessage('Pump fuel into the rocket.')};return <Frame title="Rocket Fuel" instruction={`Fuel exactly ${target}/${den} of the tank and launch automatically.`} won={won} onReset={reset}><div className={won?'fractionRocket launched':'fractionRocket'}><div className="rocketBody">🚀</div><div className="rocketTank">{Array.from({length:den},(_,i)=><i key={i} className={i<filled?'on':''}/>)}</div><div className="rocketFlame">{won?'🔥🔥':'🔥'}</div></div><div className="arcadeFuelControls"><button onClick={()=>setFilled(v=>clamp(v-1,0,den))}>Drain −</button><b>{filled}/{den} full</b><button className="pumpButton" onClick={()=>setFilled(v=>clamp(v+1,0,den))}>Pump +</button></div><p className="arcadeGameFeedback">{message}</p></Frame>}

function RatioArcade({lesson}){const a=lesson.ratioA??lesson.riseTarget??2,b=lesson.ratioB??lesson.runTarget??4,targetA=a*2,targetB=b*2,[x,setX]=useState(0),[y,setY]=useState(0),[won,setWon]=useState(false),[message,setMessage]=useState(`Mix ${targetA} blue and ${targetB} gold ingredients.`);useEffect(()=>{if(x===targetA&&y===targetB){setWon(true);setMessage('Recipe locked — the mixer is spinning!')}else if(x>targetA||y>targetB)setMessage('Too much of an ingredient. Tap a piece in the mixer to remove it.');else{const ratio=x>0&&y>0?(x/y).toFixed(2):'—',goal=(targetA/targetB).toFixed(2);setMessage(`Current mix ratio: ${ratio}. Goal ratio: ${goal}.`)}},[x,y,targetA,targetB]);const reset=()=>{setX(0);setY(0);setWon(false);setMessage(`Mix ${targetA} blue and ${targetB} gold ingredients.`)};return <Frame title="Ratio Mixer" instruction={`Fill the blender with a larger ${a} : ${b} recipe. No Check button — the machine reacts when the relationship is right.`} won={won} onReset={reset}><div className={won?'ratioMixer mixing':'ratioMixer'}><div className="mixerJar"><div className="mixerTokens">{Array.from({length:x},(_,i)=><button key={'x'+i} className="blueToken" onClick={()=>setX(v=>Math.max(0,v-1))}>●</button>)}{Array.from({length:y},(_,i)=><button key={'y'+i} className="goldToken" onClick={()=>setY(v=>Math.max(0,v-1))}>◆</button>)}</div><div className="mixerBlade">✦</div></div><div className="mixerBase"><b>{x}:{y}</b></div></div><div className="ingredientButtons"><button onClick={()=>setX(v=>clamp(v+1,0,12))}>🔵 Add blue</button><button onClick={()=>setY(v=>clamp(v+1,0,12))}>🟡 Add gold</button></div><div className="recipeGoal"><span>ORDER</span><b>{targetA} blue : {targetB} gold</b></div><p className="arcadeGameFeedback">{message}</p></Frame>}

function MachineArcade({lesson}){const pairs=lesson.pairs||[[1,3],[2,5]],a=pairs.length>1?(pairs[1][1]-pairs[0][1])/(pairs[1][0]-pairs[0][0]):2,b=pairs.length?pairs[0][1]-a*pairs[0][0]:1,input=(lesson.input??4)+1,target=Math.round(a*input+b),[v,setV]=useState(0),[won,setWon]=useState(false);const reset=()=>{setV(0);setWon(false)};return <Frame title="Beat the mystery machine" instruction={`The same rule is working. What comes out when ${input} goes in?`} won={won} onReset={reset}><div className="arcadeMachine"><div><small>IN</small><b>{input}</b></div><span>→</span><div className="gear">⚙️</div><span>→</span><div><small>OUT</small><b>{v}</b></div></div><div className="arcadeControls"><button onClick={()=>setV(n=>clamp(n-1,0,40))}>−</button><b>{v}</b><button onClick={()=>setV(n=>clamp(n+1,0,40))}>+</button><button className="arcadeCheck" onClick={()=>setWon(v===target)}>Run</button></div></Frame>}

function BalanceArcade({lesson}){const target=(lesson.target??10)-(lesson.fixed??2),[v,setV]=useState(0),[won,setWon]=useState(false);const reset=()=>{setV(0);setWon(false)};return <Frame title="Balance it fast" instruction={`Mystery + ${lesson.fixed??2} must equal ${lesson.target??10}. Find the mystery amount.`} won={won} onReset={reset}><div className="arcadeBalance"><div>❓ <b>{v}</b> + <b>{lesson.fixed??2}</b></div><span>=</span><div className="targetPan"><b>{lesson.target??10}</b></div></div><div className="arcadeControls"><button onClick={()=>setV(n=>clamp(n-1,0,30))}>−</button><b>{v}</b><button onClick={()=>setV(n=>clamp(n+1,0,30))}>+</button><button className="arcadeCheck" onClick={()=>setWon(v===target)}>Balance</button></div></Frame>}

function CoordinateArcade({lesson}){const tx=clamp(lesson.targetX??3,0,4),ty=clamp(lesson.targetY??2,0,4),[picked,setPicked]=useState(null),[won,setWon]=useState(false);const reset=()=>{setPicked(null);setWon(false)};return <Frame title="Tap the coordinate" instruction={`Find (${tx}, ${ty}) on the grid.`} won={won} onReset={reset}><div className="arcadeGrid">{Array.from({length:25},(_,i)=>{const x=i%5,y=4-Math.floor(i/5),active=picked===i;return <button key={i} className={active?'picked':''} onClick={()=>{setPicked(i);setWon(x===tx&&y===ty)}}><small>{x},{y}</small>{x===tx&&y===ty&&won?'🚀':''}</button>})}</div></Frame>}

function LineArcade({lesson}){const min=lesson.min??-5,max=lesson.max??5,target=lesson.target??0,[v,setV]=useState(0),[won,setWon]=useState(false);const reset=()=>{setV(0);setWon(false)};return <Frame title="Land on the target" instruction={`Slide to ${target}, then launch.`} won={won} onReset={reset}><div className="arcadeLine"><span>{min}</span><input type="range" min={min} max={max} value={v} onChange={e=>setV(+e.target.value)}/><span>{max}</span></div><b className="arcadeReadout">Aim: {v}</b><button className="arcadeCheck full" onClick={()=>setWon(v===target)}>Launch</button></Frame>}

function PatternArcade({lesson}){const seq=lesson.sequence||lesson.grid?.slice(0,3)||['A','B','A'],choices=lesson.choices||['A','B','C'],correct=lesson.correctIndex??0,[picked,setPicked]=useState(null),[won,setWon]=useState(false);const reset=()=>{setPicked(null);setWon(false)};return <Frame title="Spot the rule" instruction="Find the piece that keeps the pattern working." won={won} onReset={reset}><div className="arcadeSequence">{seq.map((x,i)=><span key={i}>{x}</span>)}<span>?</span></div><div className="arcadeChoices">{choices.map((x,i)=><button key={i} className={picked===i?'picked':''} onClick={()=>{setPicked(i);setWon(i===correct)}}>{x}</button>)}</div></Frame>}

function ProbabilityBagArcade({lesson}){const tr=lesson.targetRed??3,tb=lesson.targetBlue??1,[r,setR]=useState(1),[b,setB]=useState(1),[won,setWon]=useState(false);const reset=()=>{setR(1);setB(1);setWon(false)};return <Frame title="Build the chance" instruction={`Make a bag with ${tr} red and ${tb} blue.`} won={won} onReset={reset}><div className="arcadeBag">{'🔴'.repeat(r)}{'🔵'.repeat(b)}</div><div className="arcadeDualControls"><div><b>Red {r}</b><button onClick={()=>setR(v=>clamp(v-1,0,8))}>−</button><button onClick={()=>setR(v=>clamp(v+1,0,8))}>+</button></div><div><b>Blue {b}</b><button onClick={()=>setB(v=>clamp(v-1,0,8))}>−</button><button onClick={()=>setB(v=>clamp(v+1,0,8))}>+</button></div></div><button className="arcadeCheck full" onClick={()=>setWon(r===tr&&b===tb)}>Test chance</button></Frame>}

function SpinnerArcade({lesson}){const n=lesson.segments??8,target=lesson.targetA??Math.floor(n/2),[a,setA]=useState(0),[won,setWon]=useState(false);const reset=()=>{setA(0);setWon(false)};return <Frame title="Make it fair" instruction={`Color exactly half of the ${n} sections purple.`} won={won} onReset={reset}><div className="arcadeSpinner">{Array.from({length:n},(_,i)=><button key={i} className={i<a?'a':''} onClick={()=>setA(i+1)}/>)}</div><div className="arcadeControls"><button onClick={()=>setA(v=>clamp(v-1,0,n))}>−</button><b>{a} purple · {n-a} gold</b><button onClick={()=>setA(v=>clamp(v+1,0,n))}>+</button><button className="arcadeCheck" onClick={()=>setWon(a===target)}>Check fairness</button></div></Frame>}

function CombinationArcade({lesson}){const target=(lesson.a??3)*(lesson.b??2),[v,setV]=useState(0),[won,setWon]=useState(false);const reset=()=>{setV(0);setWon(false)};return <Frame title="Count every pairing" instruction={`${lesson.a??3} first choices × ${lesson.b??2} second choices. How many combinations?`} won={won} onReset={reset}><div className="arcadeCombos"><span>{(lesson.aEmoji||'●').repeat(lesson.a??3)}</span><b>×</b><span>{(lesson.bEmoji||'◆').repeat(lesson.b??2)}</span></div><div className="arcadeControls"><button onClick={()=>setV(n=>clamp(n-1,0,30))}>−</button><b>{v}</b><button onClick={()=>setV(n=>clamp(n+1,0,30))}>+</button><button className="arcadeCheck" onClick={()=>setWon(v===target)}>Check</button></div></Frame>}

function LogicArcade({lesson}){const[a,setA]=useState(false),[b,setB]=useState(false),[won,setWon]=useState(false),rule=lesson.rule||'AND';const light=rule==='AND'?a&&b:a||b,reset=()=>{setA(false);setB(false);setWon(false)};return <Frame title="Power the light" instruction={rule==='AND'?'Turn on both switches so the AND light glows.':'Turn on at least one switch so the OR light glows.'} won={won} onReset={reset}><div className="arcadeLogic"><button className={a?'on':''} onClick={()=>setA(v=>!v)}>A {a?'ON':'OFF'}</button><div className={light?'logicBulb on':'logicBulb'}>💡</div><button className={b?'on':''} onClick={()=>setB(v=>!v)}>B {b?'ON':'OFF'}</button></div><button className="arcadeCheck full" onClick={()=>setWon(light===Boolean(lesson.target??true))}>Test circuit</button></Frame>}

function ConstraintArcade({lesson}){const t=lesson.target||{color:'blue',shape:'corners',size:'large'},colors=['blue','red'],shapes=['corners','round'],sizes=['small','large'],[c,setC]=useState(colors[0]),[s,setS]=useState(shapes[0]),[z,setZ]=useState(sizes[0]),[won,setWon]=useState(false);const cycle=(arr,v,set)=>set(arr[(arr.indexOf(v)+1)%arr.length]),reset=()=>{setC(colors[0]);setS(shapes[0]);setZ(sizes[0]);setWon(false)};return <Frame title="Meet every rule" instruction={`Build something ${t.color}, ${t.shape}, and ${t.size}.`} won={won} onReset={reset}><div className={`arcadeConstraint ${c} ${s} ${z}`}><span/></div><div className="arcadeChoices"><button onClick={()=>cycle(colors,c,setC)}>Color: {c}</button><button onClick={()=>cycle(shapes,s,setS)}>Shape: {s}</button><button onClick={()=>cycle(sizes,z,setZ)}>Size: {z}</button></div><button className="arcadeCheck full" onClick={()=>setWon(c===t.color&&s===t.shape&&z===t.size)}>Check all rules</button></Frame>}

function SliderArcade({lesson,kind}){let min=0,max=12,target=5,label='setting',read=v=>v;if(kind==='race'){min=1;max=16;target=lesson.timeTarget??5;label='time';read=v=>`${v} sec`}if(kind==='orbit'){min=lesson.min??1;max=lesson.max??9;target=lesson.targetSpeed??5;label='sideways speed'}if(kind==='graph-change'){min=0;max=8;target=lesson.targetRate??3;label='rate'}if(kind==='area-slices'){min=2;max=lesson.maxSlices??16;target=lesson.targetSlices??12;label='slices'}if(kind==='energy'){min=0;max=lesson.maxHeight??10;target=lesson.targetSpeed??8;label='hill level'}const[v,setV]=useState(min),[won,setWon]=useState(false),reset=()=>{setV(min);setWon(false)};return <Frame title={kind==='area-slices'?'Refine the approximation':kind==='graph-change'?'Tune the rate':kind==='orbit'?'Find the orbit zone':kind==='energy'?'Tune the hill':'Tune the pace'} instruction={`Adjust the ${label} to reach ${target}.`} won={won} onReset={reset}><div className={`arcadeSliderVisual ${kind}`}><div style={{width:`${((v-min)/(max-min||1))*100}%`}}/><span>{kind==='orbit'?'🛰️':kind==='energy'?'🎢':kind==='area-slices'?'▥':'📈'}</span></div><input className="arcadeRange" type="range" min={min} max={max} value={v} onChange={e=>setV(+e.target.value)}/><b className="arcadeReadout">{label}: {read(v)}</b><button className="arcadeCheck full" onClick={()=>setWon(v===target)}>Check</button></Frame>}

function VectorArcade({lesson}){const tx=lesson.targetX??4,ty=lesson.targetY??3,[x,setX]=useState(0),[y,setY]=useState(0),[won,setWon]=useState(false),reset=()=>{setX(0);setY(0);setWon(false)};return <Frame title="Build the vector" instruction={`Reach (${tx}, ${ty}) by combining horizontal and vertical pushes.`} won={won} onReset={reset}><div className="arcadeVector"><div className="vectorArrow" style={{transform:`rotate(${Math.atan2(-y,x||.01)*180/Math.PI}deg) scaleX(${.5+Math.hypot(x,y)/8})`}}>➜</div><b>({x}, {y})</b></div><div className="arcadeDualControls"><div><b>Across {x}</b><button onClick={()=>setX(v=>clamp(v-1,0,8))}>−</button><button onClick={()=>setX(v=>clamp(v+1,0,8))}>+</button></div><div><b>Up {y}</b><button onClick={()=>setY(v=>clamp(v-1,0,8))}>−</button><button onClick={()=>setY(v=>clamp(v+1,0,8))}>+</button></div></div><button className="arcadeCheck full" onClick={()=>setWon(x===tx&&y===ty)}>Fire thrusters</button></Frame>}

function ProductArcade({lesson,kind}){const target=kind==='torque'?(lesson.rightWeight??3)*(lesson.rightDistance??4):lesson.target??12,[a,setA]=useState(1),[b,setB]=useState(1),[won,setWon]=useState(false),reset=()=>{setA(1);setB(1);setWon(false)},aLabel=kind==='torque'?'weight':'mass',bLabel=kind==='torque'?'distance':'speed';return <Frame title={kind==='torque'?'Balance the leverage':'Build the momentum'} instruction={`Make ${aLabel} × ${bLabel} equal ${target}.`} won={won} onReset={reset}><div className="arcadeProduct"><div><small>{aLabel.toUpperCase()}</small><b>{a}</b></div><span>×</span><div><small>{bLabel.toUpperCase()}</small><b>{b}</b></div><span>=</span><strong>{a*b}</strong></div><div className="arcadeDualControls"><div><button onClick={()=>setA(v=>clamp(v-1,1,10))}>−</button><button onClick={()=>setA(v=>clamp(v+1,1,10))}>+</button></div><div><button onClick={()=>setB(v=>clamp(v-1,1,10))}>−</button><button onClick={()=>setB(v=>clamp(v+1,1,10))}>+</button></div></div><button className="arcadeCheck full" onClick={()=>setWon(a*b===target)}>Test</button></Frame>}

function TrialsArcade({lesson}){const target=lesson.target??50,[v,setV]=useState(lesson.observed??40),[won,setWon]=useState(false),reset=()=>{setV(lesson.observed??40);setWon(false)};return <Frame title="Prediction vs. result" instruction={`The short run was ${lesson.observed??40}%. Set the long-run expectation.`} won={won} onReset={reset}><input className="arcadeRange" type="range" min="0" max="100" step="10" value={v} onChange={e=>setV(+e.target.value)}/><b className="arcadeReadout">{v}% expected</b><button className="arcadeCheck full" onClick={()=>setWon(v===target)}>Check expectation</button></Frame>}

function MissionArcade({lesson}){const stage=lesson.stages?.[0]||{question:'2 + 2',target:4},[v,setV]=useState(0),[won,setWon]=useState(false),reset=()=>{setV(0);setWon(false)};return <Frame title="One-control mission" instruction={stage.question} won={won} onReset={reset}><div className="arcadeMission">🚀 <b>{v}</b></div><div className="arcadeControls"><button onClick={()=>setV(n=>clamp(n-1,0,40))}>−</button><button onClick={()=>setV(n=>clamp(n+1,0,40))}>+</button><button className="arcadeCheck" onClick={()=>setWon(v===stage.target)}>Lock control</button></div></Frame>}

function GenericArcade({lesson}){const[v,setV]=useState(0),[won,setWon]=useState(false),target=Math.min(5,Math.max(1,lesson.difficulty||2)),reset=()=>{setV(0);setWon(false)};return <Frame title="Concept warm-up" instruction="Build the target, then check it." won={won} onReset={reset}><div className="arcadeGeneric">{Array.from({length:5},(_,i)=><button key={i} className={i<v?'on':''} onClick={()=>setV(i+1)}>●</button>)}</div><button className="arcadeCheck full" onClick={()=>setWon(v===target)}>Check {target}</button></Frame>}

export function ConceptArcade({lesson}){const m=lesson.expandedMechanic||lesson.mechanic;if(['select-parts','match-set','pour','equivalence-wheel'].includes(m))return <FractionArcade lesson={lesson}/>;if(['ratio','slope'].includes(m))return <RatioArcade lesson={lesson}/>;if(['machine','rule-blocks'].includes(m))return <MachineArcade lesson={lesson}/>;if(m==='balance')return <BalanceArcade lesson={lesson}/>;if(m==='coordinate')return <CoordinateArcade lesson={lesson}/>;if(m==='launch')return <LineArcade lesson={lesson}/>;if(['pattern-choice','matrix','analogy','sort','fold'].includes(m))return <PatternArcade lesson={lesson}/>;if(m==='probability-bag')return <ProbabilityBagArcade lesson={lesson}/>;if(m==='fair-spinner')return <SpinnerArcade lesson={lesson}/>;if(m==='combinations')return <CombinationArcade lesson={lesson}/>;if(m==='logic-switch')return <LogicArcade lesson={lesson}/>;if(m==='constraint')return <ConstraintArcade lesson={lesson}/>;if(m==='trials')return <TrialsArcade lesson={lesson}/>;if(m==='vector')return <VectorArcade lesson={lesson}/>;if(['momentum','torque'].includes(m))return <ProductArcade lesson={lesson} kind={m}/>;if(['race','orbit','graph-change','area-slices','energy'].includes(m))return <SliderArcade lesson={lesson} kind={m}/>;if(m==='mission')return <MissionArcade lesson={lesson}/>;return <GenericArcade lesson={lesson}/>}
