import React,{useState}from'react';
import'./conceptConnections.css';
import{MiniSudoku}from'./miniSudoku';

const amountToNumber=(raw,fallback=.5)=>{if(typeof raw==='number'&&Number.isFinite(raw))return Math.max(0,Math.min(1,raw));if(typeof raw==='string'){const s=raw.trim();if(s.endsWith('%')){const n=parseFloat(s);if(Number.isFinite(n))return Math.max(0,Math.min(1,n/100))}if(s.includes('/')){const[a,b]=s.split('/').map(Number);if(Number.isFinite(a)&&Number.isFinite(b)&&b!==0)return Math.max(0,Math.min(1,a/b))}const n=Number(s);if(Number.isFinite(n))return Math.max(0,Math.min(1,n))}return fallback};
function FractionLab({lesson}){const fallback=(lesson.targetSelected??2)/(lesson.totalParts||4),initial=amountToNumber(lesson.numericTarget??lesson.target,fallback),[value,setValue]=useState(initial),safeValue=amountToNumber(value,fallback),den=8,num=Math.round(safeValue*den),percent=Math.round(safeValue*100),decimal=Number(safeValue.toFixed(3));return <><div className="connectionControl"><small>MOVE ONE IDEA — WATCH EVERY REPRESENTATION CHANGE</small><input type="range" min="0" max="8" value={num} onChange={e=>setValue(+e.target.value/8)}/><b>{num}/{den} of one whole</b></div><div className="connectionModules"><article><small>FRACTION</small><strong>{num}/{den}</strong><div className="miniBar">{Array.from({length:den},(_,i)=><i key={i} className={i<num?'on':''}/>)}</div><p>{num} of {den} equal parts</p></article><article><small>DECIMAL</small><strong>{decimal}</strong><div className="decimalMeter"><i style={{width:`${percent}%`}}/></div><p>The same point between 0 and 1</p></article><article><small>CUT WHOLE</small><div className="pieVisual" style={{background:`conic-gradient(#6d5dfc 0 ${percent}%,#eef0f5 ${percent}% 100%)`}}><span/></div><p>{percent}% of the circle is filled</p></article><article><small>PERCENT</small><strong>{percent}%</strong><div className="hundredDots">{Array.from({length:20},(_,i)=><i key={i} className={i<Math.round(percent/5)?'on':''}/>)}</div><p>{percent} out of every 100</p></article><article className="numberLineCard"><small>NUMBER LINE</small><div className="connectionNumberLine"><span>0</span><i style={{left:`${percent}%`}}/><span>1</span></div><p>Every representation lands at the same location.</p></article></div></>}
function PatternLab(){return <div className="connectionModules"><article><small>SEE THE REPEAT</small><div className="patternStrip"><b>●</b><em>■</em><b>●</b><em>■</em><b>●</b><em>■</em></div><p>A-B-A-B-A-B</p></article><article><small>NUMBER IT</small><strong>1, 2, 1, 2…</strong><p>The same structure can use numbers.</p></article><article><small>RULE</small><strong>odd → A<br/>even → B</strong><p>Position predicts what comes next.</p></article></div>}
function CoordinateLab({lesson}){const x=lesson.targetX??3,y=lesson.targetY??2;return <div className="connectionModules"><article><small>ADDRESS</small><strong>({x}, {y})</strong><p>{x} across, then {y} up</p></article><article><small>GRID</small><div className="miniGrid"><i style={{left:`${12+x*15}%`,bottom:`${12+y*15}%`}}/></div><p>One ordered pair marks one exact spot.</p></article><article><small>MOVEMENT</small><strong>→ {x}<br/>↑ {y}</strong><p>Movement becomes an address.</p></article></div>}
function BalanceLab({lesson}){const fixed=lesson.fixed??2,target=lesson.target??6,unknown=target-fixed;return <div className="connectionModules"><article><small>SETUP</small><strong>? + {fixed} = {target}</strong><p>The unknown is a quantity, not a symbol trick.</p></article><article><small>UNDO</small><strong>{target} − {fixed} = {unknown}</strong><p>Reverse the known operation.</p></article><article><small>CHECK</small><strong>{unknown} + {fixed} = {target}</strong><p>Put it back in to prove it works.</p></article></div>}
function RatioLab({lesson}){const a=lesson.ratioA||2,b=lesson.ratioB||1;return <div className="connectionModules"><article><small>RATIO</small><strong>{a}:{b}</strong><p>{a} for every {b}</p></article><article><small>PICTURE</small><div className="ratioDots">{Array.from({length:a},(_,i)=><b key={'a'+i}>●</b>)}{Array.from({length:b},(_,i)=><em key={'b'+i}>●</em>)}</div><p>See the relationship.</p></article><article><small>SCALE IT</small><strong>{a*2}:{b*2}</strong><p>Both parts change together.</p></article></div>}
function FunctionLab(){return <div className="connectionModules"><article><small>EXAMPLES</small><strong>1 → 3<br/>2 → 5<br/>3 → 7</strong><p>Each row is one input/output pair.</p></article><article><small>MACHINE</small><div className="functionPipe"><b>input</b><span>×2, +1</span><b>output</b></div><p>The rule acts on one input at a time.</p></article><article><small>RULE</small><strong>output = 2×input + 1</strong><p>Words, machine and equation describe the same process.</p></article></div>}
function ScaleLab(){return <div className="connectionModules"><article><small>MODEL</small><strong>1 → 2</strong><p>Scale factor ×2</p></article><article><small>LENGTH</small><div className="scaleBlocks"><b>■</b><span>→</span><b>■■</b></div><p>Every length doubles.</p></article><article><small>AREA</small><strong>2× length<br/>4× area</strong><p>Two dimensions scale.</p></article></div>}
function RateLab(){return <div className="connectionModules"><article><small>TOTAL</small><strong>6 spaces / 3 sec</strong><p>Two quantities are changing.</p></article><article><small>PER ONE</small><strong>2 spaces / sec</strong><p>Reduce to one second.</p></article><article><small>PREDICT</small><strong>5 sec → 10 spaces</strong><p>Scale the unit rate.</p></article></div>}
function SlopeLab(){return <div className="connectionModules"><article><small>RISE / RUN</small><strong>2 / 4</strong><p>Up compared with across.</p></article><article><small>SAME SLOPE</small><strong>1 / 2 = 3 / 6</strong><p>Equivalent ratios mean equal steepness.</p></article><article><small>VISUAL</small><div className="slopeMini"><i/></div><p>Different triangles can sit on one line.</p></article></div>}
function GenericLab({lesson}){return <div className="connectionModules"><article><small>CONCEPT</small><strong>{lesson.concept}</strong><p>{lesson.intro}</p></article><article><small>STRUCTURE</small><strong>What stays the same?</strong><p>Look past the surface objects.</p></article><article><small>TRANSFER</small><strong>New context, same idea</strong><p>Use the relationship somewhere else.</p></article></div>}
export function ConceptConnections({lesson}){let content;if(['select-parts','match-set','pour','equivalence-wheel'].includes(lesson.mechanic))content=<FractionLab key={lesson.id} lesson={lesson}/>;else if(lesson.mechanic==='pattern-choice')content=<PatternLab/>;else if(lesson.mechanic==='coordinate')content=<CoordinateLab lesson={lesson}/>;else if(lesson.mechanic==='balance')content=<BalanceLab lesson={lesson}/>;else if(lesson.mechanic==='ratio')content=<RatioLab lesson={lesson}/>;else if(['machine','rule-blocks'].includes(lesson.mechanic))content=<FunctionLab/>;else if(['scale','scale-map'].includes(lesson.mechanic))content=<ScaleLab/>;else if(['race','deal'].includes(lesson.mechanic))content=<RateLab/>;else if(lesson.mechanic==='slope')content=<SlopeLab/>;else content=<GenericLab lesson={lesson}/>;return <><section className="panel connectionsLab"><div className="connectionsHeading"><div><small>ONE IDEA · MANY REPRESENTATIONS</small><h2>Connections Lab</h2><p>Change or compare one representation and connect it to the others.</p></div><span>🧠</span></div>{content}<p className="connectionsTakeaway">The picture, number, rule and real situation can look different while the underlying relationship stays the same.</p></section><MiniSudoku/></>}
