import React,{useMemo,useState}from'react';
import{Building2,Gamepad2,RotateCcw,Star,Shuffle,ArrowRight}from'lucide-react';
import'./brainBreak.css';

export function AdventureCheckpoint({mastery,coins,onWorld,onBrainBreak,onContinue}){return <main className="app celebrationPage"><section className="celebrationHero panel"><div className="celebrationBurst">🏆</div><small>Adventure 1 complete</small><h1>Foundations mastered!</h1><p>You explored fractions, patterns, early algebra, coordinates, logic, and spatial reasoning. Your world has new things waiting — or you can continue into Relationships & Scaling.</p><div className="celebrationStats"><span><Star/> {mastery} mastery</span><span>🪙 {coins} coins</span></div></section><section className="celebrationChoices"><button className="celebrationChoice worldChoice" onClick={onWorld}><Building2/><div><small>See what changed</small><h2>Visit My World</h2><p>Check new buildings, pending orders, and spend what you earned.</p></div><b>Enter world →</b></button><button className="celebrationChoice breakChoice" onClick={onBrainBreak}><Gamepad2/><div><small>Take a brain break</small><h2>Gem Mix</h2><p>Play a quick match-three game before the next adventure.</p></div><b>Play →</b></button><button className="celebrationChoice continueChoice" onClick={onContinue}><ArrowRight/><div><small>Adventure 2</small><h2>Relationships & Scaling</h2><p>Ratios, scale, rates, functions, slope, unit rates, and multi-step missions.</p></div><b>Start lesson 11 →</b></button></section></main>}
export function LessonCelebration({mastery,coins,onWorld,onBrainBreak,onRestart}){return <main className="app celebrationPage"><section className="celebrationHero panel"><div className="celebrationBurst">🎉</div><small>Two adventures complete</small><h1>You made it through all 20!</h1><p>You built foundations, then used them in ratios, scaling, rates, functions, slope, and relationship missions. Now choose what happens next.</p><div className="celebrationStats"><span><Star/> {mastery} mastery</span><span>🪙 {coins} coins</span></div></section><section className="celebrationChoices"><button className="celebrationChoice worldChoice" onClick={onWorld}><Building2/><div><small>Use what you earned</small><h2>Go to My World</h2><p>See how the city changed and tackle the new orders your learning created.</p></div><b>Enter world →</b></button><button className="celebrationChoice breakChoice" onClick={onBrainBreak}><Gamepad2/><div><small>Take a brain break</small><h2>Gem Mix</h2><p>Swap colorful gems, trigger cascades, and chase the star target.</p></div><b>Play →</b></button><button className="celebrationChoice" onClick={onRestart}><RotateCcw/><div><small>Keep exploring</small><h2>Replay from Adventure 1</h2><p>Return to lesson 1 without losing anything you have earned.</p></div><b>Start again →</b></button></section></main>}
const SIZE=7,GEMS=['🔴','🟠','🟡','🟢','🔵','🟣'];
function randomGem(){return GEMS[Math.floor(Math.random()*GEMS.length)]}function adjacent(a,b){const ar=Math.floor(a/SIZE),ac=a%SIZE,br=Math.floor(b/SIZE),bc=b%SIZE;return Math.abs(ar-br)+Math.abs(ac-bc)===1}
function findMatches(board){const hit=new Set();for(let r=0;r<SIZE;r++){let start=0;for(let c=1;c<=SIZE;c++){const same=c<SIZE&&board[r*SIZE+c]===board[r*SIZE+start];if(!same){if(c-start>=3)for(let x=start;x<c;x++)hit.add(r*SIZE+x);start=c}}}for(let c=0;c<SIZE;c++){let start=0;for(let r=1;r<=SIZE;r++){const same=r<SIZE&&board[r*SIZE+c]===board[start*SIZE+c];if(!same){if(r-start>=3)for(let y=start;y<r;y++)hit.add(y*SIZE+c);start=r}}}return [...hit]}
function drop(board,matches){const next=[...board];matches.forEach(i=>next[i]=null);for(let c=0;c<SIZE;c++){const kept=[];for(let r=SIZE-1;r>=0;r--){const v=next[r*SIZE+c];if(v)kept.push(v)}for(let r=SIZE-1,k=0;r>=0;r--)next[r*SIZE+c]=k<kept.length?kept[k++]:randomGem()}return next}
function cleanBoard(){let b=Array.from({length:SIZE*SIZE},()=>randomGem()),m=findMatches(b),guard=0;while(m.length&&guard++<20){b=drop(b,m);m=findMatches(b)}return b}
export function BrainBreak({onDone}){const[board,setBoard]=useState(()=>cleanBoard()),[selected,setSelected]=useState(null),[score,setScore]=useState(0),[moves,setMoves]=useState(18),[clears,setClears]=useState(0),[combo,setCombo]=useState(0),[message,setMessage]=useState('Swap two neighboring gems to make a match.'),[flash,setFlash]=useState([]),[busy,setBusy]=useState(false);const target=1200,won=score>=target;
const resolve=(start,depth=1)=>{const matches=findMatches(start);if(!matches.length){setBusy(false);setCombo(depth-1);return}setFlash(matches);const earned=matches.length*50*depth;setScore(s=>s+earned);setClears(c=>c+matches.length);setCombo(depth);setMessage(depth>1?`Cascade x${depth}! +${earned} ✨`:matches.length>=4?`Sweet match! +${earned}`:`Nice! +${earned}`);setTimeout(()=>{const fallen=drop(start,matches);setBoard(fallen);setFlash([]);setTimeout(()=>resolve(fallen,depth+1),180)},260)};
const choose=i=>{if(busy||won||moves<=0)return;if(selected===null){setSelected(i);return}if(i===selected){setSelected(null);return}if(!adjacent(selected,i)){setSelected(i);setMessage('Choose a gem right beside it.');return}const swapped=[...board];[swapped[selected],swapped[i]]=[swapped[i],swapped[selected]];const matches=findMatches(swapped);if(!matches.length){setSelected(null);setMessage('That swap does not make a match. Try another!');return}setMoves(v=>v-1);setSelected(null);setBoard(swapped);setBusy(true);resolve(swapped)};
const reset=()=>{setBoard(cleanBoard());setSelected(null);setFlash([]);setScore(0);setMoves(18);setClears(0);setCombo(0);setBusy(false);setMessage('New board! Match 3 or more.');};const progress=Math.min(100,score/target*100);const status=useMemo(()=>won?'Star target reached!':moves<=0?'Out of moves — shuffle for another round.':`${moves} moves left`,[won,moves]);return <main className="app celebrationPage"><section className="panel brainBreak candyBreak"><div className="candyTop"><div><small>Brain break</small><h1>Gem Mix</h1><p>Swap neighboring gems. Make matches, create cascades, and fill the star meter.</p></div><div className="candyScore"><b>{score}</b><span>score</span></div></div><div className="starGoal"><div><span>⭐</span><b>{status}</b><small>{score} / {target}</small></div><div className="starTrack"><i style={{width:`${progress}%`}}/></div></div><div className="candyHud"><span>💎 {clears} cleared {combo>1&&<b> • COMBO x{combo}</b>}</span><button className="secondary" onClick={reset}><Shuffle size={18}/> New board</button></div><div className={`gemBoard ${busy?'boardBusy':''}`}>{board.map((gem,i)=><button aria-label={`Gem ${i+1}`} key={i} className={`${selected===i?'gem selectedGem':'gem'} ${flash.includes(i)?'matchedGem':''}`} onClick={()=>choose(i)}>{gem}</button>)}</div><p className="feedback candyMessage">{message}</p>{won&&<div className="sweetBanner">🌟 Sweet! Brain break complete! 🌟</div>}{moves<=0&&!won&&<div className="successNote">Great round! Start a new board or head back when you're ready.</div>}<button className="primary" onClick={onDone}>{won?'Back to the adventure':'Leave brain break'}</button></section></main>}
