import React,{useEffect,useMemo,useState}from'react';
import'./newBuildingInteriors.css';

const BUILDINGS={
 transit:{emoji:'🚉',name:'Number Line Transit',tagline:'Run the town by navigating positive and negative space.',scene:'🚏  🚋  🛤️',missions:[
  {id:'route',title:'Rescue route',story:'A passenger is waiting 4 stops left of Town Square.',steps:[{label:'Direction',prompt:'Which direction is left of zero?',choices:[['Negative',1],['Positive',0]],explain:'Left of zero is the negative direction.',hints:['Picture a number line with 0 in the middle.','Numbers get smaller as you move left.','So the direction left of zero is negative.']},{label:'Stop',prompt:'Choose the destination.',choices:[['−4',1],['+4',0],['−2',0]],explain:'Four stops left of zero is −4.',hints:['Start at 0.','Move one stop left four times: −1, −2, −3, −4.','The destination is −4.']},{label:'Return',prompt:'From −4, how many stops return to zero?',choices:[['4',1],['−4',0],['8',0]],explain:'Moving 4 stops right returns from −4 to 0.',hints:['Count the gaps from −4 back to 0.','−4→−3→−2→−1→0 is four moves.','The return trip is 4 stops.']}]},
  {id:'delivery',title:'Express delivery',story:'Plan a trip that crosses zero.',steps:[{label:'Start',prompt:'The train begins at −3 and moves 5 stops right. Where does it land?',choices:[['2',1],['−8',0],['8',0]],explain:'−3 + 5 = 2.',hints:['Begin three spaces left of zero.','Moving 3 right gets you to 0; there are 2 moves left.','So the train lands at +2.']},{label:'Next leg',prompt:'From 2, move 4 stops left.',choices:[['−2',1],['6',0],['−6',0]],explain:'2 − 4 = −2.',hints:['Use 2 as the new starting point.','Two left reaches 0, then two more left.','That finishes at −2.']},{label:'Distance',prompt:'How many total stops were traveled?',choices:[['9',1],['2',0],['7',0]],explain:'5 stops plus 4 stops makes 9 traveled.',hints:['Distance traveled counts movement, not the final location.','The first leg used 5 stops and the second used 4.','5 + 4 = 9 total stops.']}]}
 ]},
 architect:{emoji:'🪚',name:'Geometry Workshop: Woodshop',tagline:'Measure, cut, and build with rulers, fractions, symmetry, and scale.',scene:'🪚  📏  🪵  📐',missions:[
  {id:'cuts',title:'Measure & cut shelf supports',story:'Use the ruler bench to divide wood into equal fractional lengths.',steps:[{label:'Halves',prompt:'A 1-inch strip is cut into 2 equal pieces. How long is each piece?',choices:[['1/2 inch',1],['1/4 inch',0],['2 inches',0]],explain:'One whole inch split into 2 equal pieces makes two 1/2-inch pieces.',hints:['Start with 1 whole inch.','Two equal pieces means divide by 2.','Each piece is 1/2 inch.']},{label:'Quarters',prompt:'A 1-inch strip is cut into 4 equal pieces. How long is each piece?',choices:[['1/4 inch',1],['1/2 inch',0],['4 inches',0]],explain:'One whole inch split into 4 equal pieces makes four 1/4-inch pieces.',hints:['Four equal pieces means divide the whole into fourths.','Each fourth is one quarter of an inch.','Each piece is 1/4 inch.']},{label:'Combine',prompt:'Two 1/4-inch pieces placed end to end make what length?',choices:[['1/2 inch',1],['1/4 inch',0],['1 inch',0]],explain:'1/4 + 1/4 = 2/4 = 1/2.',hints:['Put two quarter-inch pieces together.','That makes 2 quarters.','2/4 is the same length as 1/2.']}]},
  {id:'facade',title:'Cut matching trim',story:'Build a symmetrical window frame from matching wood pieces.',steps:[{label:'Mirror mark',prompt:'A decorative cut is 2 inches left of the center line. Where should the matching cut go?',choices:[['2 inches right',1],['4 inches right',0],['At center',0]],explain:'A mirror image keeps the same distance on the opposite side.',hints:['Imagine folding the frame along its center line.','The matching mark must land exactly on top of the first one.','Use the same distance — 2 inches — on the right.']},{label:'Matching slats',prompt:'One side of the frame has 3 vertical slats. How many slats are needed for both mirrored sides?',choices:[['6',1],['3',0],['9',0]],explain:'Three on each side makes six.',hints:['Symmetry gives every slat a matching partner.','Three slats on the left need three on the right.','3 + 3 = 6 slats.']},{label:'Center brace',prompt:'Which piece can sit exactly on the line of symmetry without needing a matching pair?',choices:[['Center brace',1],['Side trim',0],['Corner block',0]],explain:'A piece on the symmetry line mirrors onto itself.',hints:['Think about what happens exactly on the fold line.','A centered piece lands on itself when mirrored.','The center brace does not need a second copy.']}]},
  {id:'courtyard',title:'Scale the workbench frame',story:'A 3 × 4 workbench frame is being built at double scale.',steps:[{label:'Width',prompt:'The model is 3 units wide. Double the width for the full build.',choices:[['6',1],['5',0],['9',0]],explain:'3 × 2 = 6.',hints:['Double means two equal copies.','Two groups of 3 are 3 + 3.','So the new width is 6.']},{label:'Length',prompt:'The model is 4 units long. Double the length.',choices:[['8',1],['6',0],['16',0]],explain:'4 × 2 = 8.',hints:['Use the same scale factor as the width.','Two groups of 4 are 4 + 4.','The new length is 8.']},{label:'Top area',prompt:'What is the area of the new 6 × 8 workbench top?',choices:[['48',1],['24',0],['28',0]],explain:'6 × 8 = 48 square units.',hints:['Area counts all the square units inside the tabletop.','There are 6 rows of 8, or 8 rows of 6.','6 × 8 = 48 square units.']}]}
 ]},
  think:{emoji:'🧠',name:'The Think Tank',tagline:'A cozy puzzle lounge for analogies, classification, logic, and flexible reasoning.',scene:'🧩  🔍  🧠  💡',missions:[
  {id:'analogy',title:'Crack the analogy wall',story:'The clue board only opens when you identify the relationship—not just the objects.',steps:[
    {label:'Relationship',prompt:'Bird is to nest as bee is to ___?',choices:[['Hive',1],['Flower',0],['Wing',0]],explain:'A nest is where a bird lives; a hive is where bees live.',hints:['Ask what relationship connects bird and nest.','The first object is an animal and the second is its home.','Which choice is the home of bees?']},
    {label:'Transfer',prompt:'Key is to lock as password is to ___?',choices:[['Account',1],['Keyboard',0],['Screen',0]],explain:'A key gives access through a lock; a password gives access to an account.',hints:['Think about what the first item allows you to open or access.','A password is also an access tool.','What does a password commonly unlock?']},
    {label:'Rule',prompt:'What relationship did both analogies use?',choices:[['Something that gives access or belongs with a place',1],['Things with the same color',0],['Things with the same number of letters',0]],explain:'Analogies are about relationships between ideas, not surface similarities.',hints:['Ignore how the words look.','Focus on how the two ideas are connected.','Choose the answer that describes the relationship.']}
  ]},
  {id:'classification',title:'Sort the mystery cards',story:'Four cards look similar, but one follows a different rule.',steps:[
    {label:'Notice',prompt:'Which does not belong: triangle, square, rectangle, circle?',choices:[['Circle',1],['Square',0],['Rectangle',0]],explain:'The other three are polygons made only from straight sides.',hints:['Look for a property shared by three choices.','Three shapes are made only from straight lines.','Which one has a curved edge?']},
    {label:'New rule',prompt:'Which does not belong: 8, 12, 16, 18?',choices:[['18',1],['12',0],['16',0]],explain:'8, 12, and 16 are multiples of 4; 18 is not.',hints:['Try grouping the numbers by a multiplication pattern.','8 = 4×2, 12 = 4×3, 16 = 4×4.','Which number breaks the ×4 pattern?']},
    {label:'Explain',prompt:'What makes a strong classification rule?',choices:[['One clear property that fits the group',1],['Whatever answer looks unusual',0],['The longest item',0]],explain:'A useful classification rule is based on a consistent property that can be tested.',hints:['A rule should work for every member of the group.','It should be something you can check.','Choose the consistent property idea.']}
  ]},
  {id:'logic',title:'Open the logic safe',story:'Use all the clues together. One clue alone is not enough.',steps:[
    {label:'Clue 1',prompt:'A mystery number is greater than 5 and less than 10. Which could it be?',choices:[['7',1],['4',0],['12',0]],explain:'7 satisfies both limits.',hints:['The number must pass two tests.','It must be above 5.','It must also stay below 10.']},
    {label:'Clue 2',prompt:'Now add: the number is odd and not 7. Which fits?',choices:[['9',1],['8',0],['7',0]],explain:'9 is between 5 and 10, odd, and not 7.',hints:['Keep every earlier clue.','The remaining choices must also be odd.','Which number satisfies all conditions?']},
    {label:'Constraint',prompt:'Why did the answer change after the new clue?',choices:[['More constraints removed possibilities',1],['The first clue became false',0],['Odd numbers are always larger',0]],explain:'Each additional constraint narrows the set of possible answers.',hints:['The old clues still matter.','The new clue adds another filter.','More filters leave fewer possible answers.']}
  ]}
 ]},
  observatory:{emoji:'🔭',name:'Sky Observatory',tagline:'Use patterns, coordinates, and relationships to explore the sky.',scene:'🌙  ✨  🔭',missions:[
  {id:'constellation',title:'Map a constellation',story:'Three stars reveal a movement pattern across the sky.',steps:[{label:'Pattern',prompt:'Stars appear at (1,1), (2,2), (3,3). What comes next?',choices:[['(4,4)',1],['(4,3)',0],['(3,4)',0]],explain:'Both coordinates increase by 1 each time.',hints:['Compare the first number in each pair.','Now compare the second number: both grow by 1 each step.','After (3,3), both coordinates become 4.']},{label:'Rule',prompt:'Which rule describes these points?',choices:[['x = y',1],['x + y = 1',0],['x is always 1',0]],explain:'Every point has matching x and y values.',hints:['Look inside each coordinate pair.','1 matches 1, 2 matches 2, and 3 matches 3.','The rule is x = y.']},{label:'Predict',prompt:'If x = 7, what is y?',choices:[['7',1],['6',0],['14',0]],explain:'If x = y, then y must also be 7.',hints:['Use the rule you just identified.','x and y must have the same value.','If x is 7, y is also 7.']}]},
  {id:'signal',title:'Decode the satellite signal',story:'A satellite sends 2→5, 4→9, 6→13.',steps:[{label:'Find rule',prompt:'What happens to each input?',choices:[['Double, then +1',1],['Add 3',0],['Double, then −1',0]],explain:'2×2+1=5, 4×2+1=9, 6×2+1=13.',hints:['Try the same operation on all three examples.','Doubling gives 4, 8, 12 — each output is one more.','The rule is double, then add 1.']},{label:'Predict',prompt:'What should input 8 produce?',choices:[['17',1],['16',0],['19',0]],explain:'8×2+1 = 17.',hints:['Use exactly the rule from the first control.','Double 8 to get 16.','Then add 1: 17.']},{label:'Reverse',prompt:'Which input produces 21?',choices:[['10',1],['11',0],['9',0]],explain:'10×2+1 = 21.',hints:['Undo the rule in reverse order.','First subtract 1 from 21 to get 20.','Then halve 20 to get input 10.']}]}
 ]},
 market:{emoji:'🛍️',name:'Market Square',tagline:'Run shops with unit prices, ratios, and smart comparisons.',scene:'🍎  🛒  🥖',missions:[
  {id:'market-deal',title:'Stock the fruit stand',story:'Two sellers offer different bundle prices. Choose the better unit price.',steps:[{label:'Seller A',prompt:'4 baskets cost 8 coins. What is the cost per basket?',choices:[['2 coins',1],['4 coins',0],['8 coins',0]],explain:'8 ÷ 4 = 2 coins per basket.',hints:['Unit price means the price for one basket.','Split 8 coins equally across 4 baskets.','Each basket costs 2 coins.']},{label:'Seller B',prompt:'3 baskets cost 9 coins. What is the cost per basket?',choices:[['3 coins',1],['6 coins',0],['9 coins',0]],explain:'9 ÷ 3 = 3 coins per basket.',hints:['Again, find the price of one.','Split 9 coins across 3 baskets.','Each basket costs 3 coins.']},{label:'Choose',prompt:'Which seller gives the lower unit price?',choices:[['Seller A',1],['Seller B',0],['Same price',0]],explain:'2 coins per basket is less than 3.',hints:['Compare the two per-basket prices.','Lower cost per basket is the better deal.','Seller A costs less for each basket.']}]},
  {id:'market-ratio',title:'Prepare the festival stand',story:'The market display uses 3 red flags for every 2 yellow flags.',steps:[{label:'Small display',prompt:'Which set matches 3 red : 2 yellow?',choices:[['3 red, 2 yellow',1],['3 red, 3 yellow',0],['2 red, 3 yellow',0]],explain:'That is exactly the 3:2 relationship.',hints:['Read the ratio in order.','The first number belongs to red flags.','Use 3 red and 2 yellow.']},{label:'Double it',prompt:'Double the display while keeping the same ratio.',choices:[['6 red, 4 yellow',1],['6 red, 2 yellow',0],['5 red, 4 yellow',0]],explain:'Both parts doubled, so the relationship stayed the same.',hints:['Scale both sides by the same factor.','Double 3 and double 2.','That makes 6 and 4.']},{label:'Check',prompt:'Does 9 red : 6 yellow match the same ratio?',choices:[['Yes',1],['No',0]],explain:'9:6 simplifies to 3:2.',hints:['Can both numbers be divided by the same amount?','Divide 9 and 6 by 3.','You get 3 and 2.']}]}
 ]},
 bridge:{emoji:'🌉',name:'Bridge Works',tagline:'Use balance, forces, and structure to connect the growing valley.',scene:'🏗️  🌉  ⚖️',missions:[
  {id:'bridge-balance',title:'Balance the bridge deck',story:'The bridge crew must balance loads around the center support.',steps:[{label:'Equal arms',prompt:'A 4-unit load sits 2 spaces left of the pivot. Which placement balances it on the right?',choices:[['4 units at 2 spaces',1],['2 units at 2 spaces',0],['4 units at 1 space',0]],explain:'Equal weight at equal distance balances the bridge.',hints:['Compare both weight and distance from the pivot.','A perfect mirror creates equal turning effect.','Use the same 4-unit load at 2 spaces.']},{label:'Trade weight for distance',prompt:'A 2-unit load is 4 spaces left. Which right-side load balances it?',choices:[['4 units at 2 spaces',1],['2 units at 2 spaces',0],['4 units at 4 spaces',0]],explain:'2×4 and 4×2 create the same turning effect.',hints:['Think weight × distance.','Left side gives 2 × 4 = 8.','Right side needs another combination that makes 8.']},{label:'Safety check',prompt:'Which side tips if left torque is 12 and right torque is 8?',choices:[['Left side',1],['Right side',0],['Neither',0]],explain:'The larger turning effect pulls its side downward.',hints:['Compare 12 and 8.','The larger torque wins.','12 is on the left.']}]}
 ]},
 carnival:{emoji:'🎡',name:'Logic Carnival',tagline:'Run games with probability, combinations, and logical rules.',scene:'🎡  🎯  🎈',missions:[
  {id:'carnival-spinner',title:'Make the prize wheel fair',story:'Four prize sections must give each color the same chance.',steps:[{label:'Fair wheel',prompt:'Which wheel is fair for 4 colors?',choices:[['4 equal sections',1],['One huge + 3 tiny',0],['2 equal sections',0]],explain:'Equal-sized sections give equal chances.',hints:['Fair means every outcome has the same chance.','Chance follows the amount of wheel space.','Use four equal sections.']},{label:'Chance',prompt:'On a fair 4-color wheel, what is the chance of landing on blue?',choices:[['1 out of 4',1],['1 out of 2',0],['3 out of 4',0]],explain:'One of four equal outcomes is blue.',hints:['Count all equal sections.','Only one section is blue.','That is 1 out of 4.']},{label:'Two spins',prompt:'Which statement is true after one red spin?',choices:[['The next spin can still be any color',1],['Red cannot happen again',0],['Blue must happen next',0]],explain:'A new fair spin starts with the same chances again.',hints:['The wheel does not remember the last spin.','Each spin starts fresh.','All four colors remain possible.']}]}
 ]},
 spaceport:{emoji:'🚀',name:'Valley Spaceport',tagline:'Combine coordinates, vectors, gravity, and change to launch missions.',scene:'🚀  🛰️  🌌',missions:[
  {id:'spaceport-vector',title:'Dock with the satellite',story:'Your ship needs two directional pushes to reach the docking point.',steps:[{label:'Across',prompt:'The satellite is 3 spaces right. What horizontal push is needed?',choices:[['+3',1],['−3',0],['0',0]],explain:'Positive horizontal movement sends the ship right.',hints:['Right is the positive horizontal direction.','Count three spaces.','Use +3.']},{label:'Up',prompt:'It is also 2 spaces up. What vertical push is needed?',choices:[['+2',1],['−2',0],['+3',0]],explain:'Positive vertical movement sends the ship up.',hints:['Up is positive here.','Count two spaces.','Use +2.']},{label:'Vector',prompt:'Which combined vector reaches the satellite?',choices:[['(3, 2)',1],['(2, 3)',0],['(−3, 2)',0]],explain:'The two pushes combine into vector (3,2).',hints:['Write horizontal movement first.','Then write vertical movement.','That gives (3,2).']}]},
  {id:'spaceport-orbit',title:'Tune the orbit',story:'A satellite needs the right sideways speed to keep falling around the planet.',steps:[{label:'Too slow',prompt:'What happens if sideways speed is too low?',choices:[['It falls toward the planet',1],['It escapes',0],['It freezes',0]],explain:'Without enough sideways motion, gravity pulls it inward.',hints:['Gravity is always pulling inward.','Sideways motion helps the satellite keep missing the ground.','Too little sideways speed means it falls inward.']},{label:'Too fast',prompt:'What can happen if sideways speed is much too high?',choices:[['It can escape farther away',1],['It falls straight down',0],['It stops moving',0]],explain:'Enough extra speed can carry the satellite away.',hints:['More sideways speed means a wider path.','At very high speed the path may no longer close.','The satellite can escape outward.']},{label:'Just right',prompt:'What describes a stable orbit?',choices:[['Gravity bends the sideways motion into a curved path',1],['No gravity acts at all',0],['The satellite has no motion',0]],explain:'Orbit is continuous falling while moving sideways.',hints:['The satellite is moving and falling at the same time.','Gravity bends the path inward.','The result is a curved orbit.']}]}
 ]},
 market:{emoji:'🛍️',name:'Market Square',tagline:'Run a busy market with rates, prices, and quantities.',scene:'🍎  🧺  🏷️',missions:[
  {id:'unit',title:'Price the fruit stand',story:'The market needs fair unit prices before opening.',steps:[{label:'Apples',prompt:'4 apples cost 8 coins. What is the price per apple?',choices:[['2 coins',1],['4 coins',0],['8 coins',0]],explain:'8 ÷ 4 = 2 coins per apple.',hints:['Unit price means the cost of one item.','Split 8 coins equally across 4 apples.','Each apple costs 2 coins.']},{label:'Berries',prompt:'3 baskets cost 9 coins. What is the unit price?',choices:[['3 coins',1],['6 coins',0],['9 coins',0]],explain:'9 ÷ 3 = 3 coins per basket.',hints:['Again, find the cost of one basket.','9 shared across 3 baskets gives 3 each.','The unit price is 3 coins.']},{label:'Best deal',prompt:'Which is cheaper per item?',choices:[['Apples at 2',1],['Berries at 3',0]],explain:'2 coins per item is cheaper than 3.',hints:['Compare the two unit prices directly.','2 is less than 3.','So the apple deal is cheaper.']}]},
  {id:'stock',title:'Restock the stalls',story:'Keep every stall in the right ratio.',steps:[{label:'Fruit mix',prompt:'For every 2 apple crates, stock 1 berry crate. If there are 6 apple crates, how many berry crates?',choices:[['3',1],['6',0],['12',0]],explain:'6:3 keeps the same 2:1 ratio.',hints:['6 apples is three groups of 2.','Each group needs 1 berry crate.','So 3 berry crates are needed.']},{label:'Double order',prompt:'A 3:2 snack mix doubles. What ratio keeps the same relationship?',choices:[['6:4',1],['5:4',0],['6:2',0]],explain:'Both parts double: 3:2 becomes 6:4.',hints:['Scale both quantities by the same factor.','Double 3 and double 2.','That gives 6 and 4.']},{label:'Checkout',prompt:'5 baskets at 2 coins each cost how much?',choices:[['10 coins',1],['7 coins',0],['12 coins',0]],explain:'5 groups of 2 coins makes 10.',hints:['Unit price is 2 coins.','There are 5 baskets.','5 × 2 = 10.']}]}
 ]},
 bridge:{emoji:'🌉',name:'Bridge Works',tagline:'Balance forces and structure to connect the valley.',scene:'🔩  🌉  ⚙️',missions:[
  {id:'balance',title:'Balance the bridge deck',story:'Workers are placing loads on both sides of a support.',steps:[{label:'Equal load',prompt:'A 4-block load sits 2 spaces left of the pivot. Which placement balances it?',choices:[['4 blocks, 2 right',1],['2 blocks, 4 right',1],['4 blocks, 1 right',0]],explain:'Equal turning effect can come from equal load/distance or a smaller load farther away.',hints:['Think weight × distance.','4×2 gives a turning effect of 8.','Any choice that also makes 8 balances it.']},{label:'Stronger side',prompt:'Which creates more turning effect: 3 blocks at distance 4, or 5 blocks at distance 2?',choices:[['3 at 4',1],['5 at 2',0]],explain:'3×4=12, while 5×2=10.',hints:['Multiply load by distance.','3×4 is 12.','5×2 is 10, so 12 is larger.']},{label:'Center',prompt:'Where should the pivot be placed for a symmetric bridge deck?',choices:[['At the center',1],['At one end',0]],explain:'A centered pivot gives equal reach to both sides.',hints:['Symmetry gives equal distances.','A center pivot splits the span in half.','That makes balancing easier.']}]},
  {id:'span',title:'Plan the new crossing',story:'The bridge must span the river using equal sections.',steps:[{label:'Sections',prompt:'A 24 m bridge uses 6 equal sections. How long is each?',choices:[['4 m',1],['6 m',0],['18 m',0]],explain:'24 ÷ 6 = 4 meters per section.',hints:['Split the full length equally.','24 shared across 6 sections.','Each section is 4 m.']},{label:'Double scale',prompt:'A 5 m model span is built at 3× scale. Real span?',choices:[['15 m',1],['8 m',0],['10 m',0]],explain:'5×3=15 meters.',hints:['Scale factor 3 means three times as large.','Multiply 5 by 3.','The real span is 15 m.']},{label:'Safety',prompt:'If one section fails, should the design rely on only one support path?',choices:[['No, use multiple supports',1],['Yes, one path is enough',0]],explain:'Redundancy makes structures more resilient.',hints:['Think about what happens if one part stops working.','More than one support path gives backup.','That is structural redundancy.']}]}
 ]},
 carnival:{emoji:'🎡',name:'Logic Carnival',tagline:'Probability, combinations, and logic run every game.',scene:'🎈  🎟️  🎪',missions:[
  {id:'spinner',title:'Make the spinner fair',story:'The prize wheel should give two colors equal chances.',steps:[{label:'Equal sections',prompt:'A wheel has 8 equal spaces. How many should be blue for a 1/2 chance?',choices:[['4',1],['2',0],['6',0]],explain:'Half of 8 is 4.',hints:['A fair half means half the spaces.','Half of 8 is 4.','So 4 blue spaces are needed.']},{label:'Chance',prompt:'3 winning spaces out of 12 gives what chance?',choices:[['1/4',1],['1/3',0],['3/4',0]],explain:'3/12 simplifies to 1/4.',hints:['Write wins over total: 3/12.','Divide both by 3.','That becomes 1/4.']},{label:'Fairness',prompt:'Which game is fairer if players should win half the time?',choices:[['5 wins out of 10',1],['4 wins out of 10',0]],explain:'5/10 is exactly one half.',hints:['Half of 10 is 5.','Compare each win count to 5.','5 out of 10 is exactly half.']}]},
  {id:'combos',title:'Build the prize booth',story:'Count every possible ticket-prize pairing.',steps:[{label:'Pairs',prompt:'3 ticket colors and 2 prizes make how many combinations?',choices:[['6',1],['5',0],['3',0]],explain:'3×2=6 combinations.',hints:['Each of 3 tickets can pair with each of 2 prizes.','That is 2 combinations per ticket color.','3×2=6.']},{label:'Add choice',prompt:'Add a third prize. Now 3 ticket colors × 3 prizes gives?',choices:[['9',1],['6',0],['12',0]],explain:'3×3=9 combinations.',hints:['There are now 3 choices in each set.','Pair each ticket with all 3 prizes.','3×3=9.']},{label:'Logic gate',prompt:'A ride opens only if BOTH safety switches are on. Which rule?',choices:[['AND',1],['OR',0]],explain:'AND requires both conditions.',hints:['The ride needs switch A and switch B.','Both must be true.','That is AND logic.']}]}
 ]},
 spaceport:{emoji:'🚀',name:'Valley Spaceport',tagline:'Launch missions using vectors, gravity, and orbital thinking.',scene:'🛰️  🌙  🚀',missions:[
  {id:'vector',title:'Plot the launch vector',story:'Combine horizontal and vertical pushes to reach the beacon.',steps:[{label:'Across',prompt:'Push 4 right and 3 up. What is the horizontal component?',choices:[['4',1],['3',0],['7',0]],explain:'The horizontal component is the 4-right push.',hints:['Separate the two directions.','Horizontal means left-right.','That component is 4.']},{label:'Up',prompt:'What is the vertical component?',choices:[['3',1],['4',0],['7',0]],explain:'The vertical component is the 3-up push.',hints:['Vertical means up-down.','The up push is 3.','So the vertical component is 3.']},{label:'Result',prompt:'Which coordinate does the ship reach from (0,0)?',choices:[['(4,3)',1],['(3,4)',0],['(7,0)',0]],explain:'Combining the components lands at (4,3).',hints:['Start at the origin.','Move 4 across and 3 up.','The new coordinate is (4,3).']}]},
  {id:'orbit',title:'Stabilize the satellite',story:'Balance speed and gravity to keep the satellite near the planet.',steps:[{label:'Too slow',prompt:'If the satellite moves too slowly, what tends to happen?',choices:[['It falls inward',1],['It escapes',0]],explain:'Too little sideways speed lets gravity pull it inward.',hints:['Gravity is always pulling toward the planet.','Sideways speed keeps the satellite from falling straight down.','Too little speed means it drops inward.']},{label:'Too fast',prompt:'If it moves much too fast?',choices:[['It can escape outward',1],['It falls straight down',0]],explain:'Too much speed can carry it away.',hints:['Now think about excessive sideways motion.','Gravity may not bend the path enough.','The satellite can move outward or escape.']},{label:'Orbit',prompt:'A stable orbit needs what balance?',choices:[['Sideways speed + gravity',1],['No gravity',0]],explain:'Orbit is continuous falling around a planet.',hints:['The satellite moves forward while gravity bends the path.','Neither effect works alone.','The balance creates orbit.']}]}
 ]}
};
const key=id=>`first-principles-building-${id}`;
const load=id=>{try{return JSON.parse(localStorage.getItem(key(id))||'{}')}catch{return {}}};


const rulerJobs=[
  {id:'half',label:'1" → halves',length:1,pieces:2,cuts:[.5],prompt:'Cut a 1-inch strip into 2 equal pieces.',result:'Each piece is 1/2 inch.'},
  {id:'quarters',label:'1" → quarters',length:1,pieces:4,cuts:[.25,.5,.75],prompt:'Cut a 1-inch strip into 4 equal pieces.',result:'Each piece is 1/4 inch.'},
  {id:'eighths',label:'1" → eighths',length:1,pieces:8,cuts:[.125,.25,.375,.5,.625,.75,.875],prompt:'Cut a 1-inch strip into 8 equal pieces.',result:'Each piece is 1/8 inch; the cut marks include 1/8, 3/8, 5/8, and 7/8.'},
  {id:'three-quarter-halves',label:'1 1/2" → two pieces',length:1.5,pieces:2,cuts:[.75],prompt:'Cut a 1 1/2-inch strip into 2 equal pieces.',result:'Each piece is 3/4 inch.'},
  {id:'seven-eighth-halves',label:'1 3/4" → two pieces',length:1.75,pieces:2,cuts:[.875],prompt:'Cut a 1 3/4-inch strip into 2 equal pieces.',result:'Each piece is 7/8 inch.'},
  {id:'two-half-halves',label:'2 1/2" → two pieces',length:2.5,pieces:2,cuts:[1.25],prompt:'Cut a 2 1/2-inch board into 2 equal pieces.',result:'Each piece is 1 1/4 inches.'},
  {id:'two-quarter-thirds',label:'2 1/4" → thirds',length:2.25,pieces:3,cuts:[.75,1.5],prompt:'Cut a 2 1/4-inch board into 3 equal pieces.',result:'Each piece is 3/4 inch.'},
  {id:'three-inch-quarters',label:'3" → four pieces',length:3,pieces:4,cuts:[.75,1.5,2.25],prompt:'Cut a 3-inch board into 4 equal pieces.',result:'Each piece is 3/4 inch, with cuts at 3/4, 1 1/2, and 2 1/4 inches.'}
];
const sameCuts=(a,b)=>a.length===b.length&&b.every(x=>a.some(y=>Math.abs(x-y)<.001));

function CarpentryRulerBench({onComplete,onStep}){
  const[jobIndex,setJobIndex]=useState(0),[cuts,setCuts]=useState([]),[note,setNote]=useState('Start by tapping a cut point directly on the board.'),[showHint,setShowHint]=useState(false),[solved,setSolved]=useState([]);
  const job=rulerJobs[jobIndex],step=.125,ticks=Array.from({length:Math.round(job.length/step)+1},(_,i)=>Number((i*step).toFixed(3))),possibleCuts=ticks.filter(v=>v>0&&v<job.length),requiredJobs=3;
  const toggle=value=>{setCuts(v=>v.some(x=>Math.abs(x-value)<.001)?v.filter(x=>Math.abs(x-value)>=.001):[...v,value].sort((a,b)=>a-b));setShowHint(false);setNote('Good — now compare the piece sizes.')};
  const correct=sameCuts(cuts,job.cuts);
  const chooseJob=i=>{setJobIndex(i);setCuts([]);setShowHint(false);setNote(solved.includes(rulerJobs[i].id)?'This cut is already verified. Try it again or choose another.':'Tap the board where the equal cuts belong.');onStep?.(i)};
  const check=()=>{
    if(!correct){setNote('Not quite equal yet. Compare the piece lengths and move your cut marks.');return}
    const nextSolved=solved.includes(job.id)?solved:[...solved,job.id];setSolved(nextSolved);setNote('✓ '+job.result);
    onStep?.(Math.min(2,nextSolved.length));
    if(nextSolved.length===requiredJobs)onComplete?.('Three cut jobs are verified. The ruler bench stays open for extra eighth-inch and mixed-number practice.');
    else{const next=rulerJobs.findIndex(x=>!nextSolved.includes(x.id));setTimeout(()=>chooseJob(next),450)}
  };
  const fractionLabel=v=>{const eighths=Math.round(v*8),whole=Math.floor(eighths/8),rem=eighths%8;if(!rem)return whole+'"';const g=rem%4===0?4:rem%2===0?2:1,num=rem/g,den=8/g,frac=num+'/'+den;return (whole?whole+' ':'')+frac+'"'};
  const boundaries=[0,...cuts,job.length],segments=boundaries.slice(0,-1).map((start,i)=>({start,end:boundaries[i+1],size:boundaries[i+1]-start}));
  return <section className="carpentryRulerBench intuitiveBench toolMission">
    <div className="carpentryToolHead"><div><small>MISSION TOOL</small><h3>Cut the Board</h3><p>{job.prompt}</p></div><div className="cutGoal"><small>GOAL</small><strong>{job.pieces} equal pieces</strong><span>{solved.length} solved · 3 needed for mission</span></div></div>
    <div className="rulerJobTabs">{rulerJobs.map((x,i)=><button key={x.id} className={(i===jobIndex?'active ':'')+(solved.includes(x.id)?'done':'')} onClick={()=>chooseJob(i)}>{solved.includes(x.id)?'✓ ':''}{x.label}</button>)}</div>
    <div className="rulerBenchSurface simpleRulerSurface"><div className="boardInstruction">👇 Tap a dashed line to make a cut</div><div className="boardAndRuler"><div className="woodBoard interactiveBoard"><span className="grain g1"/><span className="grain g2"/><span className="grain g3"/>{possibleCuts.map(v=>{const selected=cuts.some(x=>Math.abs(x-v)<.001),target=job.cuts.some(x=>Math.abs(x-v)<.001);return <button key={v} className={'boardCutTarget '+(selected?'selected ':'')+(showHint&&target?'hint ':'')} style={{left:(v/job.length*100)+'%'}} onClick={()=>toggle(v)}><i/><span>{fractionLabel(v)}</span></button>})}</div><div className="alignedRuler">{ticks.map(v=><span key={v} className={Number.isInteger(v)?'whole':Math.abs((v*2)%1)<.01?'half':Math.abs((v*4)%1)<.01?'quarter':'eighth'} style={{left:(v/job.length*100)+'%'}}><i/><b>{fractionLabel(v)}</b></span>)}</div></div><div className="pieceResultArea"><small>YOUR PIECES</small><div className="pieceSegments">{segments.map((seg,i)=><span key={i} style={{flex:seg.size}}><b>{fractionLabel(seg.size)}</b></span>)}</div><div className="pieceSummary"><strong>{segments.length} piece{segments.length===1?'':'s'}</strong><span>{correct?'All equal ✓':'Make every piece the same length.'}</span></div></div></div>
    <div className="carpentryActions guidedActions"><button onClick={()=>{setCuts([]);setShowHint(false);setNote('Board reset.')}} disabled={!cuts.length}>↶ Reset</button><button className="showCutHint" onClick={()=>{setShowHint(true);setNote('The glowing lines mark equal cut positions.')}}>💡 Show me</button><button className="carpentryCheck" onClick={check}>Verify this cut</button></div><p className={'carpentryNote '+(correct?'success':'')}>{note}</p>
  </section>
}

function SymmetryTrimBench({onComplete,onStep}){
  const[stage,setStage]=useState(0),[pos,setPos]=useState(null),[slats,setSlats]=useState(3),[brace,setBrace]=useState(null),[note,setNote]=useState('Mirror the first trim mark.');
  const advance=()=>{
    if(stage===0){if(pos!==2){setNote('The mirror mark must be the same distance from center.');return}setStage(1);onStep?.(1);setNote('Great. Now mirror the three slats onto both sides.');return}
    if(stage===1){if(slats!==6){setNote('Three slats on each mirrored side makes six total.');return}setStage(2);onStep?.(2);setNote('Last check: which piece can live on the symmetry line itself?');return}
    if(brace!=='center'){setNote('A piece exactly on the symmetry line mirrors onto itself.');return}
    setNote('✓ Symmetrical frame verified.');onComplete?.('The trim marks, paired slats, and center brace all preserve mirror symmetry.');
  };
  return <section className="symmetryTrimBench toolMission"><div className="woodshopToolMiniHead"><small>MISSION TOOL · {stage+1}/3</small><h3>Build the Symmetrical Frame</h3><p>{stage===0?'Place the matching cut 2 inches from center.':stage===1?'Set the total number of slats for two mirrored sides.':'Choose the piece that can sit on the symmetry line.'}</p></div>
    {stage===0&&<div className="symmetryFrame"><div className="frameCenterLine"><span>CENTER</span></div><div className="fixedTrim left"><b>-2"</b></div>{[1,2,3].map(v=><button key={v} className={pos===v?(v===2?'correct':'wrong'):''} style={{left:(50+v*13)+'%'}} onClick={()=>setPos(v)}><i/><span>+{v}"</span></button>)}</div>}
    {stage===1&&<div className="slatMirrorTool"><div>{Array.from({length:3},(_,i)=><i key={'l'+i}/>)}</div><span className="mirrorAxis">MIRROR</span><div>{Array.from({length:Math.max(0,slats-3)},(_,i)=><i key={'r'+i}/>)}</div><label>Total slats <input type="range" min="3" max="9" value={slats} onChange={e=>setSlats(+e.target.value)}/><b>{slats}</b></label></div>}
    {stage===2&&<div className="braceChoice"><button className={brace==='side'?'chosen':''} onClick={()=>setBrace('side')}>Side trim</button><button className={brace==='center'?'chosen correct':''} onClick={()=>setBrace('center')}>Center brace</button><button className={brace==='corner'?'chosen':''} onClick={()=>setBrace('corner')}>Corner block</button></div>}
    <button className="toolMissionAction" onClick={advance}>{stage<2?'Lock it in →':'Finish frame ✓'}</button><p className="toolMiniNote">{note}</p></section>
}

function FrameScaleBench({onComplete,onStep}){
  const[factor,setFactor]=useState(1),width=3*factor,length=4*factor,area=width*length,ready=factor===2;
  useEffect(()=>{onStep?.(ready?2:0)},[ready]);
  return <section className="frameScaleBench toolMission"><div className="woodshopToolMiniHead"><small>MISSION TOOL</small><h3>Scale the Workbench Frame</h3><p>Find the scale factor that makes every length double, then inspect what happens to area.</p></div><div className="scaleFactorButtons">{[1,2,3].map(v=><button key={v} className={factor===v?'active':''} onClick={()=>setFactor(v)}>{v}× scale</button>)}</div><div className="frameScaleVisual"><div className="scaleModelCard"><small>MODEL</small><div className="frameGrid original"><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/><i/></div><b>3 × 4</b><span>area = 12</span></div><div className="scaleArrow">× {factor} →</div><div className="scaleModelCard result"><small>BUILD</small><div className="frameGrid scaled" style={{width:(96+factor*22)+'px',height:(72+factor*18)+'px'}}/><b>{width} × {length}</b><span>area = {area}</span></div></div><div className="scaleRelationshipRow"><span className={width===6?'correct':''}><small>WIDTH</small><b>3 → {width}</b></span><span className={length===8?'correct':''}><small>LENGTH</small><b>4 → {length}</b></span><span className={area===48?'correct':''}><small>AREA</small><b>12 → {area}</b></span></div><button className="toolMissionAction" disabled={!ready} onClick={()=>onComplete?.('At 2× scale, every length doubles while area becomes four times as large.')}>{ready?'Use this 6 × 8 build ✓':'Find the double-scale build'}</button><p className="toolMiniNote">{ready?'All dimensions are correct: 6 × 8 with area 48.':'Change the scale factor and watch width, length, and area together.'}</p></section>
}

function BridgeLoadBench({onComplete,onStep}){
  const[stage,setStage]=useState(0),[weight,setWeight]=useState(2),[distance,setDistance]=useState(4),[side,setSide]=useState(null),[pivot,setPivot]=useState(42),[note,setNote]=useState('Balance the 4-unit load sitting 2 spaces left of the pivot.');
  const torque=weight*distance,target=8;
  const next=()=>{
    if(stage===0){if(torque!==target){setNote('Right torque must also equal 8. Try weight × distance.');return}setStage(1);onStep?.(1);setNote('Balanced. Now compare the stronger turning effects.');return}
    if(stage===1){if(side!=='left'){setNote('12 is greater than 10, so the left side has more torque.');return}setStage(2);onStep?.(2);setNote('Final check: place the pivot at the center.');return}
    if(pivot!==50){setNote('A symmetric deck needs its pivot at exactly 50%.');return}onComplete?.('You balanced torque, compared turning effects, and centered the pivot.');setNote('✓ Bridge system verified.');
  };
  return <section className="bridgeLoadBench toolMission"><div className="toolRoomHead"><small>BRIDGE CONTROL · {stage+1}/3</small><h3>{stage===0?'Balance the deck':stage===1?'Which side tips?':'Center the pivot'}</h3></div>
    {stage===0&&<><div className="bridgeBeamVisual" style={{transform:'rotate('+Math.max(-12,Math.min(12,(torque-target)*1.5))+'deg)'}}><span className="load left">4 × 2</span><i/><span className="load right">{weight} × {distance}</span></div><div className="toolSliderGrid"><label>Right weight <input type="range" min="1" max="8" value={weight} onChange={e=>setWeight(+e.target.value)}/><b>{weight}</b></label><label>Right distance <input type="range" min="1" max="8" value={distance} onChange={e=>setDistance(+e.target.value)}/><b>{distance}</b></label></div><div className="toolEquation">Left: 4 × 2 = 8 <strong>{torque===8?'=':'≠'}</strong> Right: {weight} × {distance} = {torque}</div></>}
    {stage===1&&<div className="torqueCompare"><button className={side==='left'?'chosen':''} onClick={()=>setSide('left')}><b>LEFT</b><span>3 × 4 = 12</span></button><button className={side==='right'?'chosen':''} onClick={()=>setSide('right')}><b>RIGHT</b><span>5 × 2 = 10</span></button></div>}
    {stage===2&&<div className="pivotTool"><div className="pivotDeck"><i style={{left:pivot+'%'}}/></div><label>Pivot position <input type="range" min="20" max="80" step="5" value={pivot} onChange={e=>setPivot(+e.target.value)}/><b>{pivot}%</b></label></div>}
    <button className="toolMissionAction" onClick={next}>{stage<2?'Check & continue →':'Approve bridge ✓'}</button><p className="toolMiniNote">{note}</p></section>
}

function ThinkTankBoard({mission,onComplete,onStep}){
  const[stage,setStage]=useState(0),[pick,setPick]=useState(null),[candidate,setCandidate]=useState(7),[note,setNote]=useState('Use the board, not a guess.');
  const configurations={
    analogy:[
      {prompt:'Bee needs the same relationship as bird → nest.',options:[['Hive','hive'],['Flower','flower'],['Wing','wing']],answer:'hive'},
      {prompt:'Password gives access to what, like key → lock?',options:[['Account','account'],['Keyboard','keyboard'],['Screen','screen']],answer:'account'},
      {prompt:'What is the shared relationship?',options:[['access / home relationship','relation'],['same color','color'],['same word length','length']],answer:'relation'}
    ],
    classification:[
      {prompt:'Select the odd one out.',options:[['△ triangle','triangle'],['□ square','square'],['▭ rectangle','rectangle'],['○ circle','circle']],answer:'circle'},
      {prompt:'Which number breaks the ×4 pattern?',options:[['8','8'],['12','12'],['16','16'],['18','18']],answer:'18'},
      {prompt:'A strong classification rule should be…',options:[['testable property','rule'],['whatever looks odd','odd'],['longest item','long']],answer:'rule'}
    ]
  };
  if(mission.id==='logic'){
    const constraints=stage===0?[candidate>5,candidate<10]:[candidate>5,candidate<10,candidate%2===1,candidate!==7],target=stage===0?7:9,ok=candidate===target;
    const next=()=>{if(!ok){setNote('The number must satisfy every lit clue at once.');return}if(stage<2){setStage(s=>s+1);onStep?.(stage+1);setCandidate(9);setNote(stage===0?'New clues added: odd and not 7.':'Notice how added constraints remove possibilities.')}else onComplete?.('You narrowed the solution set by keeping every constraint true at once.')};
    return <section className="thinkBoard toolMission"><div className="toolRoomHead"><small>PUZZLE BOARD · {stage+1}/3</small><h3>Constraint Safe</h3><p>Turn every clue green with one number.</p></div><div className="constraintLights">{['> 5','< 10','odd','not 7'].slice(0,constraints.length).map((x,i)=><span key={x} className={constraints[i]?'on':''}>{constraints[i]?'✓':'○'} {x}</span>)}</div><label className="numberDial">Mystery number <input type="range" min="0" max="12" value={candidate} onChange={e=>setCandidate(+e.target.value)}/><b>{candidate}</b></label><button className="toolMissionAction" onClick={next}>{stage<2?'Lock clue set →':'Open the safe ✓'}</button><p className="toolMiniNote">{note}</p></section>
  }
  const items=configurations[mission.id]||configurations.analogy,current=items[stage];
  const next=()=>{if(pick!==current.answer){setNote('That choice does not preserve the relationship/rule.');return}if(stage===2){onComplete?.('You solved all three reasoning transfers by using the relationship, not surface appearance.');setNote('✓ Puzzle wall unlocked.')}else{setStage(s=>s+1);onStep?.(stage+1);setPick(null);setNote('Good. Transfer the same reasoning habit to the next card.')}}
  return <section className="thinkBoard toolMission"><div className="toolRoomHead"><small>PUZZLE BOARD · {stage+1}/3</small><h3>{mission.title}</h3><p>{current.prompt}</p></div><div className="reasoningCards">{current.options.map(([label,id])=><button key={id} className={pick===id?'chosen':''} onClick={()=>setPick(id)}>{label}</button>)}</div><button className="toolMissionAction" onClick={next}>{stage<2?'Connect the clue →':'Unlock board ✓'}</button><p className="toolMiniNote">{note}</p></section>
}

function ObservatoryBench({mission,onComplete,onStep}){
  const[stage,setStage]=useState(0),[x,setX]=useState(4),[y,setY]=useState(4),[input,setInput]=useState(2),[reverse,setReverse]=useState(8),[note,setNote]=useState('Use the live sky instruments.');
  if(mission.id==='constellation'){
    const ok=stage===0?x===4&&y===4:stage===1?x===y:stage===2?x===7&&y===7:false;
    const next=()=>{if(!ok){setNote(stage===0?'Continue both coordinates by +1.':stage===1?'The rule is x = y. Keep them matched.':'Set x to 7 and preserve x = y.');return}if(stage<2){setStage(s=>s+1);onStep?.(stage+1);if(stage===0){setX(5);setY(5)}else{setX(7);setY(6)}setNote('Rule confirmed. Now use it again.')}else onComplete?.('You extended the constellation by preserving the x = y relationship.')};
    return <section className="observatoryBench toolMission"><div className="toolRoomHead"><small>STAR MAP · {stage+1}/3</small><h3>Map the Constellation</h3></div><div className="starGrid"><span style={{left:'18%',bottom:'18%'}}>✦</span><span style={{left:'34%',bottom:'34%'}}>✦</span><span style={{left:'50%',bottom:'50%'}}>✦</span><span className={ok?'target ok':'target'} style={{left:(10+x*10)+'%',bottom:(10+y*10)+'%'}}>✦</span></div><div className="toolSliderGrid"><label>x <input type="range" min="1" max="8" value={x} onChange={e=>setX(+e.target.value)}/><b>{x}</b></label><label>y <input type="range" min="1" max="8" value={y} onChange={e=>setY(+e.target.value)}/><b>{y}</b></label></div><button className="toolMissionAction" onClick={next}>{stage<2?'Plot & continue →':'Save constellation ✓'}</button><p className="toolMiniNote">{note}</p></section>
  }
  const output=input*2+1,reverseOutput=reverse*2+1,ok=stage===0?input===2:stage===1?input===8:reverse===10;
  const next=()=>{if(!ok){setNote(stage===0?'Start from one known pair: 2 → 5.':stage===1?'Set input 8 and apply ×2 +1.':'Find the input that produces 21.');return}if(stage<2){setStage(s=>s+1);onStep?.(stage+1);if(stage===0)setInput(8);else setReverse(9);setNote('Signal rule holds. Test it again.')}else onComplete?.('You identified ×2 + 1, predicted a new output, and reversed the rule.')};
  return <section className="observatoryBench toolMission"><div className="toolRoomHead"><small>SIGNAL CONSOLE · {stage+1}/3</small><h3>Decode the Satellite</h3></div>{stage<2?<><label className="numberDial">Input <input type="range" min="1" max="12" value={input} onChange={e=>setInput(+e.target.value)}/><b>{input}</b></label><div className="signalMachine"><span>{input}</span><i>×2 + 1</i><strong>{output}</strong></div></>:<><label className="numberDial">Which input makes 21? <input type="range" min="1" max="12" value={reverse} onChange={e=>setReverse(+e.target.value)}/><b>{reverse}</b></label><div className="signalMachine"><span>{reverse}</span><i>×2 + 1</i><strong>{reverseOutput}</strong></div></>}<button className="toolMissionAction" onClick={next}>{stage<2?'Run signal test →':'Lock signal rule ✓'}</button><p className="toolMiniNote">{note}</p></section>
}
export function NewBuildingInterior({buildingId,onExit}){
  const building=BUILDINGS[buildingId],[missionIndex,setMissionIndex]=useState(0),[step,setStep]=useState(0),[message,setMessage]=useState('Use the mission tool to begin.'),[completed,setCompleted]=useState(()=>load(buildingId)),[hintStep,setHintStep]=useState(0),[toolRun,setToolRun]=useState(0);
  const mission=building?.missions[missionIndex],current=mission?.steps[step],doneCount=Object.keys(completed).length;
  const customTool=['architect','bridge','think','observatory'].includes(buildingId);
  const progress=useMemo(()=>mission?completed[mission.id]?100:Math.round(step/Math.max(1,mission.steps.length)*100):0,[mission,step,completed]);
  useEffect(()=>{try{localStorage.setItem(key(buildingId),JSON.stringify(completed))}catch{}},[buildingId,completed]);
  if(!building)return null;
  const finishTool=text=>{setCompleted(v=>({...v,[mission.id]:true}));setStep(mission.steps.length);setMessage('Mission complete! '+text)};
  const choose=(ok,explain)=>{setHintStep(0);if(!ok){setMessage('Not quite. Look at the relationship and try again.');return}if(step===mission.steps.length-1){finishTool(explain)}else{setMessage(explain);setTimeout(()=>{setStep(s=>s+1);setMessage('Nice. Use that idea on the next control.')},350)}};
  const selectMission=i=>{setMissionIndex(i);setStep(0);setHintStep(0);setToolRun(v=>v+1);setMessage(completed[building.missions[i].id]?'You solved this mission already. Replay it or choose another.':'Use the mission tool to begin.')};
  const help=()=>{const hints=current?.hints||[];const next=Math.min(hintStep,hints.length-1);if(hints.length){setMessage('🛟 '+hints[next]);setHintStep(v=>Math.min(v+1,hints.length))}};
  const resetTool=()=>{setStep(0);setHintStep(0);setToolRun(v=>v+1);setMessage('Tool reset. Start the mission again.')};const replay=()=>{setStep(0);setToolRun(v=>v+1);setCompleted(v=>{const n={...v};delete n[mission.id];return n});setMessage('Mission reset. Use the tool to solve it again.')};
  const tool=!completed[mission.id]&&(
    buildingId==='architect'?(mission.id==='cuts'?<CarpentryRulerBench key={toolRun} onStep={setStep} onComplete={finishTool}/>:mission.id==='facade'?<SymmetryTrimBench key={toolRun} onStep={setStep} onComplete={finishTool}/>:<FrameScaleBench key={toolRun} onStep={setStep} onComplete={finishTool}/>)
    :buildingId==='bridge'?<BridgeLoadBench key={toolRun} onStep={setStep} onComplete={finishTool}/>
    :buildingId==='think'?<ThinkTankBoard key={mission.id+'-'+toolRun} mission={mission} onStep={setStep} onComplete={finishTool}/>
    :buildingId==='observatory'?<ObservatoryBench key={mission.id+'-'+toolRun} mission={mission} onStep={setStep} onComplete={finishTool}/>
    :null
  );
  return <div className={'newInterior '+buildingId+'Interior'}><header className="interiorHeader"><div><small>MY WORLD · INTERIOR</small><h1>{building.emoji} {building.name}</h1><p>{building.tagline}</p></div><button onClick={onExit}>← Back outside</button></header><div className="interiorScene"><div className="interiorBackdrop">{building.scene}</div><div className="interiorCounter"><b>{doneCount}/{building.missions.length} missions complete</b><span>Your completed missions are saved when you leave.</span></div></div><div className="interiorLayout"><aside className="missionShelf"><small>CHOOSE A MISSION</small>{building.missions.map((m,i)=><button key={m.id} className={i===missionIndex?'active':''} onClick={()=>selectMission(i)}><span>{completed[m.id]?'✅':i+1}</span><div><b>{m.title}</b><small>{completed[m.id]?'Complete':'Ready'}</small></div></button>)}</aside><section className="missionWorkbench"><div className="workbenchTop"><div><small>MISSION {missionIndex+1}</small><h2>{mission.title}</h2><p>{mission.story}</p></div><div className="missionGauge"><strong>{progress}%</strong><span>complete</span></div></div><div className="controlTrack">{mission.steps.map((s,i)=><div key={s.label} className={(i<step||completed[mission.id]?'done ':'')+(i===step&&!completed[mission.id]?'active':'')}><span>{i<step||completed[mission.id]?'✓':i+1}</span><b>{s.label}</b></div>)}</div>{completed[mission.id]?<div className="missionComplete"><span>🌟</span><h3>Mission accomplished!</h3><p>You used the idea across several connected steps.</p><button onClick={replay}>Replay mission</button></div>:customTool?<>{tool}<button className="toolResetButton" onClick={resetTool}>↻ Reset mission tool</button><p className="interiorFeedback">{message}</p></>:<><div className="challengeCard"><small>CONTROL {step+1} OF {mission.steps.length}</small><h3>{current.label}</h3><p>{current.prompt}</p><div className="answerDeck">{current.choices.map(([label,ok])=><button key={label} onClick={()=>choose(ok,current.explain)}>{label}</button>)}</div><button className="interiorHelp" onClick={help}>🛟 I’m stuck — walk me through it</button></div><p className="interiorFeedback">{message}</p></>}</section></div></div>
}