import React,{useEffect,useMemo,useState}from'react';
import'./worldConcept.css';
import'./worldConceptV2.css';
import{worldBuildings}from'./data/world';
import{unlockedOrderMeta}from'./data/worldOrders';
import{NewBuildingInterior}from'./newBuildingInteriors';

const activityIds={bakery:1,clinic:1,design:1,lab:1};
const newInteriorIds=new Set(['transit','architect','observatory']);
const shopSides=['left','right','left','right','left','right','left'];
const customerLooks=['🐰','🦊','🐼','🐶','🐱','🦝','🐻'];
const customerNames=['Mia','Theo','Pip','Luna','Nico','Zoe','Finn'];
const avatarFaces=['🧒','👧','👦','🧑'];
const avatarColors=['#6d5dfc','#22a06b','#e66c37','#ec4b7a','#2685d8','#8f5bc2'];
const avatarBackpacks=['🎒','👜','🧳','🎒'];
const AVATAR_KEY='first-principles-avatar-v1';
const defaultAvatar={name:'You',face:0,color:0,backpack:0};
const requestCopy={bakery:['I’m getting ready for a party and the bakery needs help with my order.','Can you help the baker make exactly what I need?'],clinic:['My pet needs some help at the Animal Clinic.','Can you help the clinic figure out what my pet needs?'],design:['I need a design for something special in town.','Can you help the Pattern Studio finish it?'],lab:['The Measurement Lab has a job for me.','Can you help them get the amounts exactly right?']};
const mastered=c=>Object.values(c||{}).filter(x=>x?.discovered||x?.transferred).length;
const loadAvatar=()=>{try{return {...defaultAvatar,...JSON.parse(localStorage.getItem(AVATAR_KEY)||'{}')}}catch{return defaultAvatar}};
const saveAvatar=a=>{try{localStorage.setItem(AVATAR_KEY,JSON.stringify(a))}catch{}};

function Avatar({avatar,large=false}){return <div className={`cwAvatar ${large?'large':''}`} style={{'--shirt':avatarColors[avatar.color]}}><span className="cwAvatarFace">{avatarFaces[avatar.face]}</span><span className="cwAvatarShirt">★</span><span className="cwAvatarPack">{avatarBackpacks[avatar.backpack]}</span></div>}
function BuildingArt({o}){return <><span className="cwBuildingArt"><i className="cwRoof"/><i className="cwFront"/><i className="cwAwning"/><b className="cwIcon">{o.b.emoji}</b><i className="cwWindow w1"/><i className="cwWindow w2"/><i className="cwDoor"/></span><strong className="cwBuildingLabel">{o.b.name}</strong></>}

export function GrowingWorldScene({world,completedLessons,onEnter,onChooseLot}){
 const placed=world?.placements||{},mastery=mastered(completedLessons),[inside,setInside]=useState(null),[lane,setLane]=useState(0),[distance,setDistance]=useState(0),[dialogue,setDialogue]=useState(null),[accepted,setAccepted]=useState(null),[questOpen,setQuestOpen]=useState(false),[mapOpen,setMapOpen]=useState(false),[avatarOpen,setAvatarOpen]=useState(false),[selfTalk,setSelfTalk]=useState(false),[avatar,setAvatar]=useState(loadAvatar);
 const buildings=useMemo(()=>Object.entries(placed).map(([lot,id],idx)=>({lot:+lot,id,b:worldBuildings.find(x=>x.id===id),side:shopSides[idx%shopSides.length],d:18+idx*17})).filter(x=>x.b),[placed]);
 const customers=useMemo(()=>{let n=0;return buildings.flatMap(shop=>{if(!activityIds[shop.id])return[];const pending=unlockedOrderMeta(shop.id,completedLessons).filter(o=>!world?.activities?.[shop.id]?.completedOrders?.[o.id]);return pending.slice(0,2).map((order,i)=>({id:`${shop.id}-${order.id}`,shopId:shop.id,shopName:shop.b.name,order,look:customerLooks[n%customerLooks.length],name:customerNames[n++%customerNames.length],d:shop.d-5-i*5,side:i%2?'right':'left'}))})},[buildings,world,completedLessons]);
 const visibleBuildings=buildings.map(x=>({...x,rel:x.d-distance})).filter(x=>x.rel>-8&&x.rel<92),visibleCustomers=customers.map(x=>({...x,rel:x.d-distance})).filter(x=>x.rel>-6&&x.rel<64);
 const closestCustomer=[...visibleCustomers].sort((a,b)=>Math.abs(a.rel)-Math.abs(b.rel))[0],closestBuilding=[...visibleBuildings].sort((a,b)=>Math.abs(a.rel)-Math.abs(b.rel))[0];
 const activeCustomer=closestCustomer&&Math.abs(closestCustomer.rel)<8?closestCustomer:null,activeBuilding=closestBuilding&&Math.abs(closestBuilding.rel)<9?closestBuilding:null,targetBuilding=accepted&&buildings.find(b=>b.id===accepted.shopId);
 const move=(side,forward)=>{setDialogue(null);setSelfTalk(false);setLane(v=>Math.max(-1,Math.min(1,v+side)));setDistance(v=>Math.max(0,Math.min(120,v+forward)))};
 const travel=o=>{setDistance(Math.max(0,o.d-5));setLane(o.side==='left'?-1:1);setMapOpen(false)};
 useEffect(()=>{const key=e=>{if(['INPUT','BUTTON','TEXTAREA'].includes(e.target.tagName))return;const k=e.key.toLowerCase();if(k==='arrowleft'||k==='a')move(-1,0);if(k==='arrowright'||k==='d')move(1,0);if(k==='arrowup'||k==='w')move(0,5);if(k==='arrowdown'||k==='s')move(0,-5);if(k==='m')setMapOpen(true)};window.addEventListener('keydown',key);return()=>window.removeEventListener('keydown',key)},[]);
 if(inside)return <NewBuildingInterior buildingId={inside} onExit={()=>setInside(null)}/>;
 const enter=id=>newInteriorIds.has(id)?setInside(id):onEnter(id),accept=c=>{setAccepted(c);setDialogue(null)},jumpToTarget=()=>targetBuilding&&travel(targetBuilding),updateAvatar=patch=>{const next={...avatar,...patch};setAvatar(next);saveAvatar(next)};
 return <div className="conceptWorld">
   <div className="cwSkyGlow"/><div className="cwMountains"/><div className="cwHills"/><span className="cwSun">☀️</span><span className="cwCloud c1">☁️</span><span className="cwCloud c2">☁️</span><span className="cwCloud c3">☁️</span>
   <div className="cwScene"><div className="cwRoad"/><div className="cwSidewalk left"/><div className="cwSidewalk right"/><div className="cwTownCenter"><span>🏫</span><b>Learning Valley</b></div><div className="cwFountain">⛲</div>
     <span className="cwTree t1">🌳</span><span className="cwTree t2">🌲</span><span className="cwTree t3">🌳</span><span className="cwTree t4">🌲</span><span className="cwTree t5">🌳</span><span className="cwTree t6">🌳</span>
     <span className="cwLamp l1">🏮</span><span className="cwLamp l2">🏮</span><span className="cwLamp l3">🏮</span><span className="cwLamp l4">🏮</span><span className="cwFlower f1">🌼</span><span className="cwFlower f2">🌻</span><span className="cwFlower f3">🌷</span><span className="cwFlower f4">🌸</span><span className="cwBench b1">🪑</span><span className="cwBench b2">🪑</span>
     {visibleBuildings.map(o=>{const depth=Math.max(.38,1-o.rel/110),bottom=16+(1-depth)*30,x=o.side==='left'?8+depth*15:92-depth*15,target=accepted?.shopId===o.id;return <button key={`${o.lot}-${o.id}`} className={`cwBuilding ${o.id} ${target?'destination':''}`} style={{left:`${x}%`,bottom:`${bottom}%`,transform:`translateX(-50%) scale(${depth})`,zIndex:20+Math.round(depth*70)}} onClick={()=>travel(o)}><BuildingArt o={o}/>{target&&<small>YOUR DESTINATION</small>}</button>})}
     {visibleCustomers.map(c=>{const depth=Math.max(.48,1-c.rel/80),bottom=15+(1-depth)*28,x=c.side==='left'?32-depth*7:68+depth*7,near=activeCustomer?.id===c.id;return <button key={c.id} className={`cwCustomer ${near?'near':''}`} style={{left:`${x}%`,bottom:`${bottom}%`,transform:`translateX(-50%) scale(${depth})`,zIndex:45+Math.round(depth*65)}} onClick={()=>{setDistance(Math.max(0,c.d-2));setLane(c.side==='left'?-1:1);setDialogue(c)}}><span className="shadow"/><span className="sprite">{c.look}</span>{near&&<span className="cwTalkBubble">💬 Talk</span>}</button>})}
     <button className="cwPlayer" onClick={()=>setSelfTalk(true)} aria-label="Talk to your character"><Avatar avatar={avatar}/></button>
   </div>
   <div className="cwHud"><button className="cwProfile" onClick={()=>setSelfTalk(true)}><Avatar avatar={avatar}/><div><small>{avatar.name.toUpperCase()}</small><b>Explorer · Lv. {1+Math.floor(mastery/2)}</b></div></button><div className="cwStats"><span>⭐ {mastery}</span><span>🪙 {world?.coins??''}</span></div></div>
   <button className="cwMiniMap" onClick={()=>setMapOpen(true)}><div className="river"/><span className="cwMiniPlayer" style={{top:`${77-Math.min(66,distance*.55)}%`}}>●</span>{buildings.slice(0,5).map((o,i)=><span key={o.id} className="cwMiniDot" style={{left:`${20+(i%3)*28}%`,top:`${17+Math.floor(i/3)*34}%`}}>{o.b.emoji}</span>)}<b>MAP</b></button>
   {accepted&&<div className="cwOrder"><span>{accepted.look}</span><div><small>ACTIVE ORDER · {accepted.name}</small><b>{accepted.order.label}</b><p>Head to {accepted.shopName}.</p></div><button onClick={jumpToTarget}>Show me →</button></div>}
   <div className="cwControls"><button onClick={()=>move(0,5)}>▲</button><div><button onClick={()=>move(-1,0)}>◀</button><button onClick={()=>move(0,-5)}>▼</button><button onClick={()=>move(1,0)}>▶</button></div><small>WALK</small></div>
   <div className="cwDock"><button onClick={()=>setAvatarOpen(true)}>👕<span>My Look</span></button><button onClick={()=>setMapOpen(true)}>🗺️<span>Map</span></button><button onClick={()=>setQuestOpen(true)}>📋<span>Jobs {customers.length}</span></button></div>
   <div className="cwHint">Walk the road · open the map to see the whole world · tap your person to talk</div>
   {(activeCustomer||activeBuilding)&&!dialogue&&!selfTalk&&<div className="cwContext">{activeCustomer?<><span>{activeCustomer.look}</span><div><small>NEARBY</small><b>{activeCustomer.name}</b><p>Looks like they need some help.</p></div><button onClick={()=>setDialogue(activeCustomer)}>Talk</button></>:<><span>{activeBuilding.b.emoji}</span><div><small>YOU’RE HERE</small><b>{activeBuilding.b.name}</b><p>{accepted?.shopId===activeBuilding.id?'This is where your customer needs help.':'Step inside and see what is happening.'}</p></div><button onClick={()=>enter(activeBuilding.id)}>Go inside →</button></>}</div>}
   {dialogue&&<div className="cwModal cwDialogue"><button className="cwClose" onClick={()=>setDialogue(null)}>×</button><div className="cwDialogueNpc"><span>{dialogue.look}</span><b>{dialogue.name}</b></div><div className="cwDialogueText"><small>CUSTOMER REQUEST</small><h2>{dialogue.order.label}</h2><p>“{requestCopy[dialogue.shopId]?.[0]||'I need some help in town.'} {requestCopy[dialogue.shopId]?.[1]||'Can you help me?'}”</p><div className="cwDestination"><span>{dialogue.shopName}</span><strong>{dialogue.order.label}</strong></div><button className="cwPrimary" onClick={()=>accept(dialogue)}>I’ll help! →</button></div></div>}
   {selfTalk&&<div className="cwModal cwSelf"><button className="cwClose" onClick={()=>setSelfTalk(false)}>×</button><Avatar avatar={avatar} large/><div><small>YOUR EXPLORER</small><h2>Hey, {avatar.name}!</h2><p>“We can explore anywhere in Learning Valley. Open the map if you want to see the whole town, or change how I look whenever you want.”</p><div className="cwSelfActions"><button onClick={()=>{setSelfTalk(false);setMapOpen(true)}}>Open full map 🗺️</button><button onClick={()=>{setSelfTalk(false);setAvatarOpen(true)}}>Change my look 👕</button></div></div></div>}
   {mapOpen&&<div className="cwModal"><button className="cwClose" onClick={()=>setMapOpen(false)}>×</button><small>FULL WORLD MAP</small><h2>Where do you want to go?</h2><p>Tap a built place to travel there, or choose open land to build.</p><div className="cwFullMap"><div className="river"/><div className="path p1"/><div className="path p2"/><div className="path p3"/>{buildings.map((o,i)=><button key={o.id} className="cwMapPlace" style={{left:`${14+(i%3)*34}%`,top:`${16+Math.floor(i/3)*29}%`}} onClick={()=>travel(o)}><span>{o.b.emoji}</span><b>{o.b.name}</b><small>Travel here →</small></button>)}<span className="cwMapYou" style={{left:`${48+lane*7}%`,top:`${82-Math.min(62,distance*.5)}%`}}>📍<b>You are here</b></span></div></div>}
   {avatarOpen&&<div className="cwModal cwAvatarModal"><button className="cwClose" onClick={()=>setAvatarOpen(false)}>×</button><div className="cwAvatarPreview"><small>CUSTOMIZE YOUR PERSON</small><Avatar avatar={avatar} large/><input value={avatar.name} maxLength={12} onChange={e=>updateAvatar({name:e.target.value||'You'})}/></div><div className="cwAvatarChoices"><label>FACE</label><div>{avatarFaces.map((x,i)=><button key={x} className={avatar.face===i?'selected':''} onClick={()=>updateAvatar({face:i})}>{x}</button>)}</div><label>SHIRT</label><div>{avatarColors.map((x,i)=><button key={x} className={`cwColor ${avatar.color===i?'selected':''}`} style={{background:x}} onClick={()=>updateAvatar({color:i})}/>)}</div><label>BACKPACK</label><div>{avatarBackpacks.map((x,i)=><button key={`${x}-${i}`} className={avatar.backpack===i?'selected':''} onClick={()=>updateAvatar({backpack:i})}>{x}</button>)}</div><button className="cwPrimary" onClick={()=>setAvatarOpen(false)}>Save my look ✓</button></div></div>}
   {questOpen&&<div className="cwModal"><button className="cwClose" onClick={()=>setQuestOpen(false)}>×</button><small>TOWN JOBS</small><h2>Who needs help?</h2><div className="cwJobs">{customers.length?customers.map(c=><button key={c.id} className="cwJob" onClick={()=>{setQuestOpen(false);setDistance(Math.max(0,c.d-2));setLane(c.side==='left'?-1:1);setDialogue(c)}}><span>{c.look}</span><div><b>{c.name} · {c.order.label}</b><p>{c.shopName}</p></div><em>Go →</em></button>):<p>All current jobs are complete. Keep learning to unlock more town work.</p>}</div></div>}
 </div>
}
