import React,{useState}from'react';
import'./worldHubs.css';

const venueMeta={
clinic:{sign:'🐾 ANIMAL CLINIC 🩺',empty:'The clinic is quiet right now.',decor:'clinicDecor',verb:'patients helped'},
studio:{sign:'🎨 PATTERN STUDIO ✂️',empty:'No design requests are waiting.',decor:'studioDecor',verb:'projects finished'},
lab:{sign:'🧪 MEASUREMENT LAB 🔬',empty:'No experiments are waiting.',decor:'labDecor',verb:'experiments completed'}
};
const unlocked=(o,completed)=>!o.unlockAfter||Boolean(completed?.[o.unlockAfter]?.discovered);

function HubShell({kind,title,subtitle,emoji,orders,activity,onProgress,onExit,completedLessons={},children}){const available=orders.filter(o=>unlocked(o,completedLessons)),completed=activity?.completedOrders||{},waiting=available.filter(o=>!completed[o.id]),done=available.length-waiting.length,[selectedId,setSelectedId]=useState(waiting[0]?.id||available[0]?.id),order=available.find(o=>o.id===selectedId)||waiting[0]||available[0],meta=venueMeta[kind];const finish=id=>{if(!completed[id])onProgress({completedOrders:{...completed,[id]:true}})};const allDone=waiting.length===0;return <main className="app"><header className={`hero hubHero ${kind}Hero`}><div><small>{title}</small><h1>{emoji} {subtitle}</h1><p>Requests become real missions as your skills grow. Later jobs combine several ideas before they are complete.</p></div><button className="secondary" onClick={onExit}>← Back to My World</button></header><section className="bakeryStatus panel"><div><span className="hubStatusIcon">{kind==='clinic'?'🐾':kind==='studio'?'🎨':'🧪'}</span><b>{waiting.length} waiting · {done} complete</b></div><div className="bakeryUpgrade"><span>{allDone?'🏆':'✨'}</span><div><b>{allDone?'Everything is caught up!':'New work is waiting'}</b><small>{allDone?'Return after more learning to see what changes.':'Higher-level requests use several connected decisions — not one quick answer.'}</small></div></div></section><section className="bakeryLayout"><aside className={`panel hubVenue ${kind}Venue`}><div className="venueSign">{meta.sign}</div><div className="venueScene"><div className="venueWindowTop">{waiting.length?<div className="venueWaiting">{waiting.map(o=><button key={o.id} className={`venueCustomer ${order?.id===o.id?'active':''}`} onClick={()=>setSelectedId(o.id)}><span>{o.avatar}</span><div><b>{o.customer}</b><small>{o.title}</small>{o.level&&<em>Level {o.level}{o.level>=2?' · mission':''}</em>}</div></button>)}</div>:<div className="venueEmpty"><span>{kind==='clinic'?'🪟':kind==='studio'?'🖼️':'🔬'}</span><b>{meta.empty}</b><small>Head back to lessons. New requests will arrive as new skills are mastered.</small></div>}</div><div className={`venueCounter ${meta.decor}`}/></div><div className="venueTally">✅ {done} {meta.verb}</div></aside><section className="panel bakeryCounter hubWorkArea">{order?<><div className="customerBubble"><span>{order.avatar}</span><div><small>{order.customer}'s request {order.level?`· Level ${order.level}`:''}</small><h2>{order.title}</h2><p>{order.prompt}</p></div></div>{children(order,finish)}{completed[order.id]&&<div className="successNote">Request complete! Choose another waiting request.</div>}</>:<div className="emptyBakery"><span>{emoji}</span><h2>Everything is complete.</h2><p>New work will appear here as more concepts are mastered.</p></div>}</section></section></main>}

function Mission({order,onDone}){const[stage,setStage]=useState(0),[value,setValue]=useState(0),[message,setMessage]=useState('Complete control 1 to begin the mission.'),[helpOpen,setHelpOpen]=useState(false),[helpStep,setHelpStep]=useState(0),control=order.controls[stage],finished=stage>=order.controls.length;const walkthrough=[{title:'1. What do we know?',text:control.prompt},{title:'2. What idea should I use?',text:control.hint||'Look for the relationship between the numbers in the request.'},{title:'3. Put it together',text:`Set this control to ${control.target} ${control.unit}. Then lock the control and move to the next part.`}];const check=()=>{if(value!==control.target){setMessage(control.hint||'That control is not ready. Use the information in the mission and adjust it.');return}if(stage===order.controls.length-1){setMessage(order.success);onDone(order.id);return}setStage(s=>s+1);setValue(0);setHelpOpen(false);setHelpStep(0);setMessage(`${control.label} locked! The next control is live.`)};if(finished)return null;return <div className="worldMission"><div className="missionProgress">{order.controls.map((c,i)=><div key={c.label} className={`missionNode ${i<stage?'done':i===stage?'active':''}`}><span>{i<stage?'✓':c.icon}</span><b>{c.label}</b><small>{i<stage?'Locked':i===stage?'Active':'Waiting'}</small></div>)}</div><div className="missionScene"><div className="missionSceneArt">{control.art}</div><div className="missionBrief"><small>CONTROL {stage+1} OF {order.controls.length}</small><h3>{control.icon} {control.label}</h3><p>{control.prompt}</p></div><div className="missionDial"><button onClick={()=>setValue(v=>Math.max(0,v-1))}>−</button><div><strong>{value}</strong><small>{control.unit}</small></div><button onClick={()=>setValue(v=>Math.min(control.max||40,v+1))}>+</button></div><div className="missionMeter"><i style={{width:`${Math.min(100,(value/(control.max||40))*100)}%`}}/></div></div>{helpOpen&&<div className="walkthroughCard"><div className="walkthroughCoach">🧠</div><div className="walkthroughBody"><small>QUICK WALKTHROUGH · STEP {helpStep+1} OF {walkthrough.length}</small><h4>{walkthrough[helpStep].title}</h4><p>{walkthrough[helpStep].text}</p><div className="walkthroughActions"><button className="secondary" onClick={()=>{setHelpOpen(false);setHelpStep(0)}}>I can try now</button>{helpStep<walkthrough.length-1&&<button className="walkthroughNext" onClick={()=>setHelpStep(s=>s+1)}>Show next step →</button>}</div></div></div>}<div className="missionActions"><button className="stuckButton" onClick={()=>{setHelpOpen(true);setHelpStep(0)}}>🛟 I’m stuck — walk me through it</button><button className="primary missionLock" onClick={check}>{stage===order.controls.length-1?'Complete mission':'Lock control'}</button></div><p className="feedback">{message}</p></div>}

const CLINIC=[
{id:'food-half',customer:'Biscuit',avatar:'🐶',title:'Half a bowl',prompt:'Biscuit needs exactly half of the 8 food scoops.',type:'count',target:4,max:8,level:1},
{id:'weight-sort',customer:'Mochi',avatar:'🐱',title:'Choose the light supplies',prompt:'Tap every supply that weighs less than 5 kg.',type:'sort',level:1},
{id:'water-three-fourths',customer:'Pip',avatar:'🐰',title:'Fill the water bowl',prompt:'Pip needs the bowl exactly 3/4 full.',type:'fill',target:3,level:1},
{id:'clinic-scale-blanket',unlockAfter:'scale-robot',customer:'Finn',avatar:'🦊',title:'Build Finn a bigger blanket',prompt:'Finn outgrew a 2 × 3 blanket. Build a new one at double scale, then check how much fabric it needs.',type:'mission',level:2,controls:[{label:'Width',icon:'↔️',art:'🦊 🟦🟦',prompt:'The old blanket is 2 squares wide. Double the width.',target:4,max:8,unit:'squares',hint:'Double means two copies of the old width.'},{label:'Length',icon:'↕️',art:'🟦\n🟦\n🟦',prompt:'The old blanket is 3 squares long. Double the length.',target:6,max:10,unit:'squares',hint:'Two groups of 3 make the new length.'},{label:'Fabric',icon:'🧵',art:'▦',prompt:'Your new blanket is 4 × 6. How many square pieces of fabric cover it?',target:24,max:30,unit:'squares',hint:'Think rows × squares in each row.'}],success:'Finn’s 4 × 6 blanket is ready — scaling both dimensions made 24 square pieces of fabric!'},
{id:'clinic-walk-rate',unlockAfter:'race-rate',customer:'Mochi',avatar:'🐱',title:'Plan Mochi’s recovery walk',prompt:'Mochi walks at a steady pace. Set her pace, predict the route, then plan the full out-and-back walk.',type:'mission',level:3,controls:[{label:'Find pace',icon:'🐾',art:'🐱 · · · · · ·',prompt:'Mochi walks 6 spaces in 3 seconds. How many spaces each second?',target:2,max:6,unit:'spaces/sec',hint:'Split 6 spaces equally across 3 seconds.'},{label:'Reach park',icon:'🌳',art:'🐱 ───── 🌳',prompt:'At 2 spaces each second, how far in 5 seconds?',target:10,max:15,unit:'spaces',hint:'Five seconds means five groups of the pace.'},{label:'Round trip',icon:'🏠',art:'🏠 ← 🐱 → 🌳',prompt:'The park is 10 spaces away. How many spaces for there AND back?',target:20,max:25,unit:'spaces',hint:'The return trip is the same distance again.'}],success:'Walk planned! You used a rate to predict a route and a round trip.'}
];
function ClinicTask({order,onDone}){const[n,setN]=useState(0),[picked,setPicked]=useState([]),[msg,setMsg]=useState('Help the patient.');if(order.type==='mission')return <Mission order={order} onDone={onDone}/>;if(order.type==='sort'){const items=[['🪶 1 kg',true],['🥕 2 kg',true],['🧺 6 kg',false],['📦 8 kg',false]];const check=()=>{const ok=picked.length===2&&picked.includes(0)&&picked.includes(1);ok?(setMsg('Yes — both selected supplies are under 5 kg.'),onDone(order.id)):setMsg('Look at each weight. Select every supply that is less than 5 kg.')};return <><div className="hubTiles">{items.map((x,i)=><button key={i} className={picked.includes(i)?'chosen':''} onClick={()=>setPicked(v=>v.includes(i)?v.filter(k=>k!==i):[...v,i])}>{x[0]}</button>)}</div><button className="primary" onClick={check}>Check my choices</button><p className="feedback">{msg}</p></>};const target=order.type==='fill'?3:order.target,max=order.type==='fill'?4:order.max,icon=order.type==='fill'?'💧':'🥣';const check=()=>n===target?(setMsg(order.type==='fill'?'Three of four parts makes 3/4.':'Half of 8 is 4.'),onDone(order.id)):setMsg(`You have ${n}. Try again.`);return <><div className="hubCounter"><button onClick={()=>setN(v=>Math.max(0,v-1))}>−</button><div><span>{icon.repeat(n)||'—'}</span><b>{n} of {max}</b></div><button onClick={()=>setN(v=>Math.min(max,v+1))}>+</button></div><button className="primary" onClick={check}>Check care request</button><p className="feedback">{msg}</p></>}
export function AnimalClinic(props){return <HubShell {...props} kind="clinic" title="Animal Clinic" subtitle="Care for animals with numbers." emoji="🐾" orders={CLINIC}>{(o,f)=><ClinicTask key={o.id} order={o} onDone={f}/>}</HubShell>}

const STUDIO=[
{id:'stripe',customer:'Ari',avatar:'🧑‍🎨',title:'Finish the mural',prompt:'Continue the repeating red-blue-red-blue design.',type:'sequence',seq:['🔴','🔵','🔴','🔵'],answer:'🔴',choices:['🔴','🔵','🟡'],level:1},
{id:'grow',customer:'Zoe',avatar:'👧',title:'Growing tile design',prompt:'The design grows 1, 2, 3... What size comes next?',type:'sequence',seq:['■','■■','■■■'],answer:'■■■■',choices:['■■','■■■■','■■■■■'],level:1},
{id:'make',customer:'Kai',avatar:'🧒',title:'Design your own repeat',prompt:'Build an A-B-A-B pattern for a new floor.',type:'make',level:1},
{id:'studio-slope-roof',unlockAfter:'slope-mountain',customer:'Ari',avatar:'🧑‍🎨',title:'Engineer the festival roof',prompt:'The festival stage needs a roof with the same safe steepness all the way across. Tune three connected dimensions.',type:'mission',level:3,controls:[{label:'Simplify slope',icon:'📐',art:'／',prompt:'The reference roof rises 3 for every 6 across. What is the rise for every 2 across?',target:1,max:5,unit:'rise',hint:'3 over 6 has the same steepness as 1 over 2.'},{label:'Scale roof',icon:'🏠',art:'🏠',prompt:'A wider roof runs 8 across at the same steepness. How high should it rise?',target:4,max:10,unit:'rise',hint:'The roof rises 1 for every 2 across.'},{label:'Double span',icon:'🏗️',art:'🏠──🏠',prompt:'Double the 8-wide roof to a run of 16. Keep the same slope. What rise?',target:8,max:18,unit:'rise',hint:'When the run doubles, the rise doubles too.'}],success:'Roof approved — all three sizes preserve exactly the same slope.'},
{id:'studio-rule-sign',unlockAfter:'build-function-rule',customer:'Zoe',avatar:'👧',title:'Program the light-up sign',prompt:'The sign uses one hidden rule for every number. Decode it, then program two new panels.',type:'mission',level:3,controls:[{label:'Decode +',icon:'⚙️',art:'2 → 5   4 → 9',prompt:'The machine doubles the input, then adds how many?',target:1,max:6,unit:'added',hint:'Double 2 gives 4. What gets from 4 to 5?'},{label:'Panel 6',icon:'💡',art:'6 → ?',prompt:'Use the same rule: double 6, then add 1.',target:13,max:20,unit:'output',hint:'First make 12, then apply the final +1.'},{label:'Panel 10',icon:'✨',art:'10 → ?',prompt:'Prove the rule works again for input 10.',target:21,max:25,unit:'output',hint:'Double 10, then add the same 1.'}],success:'Sign programmed! You used one function rule consistently across new inputs.'}
];
function StudioTask({order,onDone}){const[msg,setMsg]=useState('Find the design rule.'),[made,setMade]=useState([]);if(order.type==='mission')return <Mission order={order} onDone={onDone}/>;if(order.type==='sequence')return <><div className="studioSequence">{order.seq.map((x,i)=><span key={i}>{x}</span>)}<span>?</span></div><div className="hubTiles">{order.choices.map(x=><button key={x} onClick={()=>x===order.answer?(setMsg('You found the rule and transferred it to the studio job!'),onDone(order.id)):setMsg('That changes the relationship. Compare the examples again.')}>{x}</button>)}</div><p className="feedback">{msg}</p></>;const add=x=>setMade(v=>v.length<4?[...v,x]:v),check=()=>made.join('')==='🔶🔷🔶🔷'?(setMsg('You created your own repeating rule!'),onDone(order.id)):setMsg('Try making orange, blue, orange, blue.');return <><div className="studioSequence">{made.map((x,i)=><span key={i}>{x}</span>)}{Array.from({length:4-made.length},(_,i)=><span key={'e'+i}>?</span>)}</div><div className="hubTiles"><button onClick={()=>add('🔶')}>🔶</button><button onClick={()=>add('🔷')}>🔷</button><button onClick={()=>setMade([])}>Reset</button></div><button className="primary" onClick={check}>Show my design</button><p className="feedback">{msg}</p></>}
export function PatternStudio(props){return <HubShell {...props} kind="studio" title="Pattern Studio" subtitle="Create designs from hidden rules." emoji="🎨" orders={STUDIO}>{(o,f)=><StudioTask key={o.id} order={o} onDone={f}/>}</HubShell>}

const LAB=[
{id:'half',customer:'Dr. Nova',avatar:'🥼',title:'Half-full sample',prompt:'Fill the sample tube to 1/2.',target:2,total:4,type:'measure',level:1},
{id:'threequarters',customer:'Dr. Nova',avatar:'🥼',title:'Three-quarter sample',prompt:'Fill the sample tube to 3/4.',target:3,total:4,type:'measure',level:1},
{id:'double',customer:'Rex',avatar:'🤖',title:'Double the recipe',prompt:'A test needs 2 scoops. Make a double batch.',target:4,total:6,type:'measure',level:1},
{id:'lab-scale-reading',unlockAfter:'map-scale',customer:'Dr. Nova',avatar:'🥼',title:'Calibrate the scale scanner',prompt:'The scanner turns model units into real units. Calibrate it, then predict two readings.',type:'mission',level:2,controls:[{label:'Find scale',icon:'🔎',art:'3 model → 12 real',prompt:'How many real units does each 1 model unit represent?',target:4,max:8,unit:'× scale',hint:'Split 12 real units into 3 equal model units.'},{label:'Read 5',icon:'📡',art:'5 model → ?',prompt:'Use the scale factor on a model reading of 5.',target:20,max:25,unit:'real units',hint:'Five groups of 4.'},{label:'Verify 7',icon:'✅',art:'7 model → ?',prompt:'Verify the calibration with a model reading of 7.',target:28,max:32,unit:'real units',hint:'Seven groups of the same scale factor.'}],success:'Scanner calibrated — the ×4 relationship held for every reading.'},
{id:'lab-machine-rule',unlockAfter:'mystery-machine',customer:'Rex',avatar:'🤖',title:'Repair Rex’s number machine',prompt:'Rex’s machine must follow one rule every time. Diagnose the rule and run two test inputs.',type:'mission',level:3,controls:[{label:'Find offset',icon:'⚙️',art:'1→3   2→5   3→7',prompt:'The machine doubles each input, then adds how many?',target:1,max:5,unit:'added',hint:'Double 1 is 2. What turns 2 into 3?'},{label:'Test 6',icon:'🧪',art:'6 → ?',prompt:'Run input 6 through double, then +1.',target:13,max:18,unit:'output',hint:'Double 6 first.'},{label:'Stress test',icon:'🤖',art:'10 → ?',prompt:'One last test: what should input 10 produce?',target:21,max:25,unit:'output',hint:'Use exactly the same rule — no guessing.'}],success:'Rex is repaired! The same rule survived every test.'}
];
function LabTask({order,onDone}){const[n,setN]=useState(0),[msg,setMsg]=useState('Adjust the sample.');if(order.type==='mission')return <Mission order={order} onDone={onDone}/>;const check=()=>n===order.target?(setMsg('Measurement confirmed!'),onDone(order.id)):setMsg(`The sample is at ${n} parts. Adjust it to ${order.target}.`);return <><div className="labTube"><div style={{height:`${n/order.total*100}%`}}/><b>{n}/{order.total}</b></div><div className="stepper"><button onClick={()=>setN(v=>Math.max(0,v-1))}>−</button><button onClick={()=>setN(v=>Math.min(order.total,v+1))}>+</button></div><button className="primary" onClick={check}>Run experiment</button><p className="feedback">{msg}</p></>}
export function MeasurementLab(props){return <HubShell {...props} kind="lab" title="Measurement Lab" subtitle="Run experiments by measuring precisely." emoji="🧪" orders={LAB}>{(o,f)=><LabTask key={o.id} order={o} onDone={f}/>}</HubShell>}
