import React,{useMemo,useState}from'react';
import{orderUnlocked}from'./data/worldOrders';

const ORDERS=[
{id:'pizza-three-fourths',customer:'Maya',avatar:'🧒',title:'Three-fourths pizza',prompt:'Maya wants cheese on exactly 3 of the 4 slices.',type:'slices',target:3,total:4,success:'Perfect — 3 of 4 slices is 3/4.'},
{id:'half-cup',customer:'Leo',avatar:'🧑',title:'Half-cup recipe',prompt:'Leo needs exactly 1/2 cup of milk. Each scoop is 1/4 cup.',type:'scoops',target:.5,step:.25,success:'Two quarter-cup scoops make one half cup.'},
{id:'share-cookies',customer:'Nina',avatar:'👧',title:'Share the cookies',prompt:'Nina has 8 cookies and wants to give 1/2 of them to a friend. Put the right number on the tray.',type:'count',target:4,max:8,success:'Exactly right — half of 8 is 4.'},
{id:'bakery-ratio-batch',unlockAfter:'ratio-recipe-3-2',customer:'Sam',avatar:'👦',title:'Party cupcake ratio',prompt:'A party box needs 3 chocolate cupcakes for every 2 vanilla. Build one perfect batch.',type:'ratio',targetA:3,targetB:2,success:'Perfect — 3 chocolate to 2 vanilla keeps the recipe ratio.'},
{id:'bakery-best-deal',unlockAfter:'unit-price',customer:'Ava',avatar:'👧',title:'Buy the best berry deal',prompt:'The bakery needs berries. Which supplier costs less for each basket?',type:'deal',choices:['4 baskets for 8 coins','3 baskets for 9 coins'],correct:0,success:'Right — the first supplier costs 2 coins per basket instead of 3.'}
];
function SliceOrder({order,onComplete}){const[cells,setCells]=useState(Array(order.total).fill(false)),[message,setMessage]=useState('Tap slices to add cheese.');const count=useMemo(()=>cells.filter(Boolean).length,[cells]);const check=()=>count===order.target?(setMessage(order.success),onComplete(order.id)):setMessage(count<order.target?`You have ${count} cheesy slices. Add ${order.target-count} more.`:`You have ${count}. Take cheese off ${count-order.target}.`);return <><div className="bakeryPizza">{cells.map((on,i)=><button key={i} className={on?'pizzaSlice selected':'pizzaSlice'} onClick={()=>setCells(v=>v.map((x,j)=>j===i?!x:x))}>{on?'🧀':'🍕'}</button>)}</div><button className="primary" onClick={check}>Serve this pizza</button><p className="feedback">{message}</p></>}
function ScoopOrder({order,onComplete}){const[amount,setAmount]=useState(0),[message,setMessage]=useState('Add quarter-cup scoops.');const check=()=>amount===order.target?(setMessage(order.success),onComplete(order.id)):setMessage(amount<order.target?'Not enough yet — add another 1/4 cup scoop.':'Too much — remove one scoop.');return <><div className="bakeryMeasure"><div className="miniCup"><div className="miniLiquid" style={{height:`${amount*100}%`}}/><b>{amount===0?'0':amount===.25?'1/4':amount===.5?'1/2':amount===.75?'3/4':'1'} cup</b></div><div><button onClick={()=>setAmount(v=>Math.max(0,v-order.step))}>− 1/4</button><button onClick={()=>setAmount(v=>Math.min(1,v+order.step))}>+ 1/4</button></div></div><button className="primary" onClick={check}>Use this amount</button><p className="feedback">{message}</p></>}
function CountOrder({order,onComplete}){const[count,setCount]=useState(0),[message,setMessage]=useState('Move cookies onto the sharing tray.');const check=()=>count===order.target?(setMessage(order.success),onComplete(order.id)):setMessage(`You shared ${count}. Try again.`);return <><div className="cookieCounter"><button onClick={()=>setCount(v=>Math.max(0,v-1))}>−</button><div><span>{'🍪'.repeat(count)||'—'}</span><b>{count} of 8 cookies</b></div><button onClick={()=>setCount(v=>Math.min(order.max,v+1))}>+</button></div><button className="primary" onClick={check}>Give these cookies</button><p className="feedback">{message}</p></>}
function RatioOrder({order,onComplete}){const[a,setA]=useState(0),[b,setB]=useState(0),[m,setM]=useState('Build the requested cupcake mix.');const check=()=>a===order.targetA&&b===order.targetB?(setM(order.success),onComplete(order.id)):setM('Keep the relationship at exactly 3 chocolate for 2 vanilla.');return <><div className="ratioWorkbench"><div><span className="ratioObjects">{'🧁'.repeat(a)||'—'}</span><b>{a} chocolate</b><div className="stepper"><button onClick={()=>setA(v=>Math.max(0,v-1))}>−</button><button onClick={()=>setA(v=>Math.min(6,v+1))}>+</button></div></div><strong>:</strong><div><span className="ratioObjects">{'🍰'.repeat(b)||'—'}</span><b>{b} vanilla</b><div className="stepper"><button onClick={()=>setB(v=>Math.max(0,v-1))}>−</button><button onClick={()=>setB(v=>Math.min(6,v+1))}>+</button></div></div></div><button className="primary" onClick={check}>Pack the order</button><p className="feedback">{m}</p></>}
function DealOrder({order,onComplete}){const[m,setM]=useState('Compare the cost of one basket in each deal.');return <><div className="hubTiles">{order.choices.map((x,i)=><button key={x} onClick={()=>i===order.correct?(setM(order.success),onComplete(order.id)):setM('That supplier costs more for each basket. Try the other deal.')}>{x}</button>)}</div><p className="feedback">{m}</p></>}
export function FractionBakery({activity,onProgress,onExit,completedLessons={}}){const completed=activity?.completedOrders||{},orders=ORDERS.filter(o=>orderUnlocked(o,completedLessons)),stars=orders.filter(o=>completed[o.id]).length,[selected,setSelected]=useState(Math.max(0,orders.findIndex(o=>!completed[o.id]))),order=orders[Math.min(selected,orders.length-1)];const finish=id=>{if(!completed[id])onProgress({completedOrders:{...completed,[id]:true}})};return <main className="app"><header className="hero bakeryHero"><div><small>Fraction Bakery</small><h1>Run the bakery with math.</h1><p>New things you learn create new customer orders back in town.</p></div><button className="secondary" onClick={onExit}>← Back to My World</button></header><section className="bakeryStatus panel"><div><span>⭐</span><b>{stars}/{orders.length} available orders complete</b></div><div className="bakeryUpgrade"><span>{stars===orders.length?'🏆':'🔥'}</span><div><b>{stars===orders.length?'All current orders filled!':'Customers are waiting'}</b><small>{stars===orders.length?'Learn more and new bakery work may arrive.':'Fill the waiting orders to grow the bakery.'}</small></div></div></section><section className="bakeryLayout"><aside className="panel orderQueue"><h2>Customer orders</h2>{orders.map((o,i)=><button key={o.id} className={selected===i?'orderCard active':'orderCard'} onClick={()=>setSelected(i)}><span>{completed[o.id]?'✅':o.avatar}</span><div><b>{o.title}</b><small>{completed[o.id]?'Completed':o.customer+' is waiting'}</small></div></button>)}</aside><section className="panel bakeryCounter"><div className="customerBubble"><span>{order.avatar}</span><div><small>{order.customer}'s order</small><h2>{order.title}</h2><p>{order.prompt}</p></div></div>{order.type==='slices'&&<SliceOrder order={order} onComplete={finish}/>} {order.type==='scoops'&&<ScoopOrder order={order} onComplete={finish}/>} {order.type==='count'&&<CountOrder order={order} onComplete={finish}/>} {order.type==='ratio'&&<RatioOrder order={order} onComplete={finish}/>} {order.type==='deal'&&<DealOrder order={order} onComplete={finish}/>} {completed[order.id]&&<div className="successNote">Order completed — this bakery star is saved.</div>}</section></section></main>}
