import React,{useState}from'react';
import'./worldHubs.css';

const venueMeta={
clinic:{sign:'🐾 ANIMAL CLINIC 🩺',empty:'The clinic is quiet right now.',decor:'clinicDecor',verb:'patients helped'},
studio:{sign:'🎨 PATTERN STUDIO ✂️',empty:'No design requests are waiting.',decor:'studioDecor',verb:'projects finished'},
lab:{sign:'🧪 MEASUREMENT LAB 🔬',empty:'No experiments are waiting.',decor:'labDecor',verb:'experiments completed'}
};
const unlocked=(o,completed)=>!o.unlockAfter||Boolean(completed?.[o.unlockAfter]?.discovered);

function HubShell({kind,title,subtitle,emoji,orders,activity,onProgress,onExit,completedLessons={},children}){const available=orders.filter(o=>unlocked(o,completedLessons)),completed=activity?.completedOrders||{},waiting=available.filter(o=>!completed[o.id]),done=available.length-waiting.length,[selectedId,setSelectedId]=useState(waiting[0]?.id||available[0]?.id),order=available.find(o=>o.id===selectedId)||waiting[0]||available[0],meta=venueMeta[kind];const finish=id=>{if(!completed[id])onProgress({completedOrders:{...completed,[id]:true}})};const allDone=waiting.length===0;return <main className="app"><header className={`hero hubHero ${kind}Hero`}><div><small>{title}</small><h1>{emoji} {subtitle}</h1><p>New requests arrive as new ideas are mastered — and later requests expect stronger reasoning.</p></div><button className="secondary" onClick={onExit}>← Back to My World</button></header><section className="bakeryStatus panel"><div><span className="hubStatusIcon">{kind==='clinic'?'🐾':kind==='studio'?'🎨':'🧪'}</span><b>{waiting.length} waiting · {done} complete</b></div><div className="bakeryUpgrade"><span>{allDone?'🏆':'✨'}</span><div><b>{allDone?'Everything is caught up!':'New work is waiting'}</b><small>{allDone?'Return after more learning to see what changes.':'Orders match — or slightly stretch — the skills that unlocked them.'}</small></div></div></section><section className="bakeryLayout"><aside className={`panel hubVenue ${kind}Venue`}><div className="venueSign">{meta.sign}</div><div className="venueScene"><div className="venueWindowTop">{waiting.length?<div className="venueWaiting">{waiting.map(o=><button key={o.id} className={`venueCustomer ${order?.id===o.id?'active':''}`} onClick={()=>setSelectedId(o.id)}><span>{o.avatar}</span><div><b>{o.customer}</b><small>{o.title}</small>{o.level&&<em>Level {o.level}</em>}</div></button>)}</div>:<div className="venueEmpty"><span>{kind==='clinic'?'🪟':kind==='studio'?'🖼️':'🔬'}</span><b>{meta.empty}</b><small>Head back to lessons. New requests will arrive as new skills are mastered.</small></div>}</div><div className={`venueCounter ${meta.decor}`}/></div><div className="venueTally">✅ {done} {meta.verb}</div></aside><section className="panel bakeryCounter hubWorkArea">{order?<><div className="customerBubble"><span>{order.avatar}</span><div><small>{order.customer}'s request {order.level?`· Level ${order.level}`:''}</small><h2>{order.title}</h2><p>{order.prompt}</p></div></div>{children(order,finish)}{completed[order.id]&&<div className="successNote">Request complete! Choose another waiting request.</div>}</>:<div className="emptyBakery"><span>{emoji}</span><h2>Everything is complete.</h2><p>New work will appear here as more concepts are mastered.</p></div>}</section></section></main>}

const CLINIC=[
{id:'food-half',customer:'Biscuit',avatar:'🐶',title:'Half a bowl',prompt:'Biscuit needs exactly half of the 8 food scoops.',type:'count',target:4,max:8,level:1},
{id:'weight-sort',customer:'Mochi',avatar:'🐱',title:'Choose the light supplies',prompt:'Tap every supply that weighs less than 5 kg.',type:'sort',level:1},
{id:'water-three-fourths',customer:'Pip',avatar:'🐰',title:'Fill the water bowl',prompt:'Pip needs the bowl exactly 3/4 full.',type:'fill',target:3,level:1},
{id:'clinic-scale-blanket',unlockAfter:'scale-robot',customer:'Finn',avatar:'🦊',title:'Scale the pet blanket',prompt:'A puppy blanket is 2 squares wide and 3 squares long. Make a blanket twice as large in both dimensions. What should the new length be?',type:'choice',choices:['5 squares','6 squares','9 squares'],correct:1,level:2},
{id:'clinic-walk-rate',unlockAfter:'race-rate',customer:'Mochi',avatar:'🐱',title:'Walking pace',prompt:'Mochi walks 6 spaces in 3 seconds. At the same pace, how far will she walk in 5 seconds?',type:'choice',choices:['8 spaces','10 spaces','12 spaces'],correct:1,level:3}
];
function ClinicTask({order,onDone}){const[n,setN]=useState(0),[picked,setPicked]=useState([]),[msg,setMsg]=useState('Help the patient.');if(order.type==='choice')return <><div className="hubTiles">{order.choices.map((x,i)=><button key={x} onClick={()=>i===order.correct?(setMsg('Correct — you used the lesson idea in a new care problem.'),onDone(order.id)):setMsg('Not yet. Work from the relationship in the request rather than guessing.')}>{x}</button>)}</div><p className="feedback">{msg}</p></>;if(order.type==='sort'){const items=[['🪶 1 kg',true],['🥕 2 kg',true],['🧺 6 kg',false],['📦 8 kg',false]];const check=()=>{const ok=picked.length===2&&picked.includes(0)&&picked.includes(1);ok?(setMsg('Yes — both selected supplies are under 5 kg.'),onDone(order.id)):setMsg('Look at each weight. Select every supply that is less than 5 kg.')};return <><div className="hubTiles">{items.map((x,i)=><button key={i} className={picked.includes(i)?'chosen':''} onClick={()=>setPicked(v=>v.includes(i)?v.filter(k=>k!==i):[...v,i])}>{x[0]}</button>)}</div><button className="primary" onClick={check}>Check my choices</button><p className="feedback">{msg}</p></>};const target=order.type==='fill'?3:order.target,max=order.type==='fill'?4:order.max,icon=order.type==='fill'?'💧':'🥣';const check=()=>n===target?(setMsg(order.type==='fill'?'Three of four parts makes 3/4.':'Half of 8 is 4.'),onDone(order.id)):setMsg(`You have ${n}. Try again.`);return <><div className="hubCounter"><button onClick={()=>setN(v=>Math.max(0,v-1))}>−</button><div><span>{icon.repeat(n)||'—'}</span><b>{n} of {max}</b></div><button onClick={()=>setN(v=>Math.min(max,v+1))}>+</button></div><button className="primary" onClick={check}>Check care request</button><p className="feedback">{msg}</p></>}
export function AnimalClinic(props){return <HubShell {...props} kind="clinic" title="Animal Clinic" subtitle="Care for animals with numbers." emoji="🐾" orders={CLINIC}>{(o,f)=><ClinicTask key={o.id} order={o} onDone={f}/>}</HubShell>}

const STUDIO=[
{id:'stripe',customer:'Ari',avatar:'🧑‍🎨',title:'Finish the mural',prompt:'Continue the repeating red-blue-red-blue design.',type:'sequence',seq:['🔴','🔵','🔴','🔵'],answer:'🔴',choices:['🔴','🔵','🟡'],level:1},
{id:'grow',customer:'Zoe',avatar:'👧',title:'Growing tile design',prompt:'The design grows 1, 2, 3... What size comes next?',type:'sequence',seq:['■','■■','■■■'],answer:'■■■■',choices:['■■','■■■■','■■■■■'],level:1},
{id:'make',customer:'Kai',avatar:'🧒',title:'Design your own repeat',prompt:'Build an A-B-A-B pattern for a new floor.',type:'make',level:1},
{id:'studio-slope-roof',unlockAfter:'slope-mountain',customer:'Ari',avatar:'🧑‍🎨',title:'Design a roof slope',prompt:'One roof rises 3 squares for every 6 across. Which new roof has the same steepness?',type:'sequence',seq:['rise 3','run 6'],answer:'rise 2, run 4',choices:['rise 2, run 4','rise 3, run 4','rise 4, run 6'],level:3},
{id:'studio-rule-sign',unlockAfter:'build-function-rule',customer:'Zoe',avatar:'👧',title:'Build a sign rule',prompt:'A sign machine changes 2→5 and 4→9. Which rule works for both?',type:'sequence',seq:['2 → 5','4 → 9'],answer:'double, then +1',choices:['double, then +1','add 3 every time','triple, then −1'],level:3}
];
function StudioTask({order,onDone}){const[msg,setMsg]=useState('Find the design rule.'),[made,setMade]=useState([]);if(order.type==='sequence')return <><div className="studioSequence">{order.seq.map((x,i)=><span key={i}>{x}</span>)}<span>?</span></div><div className="hubTiles">{order.choices.map(x=><button key={x} onClick={()=>x===order.answer?(setMsg('You found the rule and transferred it to the studio job!'),onDone(order.id)):setMsg('That changes the relationship. Compare the examples again.')}>{x}</button>)}</div><p className="feedback">{msg}</p></>;const add=x=>setMade(v=>v.length<4?[...v,x]:v),check=()=>made.join('')==='🔶🔷🔶🔷'?(setMsg('You created your own repeating rule!'),onDone(order.id)):setMsg('Try making orange, blue, orange, blue.');return <><div className="studioSequence">{made.map((x,i)=><span key={i}>{x}</span>)}{Array.from({length:4-made.length},(_,i)=><span key={'e'+i}>?</span>)}</div><div className="hubTiles"><button onClick={()=>add('🔶')}>🔶</button><button onClick={()=>add('🔷')}>🔷</button><button onClick={()=>setMade([])}>Reset</button></div><button className="primary" onClick={check}>Show my design</button><p className="feedback">{msg}</p></>}
export function PatternStudio(props){return <HubShell {...props} kind="studio" title="Pattern Studio" subtitle="Create designs from hidden rules." emoji="🎨" orders={STUDIO}>{(o,f)=><StudioTask key={o.id} order={o} onDone={f}/>}</HubShell>}

const LAB=[
{id:'half',customer:'Dr. Nova',avatar:'🥼',title:'Half-full sample',prompt:'Fill the sample tube to 1/2.',target:2,total:4,type:'measure',level:1},
{id:'threequarters',customer:'Dr. Nova',avatar:'🥼',title:'Three-quarter sample',prompt:'Fill the sample tube to 3/4.',target:3,total:4,type:'measure',level:1},
{id:'double',customer:'Rex',avatar:'🤖',title:'Double the recipe',prompt:'A test needs 2 scoops. Make a double batch.',target:4,total:6,type:'measure',level:1},
{id:'lab-scale-reading',unlockAfter:'map-scale',customer:'Dr. Nova',avatar:'🥼',title:'Scale a reading',prompt:'A model reading of 3 units represents 12 real units. What does a model reading of 5 represent?',type:'choice',choices:['15 units','20 units','24 units'],correct:1,level:2},
{id:'lab-machine-rule',unlockAfter:'mystery-machine',customer:'Rex',avatar:'🤖',title:'Machine rule test',prompt:'The machine maps 1→3, 2→5, and 3→7. Without trial-and-error, predict the output for 6.',type:'choice',choices:['11','12','13'],correct:2,level:3}
];
function LabTask({order,onDone}){const[n,setN]=useState(0),[msg,setMsg]=useState('Adjust the sample.');if(order.type==='choice')return <><div className="hubTiles">{order.choices.map((x,i)=><button key={x} onClick={()=>i===order.correct?(setMsg('Confirmed — that relationship holds in the lab test.'),onDone(order.id)):setMsg('That does not preserve the relationship. Recheck the scale or rule.')}>{x}</button>)}</div><p className="feedback">{msg}</p></>;const check=()=>n===order.target?(setMsg('Measurement confirmed!'),onDone(order.id)):setMsg(`The sample is at ${n} parts. Adjust it to ${order.target}.`);return <><div className="labTube"><div style={{height:`${n/order.total*100}%`}}/><b>{n}/{order.total}</b></div><div className="stepper"><button onClick={()=>setN(v=>Math.max(0,v-1))}>−</button><button onClick={()=>setN(v=>Math.min(order.total,v+1))}>+</button></div><button className="primary" onClick={check}>Run experiment</button><p className="feedback">{msg}</p></>}
export function MeasurementLab(props){return <HubShell {...props} kind="lab" title="Measurement Lab" subtitle="Run experiments by measuring precisely." emoji="🧪" orders={LAB}>{(o,f)=><LabTask key={o.id} order={o} onDone={f}/>}</HubShell>}
