import React,{useState}from'react';

function HubShell({kind,title,subtitle,emoji,orders,activity,onProgress,onExit,children}){const completed=activity?.completedOrders||{},done=Object.keys(completed).length,[selected,setSelected]=useState(Math.max(0,orders.findIndex(o=>!completed[o.id]))),order=orders[selected];const finish=id=>{if(!completed[id])onProgress({completedOrders:{...completed,[id]:true}})};return <main className="app"><header className={`hero hubHero ${kind}Hero`}><div><small>{title}</small><h1>{emoji} {subtitle}</h1><p>Pick a request, solve it by doing, and improve this place.</p></div><button className="secondary" onClick={onExit}>← Back to My World</button></header><section className="bakeryStatus panel"><div><span>⭐</span><b>{done}/{orders.length} {title.toLowerCase()} stars</b></div><div className="bakeryUpgrade"><span>{done===orders.length?'🏆':'✨'}</span><div><b>{done===orders.length?'Special upgrade unlocked!':'Next upgrade'}</b><small>{done===orders.length?'Every request is complete.':'Complete every request to improve this building.'}</small></div></div></section><section className="bakeryLayout"><aside className="panel orderQueue"><h2>Requests</h2>{orders.map((o,i)=><button key={o.id} className={selected===i?'orderCard active':'orderCard'} onClick={()=>setSelected(i)}><span>{completed[o.id]?'✅':o.avatar}</span><div><b>{o.title}</b><small>{completed[o.id]?'Completed':o.customer+' needs help'}</small></div></button>)}</aside><section className="panel bakeryCounter"><div className="customerBubble"><span>{order.avatar}</span><div><small>{order.customer}'s request</small><h2>{order.title}</h2><p>{order.prompt}</p></div></div>{children(order,finish)}{completed[order.id]&&<div className="successNote">Request completed — this star is saved.</div>}</section></section></main>}

const CLINIC=[
{id:'food-half',customer:'Biscuit',avatar:'🐶',title:'Half a bowl',prompt:'Biscuit needs exactly half of the 8 food scoops.',type:'count',target:4,max:8},
{id:'weight-sort',customer:'Mochi',avatar:'🐱',title:'Sort the supplies',prompt:'Put the light supplies under 5 kg in the left bin.',type:'sort'},
{id:'water-three-fourths',customer:'Pip',avatar:'🐰',title:'Fill the water bowl',prompt:'Pip needs the bowl exactly 3/4 full.',type:'fill',target:3}
];
function ClinicTask({order,onDone}){const[n,setN]=useState(0),[picked,setPicked]=useState([]),[msg,setMsg]=useState('Help the patient.');if(order.type==='sort'){const items=[['🪶 1 kg',true],['🥕 2 kg',true],['🧺 6 kg',false],['📦 8 kg',false]];const check=()=>{const ok=picked.length===2&&picked.includes(0)&&picked.includes(1);ok?(setMsg('Yes — both are under 5 kg.'),onDone(order.id)):setMsg('Look at each weight. Which ones are less than 5?')};return <><div className="hubTiles">{items.map((x,i)=><button className={picked.includes(i)?'chosen':''} onClick={()=>setPicked(v=>v.includes(i)?v.filter(k=>k!==i):[...v,i])}>{x[0]}</button>)}</div><button className="primary" onClick={check}>Sort supplies</button><p className="feedback">{msg}</p></>};const target=order.type==='fill'?3:order.target,max=order.type==='fill'?4:order.max,icon=order.type==='fill'?'💧':'🥣';const check=()=>n===target?(setMsg(order.type==='fill'?'Three of four parts makes 3/4.':'Half of 8 is 4.'),onDone(order.id)):setMsg(`You have ${n}. Try again.`);return <><div className="hubCounter"><button onClick={()=>setN(v=>Math.max(0,v-1))}>−</button><div><span>{icon.repeat(n)||'—'}</span><b>{n} of {max}</b></div><button onClick={()=>setN(v=>Math.min(max,v+1))}>+</button></div><button className="primary" onClick={check}>Check care request</button><p className="feedback">{msg}</p></>}
export function AnimalClinic(props){return <HubShell {...props} kind="clinic" title="Animal Clinic" subtitle="Care for animals with numbers." emoji="🐾" orders={CLINIC}>{(o,f)=><ClinicTask key={o.id} order={o} onDone={f}/>}</HubShell>}

const STUDIO=[
{id:'stripe',customer:'Ari',avatar:'🧑‍🎨',title:'Finish the mural',prompt:'Continue the repeating red-blue-red-blue design.',type:'sequence',seq:['🔴','🔵','🔴','🔵'],answer:'🔴',choices:['🔴','🔵','🟡']},
{id:'grow',customer:'Zoe',avatar:'👧',title:'Growing tile design',prompt:'The design grows 1, 2, 3... What size comes next?',type:'sequence',seq:['■','■■','■■■'],answer:'■■■■',choices:['■■','■■■■','■■■■■']},
{id:'make',customer:'Kai',avatar:'🧒',title:'Design your own repeat',prompt:'Build an A-B-A-B pattern for a new floor.',type:'make'}
];
function StudioTask({order,onDone}){const[msg,setMsg]=useState('Find the design rule.'),[made,setMade]=useState([]);if(order.type==='sequence')return <><div className="studioSequence">{order.seq.map((x,i)=><span key={i}>{x}</span>)}<span>?</span></div><div className="hubTiles">{order.choices.map(x=><button onClick={()=>x===order.answer?(setMsg('You found the rule!'),onDone(order.id)):setMsg('That changes the rule. Look at how the design repeats or grows.')}>{x}</button>)}</div><p className="feedback">{msg}</p></>;const add=x=>setMade(v=>v.length<4?[...v,x]:v),check=()=>made.join('')==='🔶🔷🔶🔷'?(setMsg('You created your own repeating rule!'),onDone(order.id)):setMsg('Try making orange, blue, orange, blue.');return <><div className="studioSequence">{made.map((x,i)=><span key={i}>{x}</span>)}{Array.from({length:4-made.length},(_,i)=><span key={'e'+i}>?</span>)}</div><div className="hubTiles"><button onClick={()=>add('🔶')}>🔶</button><button onClick={()=>add('🔷')}>🔷</button><button onClick={()=>setMade([])}>Reset</button></div><button className="primary" onClick={check}>Show my design</button><p className="feedback">{msg}</p></>}
export function PatternStudio(props){return <HubShell {...props} kind="studio" title="Pattern Studio" subtitle="Create designs from hidden rules." emoji="🎨" orders={STUDIO}>{(o,f)=><StudioTask key={o.id} order={o} onDone={f}/>}</HubShell>}

const LAB=[
{id:'half',customer:'Dr. Nova',avatar:'🥼',title:'Half-full sample',prompt:'Fill the sample tube to 1/2.',target:2,total:4},
{id:'threequarters',customer:'Dr. Nova',avatar:'🥼',title:'Three-quarter sample',prompt:'Fill the sample tube to 3/4.',target:3,total:4},
{id:'double',customer:'Rex',avatar:'🤖',title:'Double the recipe',prompt:'A test needs 2 scoops. Make a double batch.',target:4,total:6}
];
function LabTask({order,onDone}){const[n,setN]=useState(0),[msg,setMsg]=useState('Adjust the sample.');const check=()=>n===order.target?(setMsg('Measurement confirmed!'),onDone(order.id)):setMsg(`The sample is at ${n} parts. Adjust it to ${order.target}.`);return <><div className="labTube"><div style={{height:`${n/order.total*100}%`}}/><b>{n}/{order.total}</b></div><div className="stepper"><button onClick={()=>setN(v=>Math.max(0,v-1))}>−</button><button onClick={()=>setN(v=>Math.min(order.total,v+1))}>+</button></div><button className="primary" onClick={check}>Run experiment</button><p className="feedback">{msg}</p></>}
export function MeasurementLab(props){return <HubShell {...props} kind="lab" title="Measurement Lab" subtitle="Run experiments by measuring precisely." emoji="🧪" orders={LAB}>{(o,f)=><LabTask key={o.id} order={o} onDone={f}/>}</HubShell>}
